# -*- coding: utf-8 -*-
"""Author content/samples/kitab-al-sulh — the Sulh story, chapter by chapter.

ORIGINAL graded Arabic, composed editorially from the user's uploaded
Turkish fiqh reference (research/sources/sulh-fiqh-turkce.txt). The
Qur'anic clause {وَالصُّلْحُ خَيْرٌ} (al-Nisa 4:128) and the hadith wording
«الصُّلْحُ جَائِزٌ بَيْنَ الْمُسْلِمِينَ…» (Tirmidhi, Ahkam 17) are received
text; everything else is simple original composition in the Hidaya
register, marked pending-scholarly-review. Verb paradigms ride the same
audited engines as the rest of the corpus.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PKG = ROOT / "content/samples/kitab-al-sulh"
(PKG / "chapters").mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import sarf_gen as _sg

import re
DIA = re.compile("[ً-ٰ]")
def bare(s): return DIA.sub("", s)

def tok(full, lex, pos, grammar, ar, en, tr, punct=None):
    t = {"surface": {"full": full, "smart": full, "bare": bare(full)},
         "lex": lex, "pos": pos}
    if grammar: t["grammar"] = grammar
    t["irab"] = {"ar": ar, "en": en, "tr": tr}
    if punct: t["punctAfter"] = punct
    return t

J = lambda text, ar, en, tr: {"text": text, "ar": ar, "en": en, "tr": tr}

S = []

S.append({"id": "s1", "translation": {
 "en": "Sulh is a contract that lifts the dispute between two contending parties.",
 "tr": "Sulh, iki çekişen taraf arasındaki nizâı kaldıran bir akittir."},
 "tokens": [
  tok("الصُّلْحُ","sulh","noun",["mubtada-khabar"],
      "مُبْتَدَأٌ مَرْفُوعٌ — الصُّلْحُ لُغَةً: قَطْعُ النِّزَاعِ.",
      "Mubtada in raf' — «sulh», in the tongue: cutting off dispute.",
      "Merfû mübteda — «sulh» lugatte: nizâı kesmektir."),
  tok("عَقْدٌ","aqd","noun",["mubtada-khabar","masdar"],
      "خَبَرٌ مَرْفُوعٌ — مَصْدَرُ عَقَدَ.",
      "The khabar in raf' — the masdar of «to bind».",
      "Merfû haber — عَقَدَ'nin masdarıdır."),
  tok("يَرْفَعُ","rafaa","verb",["mudari-marfu","jumla-sifa"],
      "مُضَارِعٌ مَرْفُوعٌ — وَالْجُمْلَةُ صِفَةٌ لِـ«عَقْدٌ» فِي مَحَلِّ رَفْعٍ.",
      "A mudari' in raf' — the clause describes «a contract», in raf's position.",
      "Merfû muzâri — cümle «عقد»in sıfatıdır; mahallen merfûdur."),
  tok("النِّزَاعَ","niza","noun",["maful-bihi","masdar"],
      "مَفْعُولٌ بِهِ مَنْصُوبٌ — مَصْدَرُ الْمُفَاعَلَةِ مِنْ نَازَعَ.",
      "The object in nasb — the Form III masdar of «to contend».",
      "Mensub mef'ûlün bih — نَازَعَ'nin müfâale masdarıdır."),
  tok("بَيْنَ","bayna","noun",["maful-fih","idafa-definiteness"],
      "ظَرْفُ مَكَانٍ مَنْصُوبٌ وَهُوَ مُضَافٌ.",
      "A place-adverbial in nasb, mudaf.",
      "Mensub mekân zarfı; muzâftır."),
  tok("الْمُتَخَاصِمَيْنِ","mutakhasim","noun",["idafa-definiteness","ism-fail","form-vi-verbs"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ بِالْيَاءِ — مُثَنَّى اسْمِ فَاعِلِ التَّفَاعُلِ.",
      "Mudaf ilayh, jarr by the ya — the dual of the Form VI participle.",
      "Yâ ile mecrur muzâfun ileyh — tefâulün ism-i fâilinin tesniyesidir.", punct="."),
 ],
 "jumal": [
  J("الصُّلْحُ عَقْدٌ…",
    "جُمْلَةٌ اسْمِيَّةٌ ابْتِدَائِيَّةٌ — لَا مَحَلَّ لَهَا؛ وَجُمْلَةُ «يَرْفَعُ» صِفَةٌ.",
    "An opening nominal sentence — i'rabless; the «lifts» clause is its sifa.",
    "İbtidâî isim cümlesi — mahalsiz; «يرفع» cümlesi sıfattır."),
 ]})

S.append({"id": "s2", "translation": {
 "en": "Allah Most High has said: “And sulh is best” (al-Nisa 4:128).",
 "tr": "Allah Teâlâ buyurdu: «Sulh daha hayırlıdır» (en-Nisâ 4/128)."},
 "tokens": [
  tok("قَالَ","qala","verb",["hollow-verbs"],
      "فِعْلٌ مَاضٍ — أَجْوَفُ.",
      "A past verb — hollow.",
      "Mâzî fiil — ecveftir."),
  tok("اللهُ","allah","propn",["fail"],
      "لَفْظُ الْجَلَالَةِ فَاعِلٌ مَرْفُوعٌ.",
      "The Name of Majesty, fa'il in raf'.",
      "Lafza-i celâl; merfû fâildir."),
  tok("تَعَالَى","taala","verb",["naqis-verbs","form-vi-verbs"],
      "فِعْلٌ مَاضٍ، وَجُمْلَتُهُ مُعْتَرِضَةٌ لِلتَّعْظِيمِ.",
      "A past verb whose clause interposes in reverence.",
      "Mâzî fiil; cümlesi tazim için muterizedir.", punct=":"),
  tok("وَالصُّلْحُ","sulh","noun",["mubtada-khabar"],
      "الْوَاوُ عَلَى مَا قَبْلَهَا فِي الْآيَةِ، وَ«الصُّلْحُ» مُبْتَدَأٌ مَرْفُوعٌ — وَالْجُمْلَةُ مَقُولُ الْقَوْلِ.",
      "The waw follows what precedes it in the aya; «al-sulh» a mubtada in raf' — the clause is the quoted speech.",
      "Vav, âyette öncesine bağlıdır; «الصلح» merfû mübteda — cümle makûlü'l-kavldir."),
  tok("خَيْرٌ","khayr","noun",["mubtada-khabar","ism-tafdil"],
      "خَبَرٌ مَرْفُوعٌ — «خَيْر» بِقُوَّةِ أَفْعَلِ التَّفْضِيلِ.",
      "The khabar in raf' — «khayr» with the comparative's force.",
      "Merfû haber — «خير» ism-i tafdîl kuvvetindedir.", punct="."),
 ],
 "jumal": [
  J("وَالصُّلْحُ خَيْرٌ",
    "جُمْلَةٌ اسْمِيَّةٌ — مَقُولُ الْقَوْلِ فِي مَحَلِّ نَصْبٍ.",
    "A nominal sentence — the quoted speech, in nasb's position.",
    "İsim cümlesi — makûlü'l-kavl olarak mahallen mensubdur."),
 ]})

S.append({"id": "s3", "translation": {
 "en": "And the Prophet, peace be upon him, said: “Sulh is permissible between the Muslims.”",
 "tr": "Peygamber (aleyhisselâm) buyurdu: «Müslümanlar arasında sulh câizdir.»"},
 "tokens": [
  tok("وَقَالَ","qala","verb",["atf-nasaq","hollow-verbs"],
      "الْوَاوُ عَاطِفَةٌ، «قَالَ» مَاضٍ.",
      "The waw joins; «said» a past verb.",
      "Vav atıftır; «قال» mâzîdir."),
  tok("النَّبِيُّ","nabi","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ.","Fa'il in raf'.","Merfû fâildir."),
  tok("عَلَيْهِ","alayhi","part",["huruf-jarr"],
      "جَارٌّ وَمَجْرُورٌ — خَبَرٌ مُقَدَّمٌ لِلدُّعَاءِ.",
      "A jarr-phrase — the fronted khabar of the blessing.",
      "Câr-mecrûr — duanın mukaddem haberidir."),
  tok("السَّلَامُ","salam","noun",["mubtada-khabar"],
      "مُبْتَدَأٌ مُؤَخَّرٌ مَرْفُوعٌ — وَالْجُمْلَةُ مُعْتَرِضَةٌ دُعَائِيَّةٌ.",
      "The delayed mubtada in raf' — a parenthetical blessing.",
      "Muahhar mübteda; merfû — muterize dua cümlesidir.", punct=":"),
  tok("الصُّلْحُ","sulh","noun",["mubtada-khabar"],
      "مُبْتَدَأٌ مَرْفُوعٌ — وَالْجُمْلَةُ مَقُولُ الْقَوْلِ.",
      "Mubtada in raf' — the clause is the quoted speech.",
      "Merfû mübteda — cümle makûlü'l-kavldir."),
  tok("جَائِزٌ","jaiz","noun",["mubtada-khabar","ism-fail"],
      "خَبَرٌ مَرْفُوعٌ — اسْمُ فَاعِلٍ مِنْ جَازَ.",
      "The khabar in raf' — the participle of «to be allowed».",
      "Merfû haber — جَازَ'nin ism-i fâilidir."),
  tok("بَيْنَ","bayna","noun",["maful-fih","idafa-definiteness"],
      "ظَرْفٌ مَنْصُوبٌ وَهُوَ مُضَافٌ.",
      "An adverbial in nasb, mudaf.",
      "Mensub zarf; muzâftır."),
  tok("الْمُسْلِمِينَ","muslim","noun",["idafa-definiteness","jam-mudhakkar-salim","ism-fail"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ بِالْيَاءِ — جَمْعُ مُذَكَّرٍ سَالِمٌ.",
      "Mudaf ilayh, jarr by the ya — a sound masculine plural.",
      "Yâ ile mecrur muzâfun ileyh — cem-i müzekker-i sâlimdir.", punct="."),
 ],
 "jumal": [
  J("الصُّلْحُ جَائِزٌ بَيْنَ الْمُسْلِمِينَ",
    "جُمْلَةٌ اسْمِيَّةٌ — مَقُولُ الْقَوْلِ فِي مَحَلِّ نَصْبٍ.",
    "A nominal sentence — the quoted speech, in nasb's position.",
    "İsim cümlesi — makûlü'l-kavl olarak mahallen mensubdur."),
 ]})

S.append({"id": "s4", "translation": {
 "en": "— “except a sulh that forbids a lawful thing or permits a forbidden one.”",
 "tr": "— «Helâli haram kılan yahut haramı helâl kılan bir sulh müstesnâ.»"},
 "tokens": [
  tok("إِلَّا","illa","part",["istithna"],
      "حَرْفُ اسْتِثْنَاءٍ.",
      "The particle of exception.",
      "İstisnâ harfidir."),
  tok("صُلْحًا","sulh","noun",["istithna"],
      "مُسْتَثْنًى مَنْصُوبٌ.",
      "The excepted, in nasb.",
      "Müstesnâ; mensubdur."),
  tok("حَرَّمَ","harrama","verb",["form-ii-verbs","jumla-sifa"],
      "مَاضٍ مِنَ التَّفْعِيلِ — وَالْجُمْلَةُ صِفَةٌ لِـ«صُلْحًا».",
      "A Form II past — the clause describes «a sulh».",
      "Tef'îl bâbından mâzî — cümle «صلحًا»ın sıfatıdır."),
  tok("حَلَالًا","halal","noun",["maful-bihi"],
      "مَفْعُولٌ بِهِ مَنْصُوبٌ.",
      "The object in nasb.",
      "Mensub mef'ûlün bihtir."),
  tok("أَوْ","aw","part",["atf-nasaq"],
      "حَرْفُ عَطْفٍ.","A joining particle.","Atıf harfidir."),
  tok("أَحَلَّ","ahalla","verb",["atf-nasaq","form-iv-verbs"],
      "مَعْطُوفٌ — مَاضٍ مِنَ الْإِفْعَالِ، مُضَاعَفٌ.",
      "Joined on — a Form IV past, geminate.",
      "Matuf — if'âl bâbından mâzî; muzâaftır."),
  tok("حَرَامًا","haram","noun",["maful-bihi"],
      "مَفْعُولٌ بِهِ مَنْصُوبٌ.",
      "The object in nasb.",
      "Mensub mef'ûlün bihtir.", punct="."),
 ],
 "jumal": [
  J("إِلَّا صُلْحًا حَرَّمَ حَلَالًا…",
    "اسْتِثْنَاءٌ مُتَّصِلٌ مِنْ عُمُومِ الصُّلْحِ الْجَائِزِ؛ وَجُمْلَةُ «حَرَّمَ» صِفَةٌ فِي مَحَلِّ نَصْبٍ.",
    "A connected exception from the general permission; the «forbids» clause its sifa, in nasb's position.",
    "Câiz sulhun umumundan muttasıl istisnâ; «حرّم» cümlesi sıfat olarak mahallen mensubdur."),
 ]})

S.append({"id": "s5", "translation": {
 "en": "So sulh is commended, and the judge urges the disputants toward it.",
 "tr": "Şu halde sulh menduptur; hâkim, hasımları ona teşvik eder."},
 "tokens": [
  tok("فَالصُّلْحُ","sulh","noun",["mubtada-khabar"],
      "الْفَاءُ لِلتَّفْرِيعِ وَ«الصُّلْحُ» مُبْتَدَأٌ مَرْفُوعٌ.",
      "The fa draws the consequence; «al-sulh» a mubtada in raf'.",
      "Fâ tefrî' içindir; «الصلح» merfû mübtedadır."),
  tok("مَنْدُوبٌ","mandub","noun",["mubtada-khabar","ism-maful"],
      "خَبَرٌ مَرْفُوعٌ — اسْمُ مَفْعُولٍ: الْمَطْلُوبُ فِعْلُهُ طَلَبًا غَيْرَ جَازِمٍ.",
      "The khabar in raf' — a passive participle: what the Law asks for without binding.",
      "Merfû haber — ism-i mef'ûl: kesin olmayan taleple istenendir.", punct="،"),
  tok("وَالْقَاضِي","qadi","noun",["atf-nasaq","mubtada-khabar","ism-maqsur-manqus","ism-fail"],
      "الْوَاوُ عَاطِفَةٌ، «الْقَاضِي» مُبْتَدَأٌ مَرْفُوعٌ بِضَمَّةٍ مُقَدَّرَةٍ — مَنْقُوصٌ.",
      "The waw joins; «the judge» a mubtada by an assumed damma — a manqus noun.",
      "Vav atıftır; «القاضي» takdîrî damme ile merfû mübteda — menkûstur."),
  tok("يُرَغِّبُ","raggaba","verb",["mudari-marfu","form-ii-verbs"],
      "مُضَارِعٌ مَرْفُوعٌ مِنَ التَّفْعِيلِ — وَالْجُمْلَةُ خَبَرٌ.",
      "A Form II mudari' in raf' — the clause is the khabar.",
      "Tef'îl bâbından merfû muzâri — cümle haberdir."),
  tok("فِيهِ","fi","part",["huruf-jarr"],
      "جَارٌّ وَمَجْرُورٌ.","A jarr-phrase.","Câr ve mecrûrdur."),
  tok("الْخُصُومَ","khasm","noun",["maful-bihi"],
      "مَفْعُولٌ بِهِ مَنْصُوبٌ — جَمْعُ «خَصْم».",
      "The object in nasb — the plural of «disputant».",
      "Mensub mef'ûlün bih — «خصم»in cem'idir.", punct="."),
 ],
 "jumal": [
  J("وَالْقَاضِي يُرَغِّبُ فِيهِ الْخُصُومَ",
    "جُمْلَةٌ اسْمِيَّةٌ خَبَرُهَا جُمْلَةٌ فِعْلِيَّةٌ — فِي مَحَلِّ رَفْعٍ.",
    "A nominal sentence whose khabar is a verbal clause — in raf's position.",
    "Haberi fiil cümlesi olan isim cümlesi — mahallen merfûdur."),
 ]})

S.append({"id": "s6", "translation": {
 "en": "And it is of three kinds: sulh upon acknowledgment, sulh upon denial, and sulh upon silence.",
 "tr": "Sulh üç nevidir: ikrar üzerine sulh, inkâr üzerine sulh ve sükût üzerine sulh."},
 "tokens": [
  tok("وَهُوَ","huwa","pron",["mubtada-khabar"],
      "الْوَاوُ اسْتِئْنَافِيَّةٌ، «هُوَ» مُبْتَدَأٌ فِي مَحَلِّ رَفْعٍ.",
      "The waw begins afresh; «it» a mubtada in raf's position.",
      "Vav isti'nâfiyedir; «هو» mahallen merfû mübtedadır."),
  tok("ثَلَاثَةُ","thalatha","noun",["mubtada-khabar","idafa-definiteness"],
      "خَبَرٌ مَرْفُوعٌ وَهُوَ مُضَافٌ — جَاءَ بِالتَّاءِ لِأَنَّ الْمَعْدُودَ «نَوْع» مُذَكَّرٌ: قَاعِدَةُ الْعَدَدِ.",
      "The khabar in raf', mudaf — it keeps the TA because the counted «kind» is masculine: the number rule.",
      "Merfû haber; muzâf — ma'dûd olan «نوع» müzekker olduğundan TÂ'lıdır: aded kaidesi."),
  tok("أَنْوَاعٍ","naw","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ — جَمْعٌ بَعْدَ الثَّلَاثَةِ.",
      "Mudaf ilayh in jarr — a plural, as 3–10 demand.",
      "Mecrur muzâfun ileyh — 3–10'dan sonra cemidir.", punct=":"),
  tok("صُلْحٌ","sulh","noun",["badal"],
      "بَدَلٌ مُفَصَّلٌ مِنْ «ثَلَاثَةُ» مَرْفُوعٌ.",
      "A detailing badal of «three», in raf'.",
      "«ثلاثة»den tafsil bedeli; merfûdur."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("إِقْرَارٍ","iqrar","noun",["huruf-jarr","masdar"],
      "مَجْرُورٌ — مَصْدَرُ الْإِفْعَالِ.",
      "In jarr — the Form IV masdar.",
      "Mecrur — if'âl masdarıdır.", punct="،"),
  tok("وَصُلْحٌ","sulh","noun",["atf-nasaq"],
      "مَعْطُوفٌ مَرْفُوعٌ.","Joined, in raf'.","Matuf; merfûdur."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("إِنْكَارٍ","inkar","noun",["huruf-jarr","masdar"],
      "مَجْرُورٌ — مَصْدَرُ الْإِفْعَالِ.",
      "In jarr — the Form IV masdar.",
      "Mecrur — if'âl masdarıdır.", punct="،"),
  tok("وَصُلْحٌ","sulh","noun",["atf-nasaq"],
      "مَعْطُوفٌ مَرْفُوعٌ.","Joined, in raf'.","Matuf; merfûdur."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("سُكُوتٍ","sukut","noun",["huruf-jarr","masdar"],
      "مَجْرُورٌ — مَصْدَرُ سَكَتَ.",
      "In jarr — the masdar of «to be silent».",
      "Mecrur — سَكَتَ'nin masdarıdır.", punct="."),
 ],
 "jumal": [
  J("وَهُوَ ثَلَاثَةُ أَنْوَاعٍ",
    "جُمْلَةٌ اسْمِيَّةٌ مُسْتَأْنَفَةٌ — لَا مَحَلَّ لَهَا؛ وَفِيهَا قَاعِدَةُ الْعَدَدِ ٣–١٠.",
    "A fresh nominal sentence — i'rabless; the 3–10 number rule lives in it.",
    "İsti'nâf isim cümlesi — mahalsiz; içinde 3–10 aded kaidesi vardır."),
 ]})

S.append({"id": "s7", "translation": {
 "en": "And its pillar is the offer and the acceptance.",
 "tr": "Rüknü, icap ve kabuldür."},
 "tokens": [
  tok("وَرُكْنُهُ","rukn","noun",["mubtada-khabar","idafa-definiteness"],
      "الْوَاوُ عَاطِفَةٌ، «رُكْنُ» مُبْتَدَأٌ مَرْفُوعٌ مُضَافٌ إِلَى الْهَاءِ.",
      "The waw joins; «pillar» a mubtada in raf', mudaf to the «its».",
      "Vav atıftır; «ركن» merfû mübteda; هُ zamirine muzâftır."),
  tok("الْإِيجَابُ","ijab","noun",["mubtada-khabar","masdar"],
      "خَبَرٌ مَرْفُوعٌ — مَصْدَرُ الْإِفْعَالِ.",
      "The khabar in raf' — the Form IV masdar.",
      "Merfû haber — if'âl masdarıdır."),
  tok("وَالْقَبُولُ","qabul","noun",["atf-nasaq","masdar"],
      "مَعْطُوفٌ مَرْفُوعٌ.",
      "Joined, in raf'.",
      "Matuf; merfûdur.", punct="."),
 ],
 "jumal": [
  J("وَرُكْنُهُ الْإِيجَابُ وَالْقَبُولُ",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ — لَا مَحَلَّ لَهَا.",
    "A joined nominal sentence — i'rabless.",
    "Matuf isim cümlesi — mahalli yoktur."),
 ]})

TITLE1 = {"ar": "تَعْرِيفُ الصُّلْحِ وَمَشْرُوعِيَّتُهُ",
          "en": "The Definition of Sulh, and Its Legitimacy",
          "tr": "Sulhun Tarifi ve Meşrûiyeti"}

# ---------------------------------------------------------------- chapter 2
S2 = []

S2.append({"id": "s8", "translation": {
 "en": "Sulh upon acknowledgment, when it falls on property, is like a sale.",
 "tr": "İkrar üzerine sulh, bir mal üzerine vâki olursa satım (bey') gibidir."},
 "tokens": [
  tok("فَالصُّلْحُ","sulh","noun",["mubtada-khabar"],
      "الْفَاءُ لِلتَّفْصِيلِ وَ«الصُّلْحُ» مُبْتَدَأٌ مَرْفُوعٌ.",
      "The fa opens the detail; «al-sulh» a mubtada in raf'.",
      "Fâ tafsil içindir; «الصلح» merfû mübtedadır."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("إِقْرَارٍ","iqrar","noun",["huruf-jarr","masdar"],
      "مَجْرُورٌ.","In jarr.","Mecrurdur."),
  tok("إِذَا","idha","part",["idha-shartiyya","maful-fih"],
      "ظَرْفٌ مُتَضَمِّنٌ مَعْنَى الشَّرْطِ.",
      "The adverbial carrying a condition.",
      "Şart manası taşıyan zarftır."),
  tok("وَقَعَ","waqaa","verb",["idha-shartiyya","mithal-verbs"],
      "فِعْلُ الشَّرْطِ — مِثَالٌ وَاوِيٌّ، وَفَاعِلُهُ مُسْتَتِرٌ.",
      "The condition verb — an assimilated (waw) verb, its fa'il concealed.",
      "Şart fiili — misâl-i vâvî; fâili gizlidir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("مَالٍ","mal","noun",["huruf-jarr"],
      "مَجْرُورٌ.","In jarr.","Mecrurdur."),
  tok("فَهُوَ","huwa","pron",["mubtada-khabar"],
      "الْفَاءُ رَابِطَةٌ لِجَوَابِ الشَّرْطِ وَ«هُوَ» مُبْتَدَأٌ.",
      "The fa ties the answer; «it» a mubtada.",
      "Fâ, cevabı bağlar; «هو» mübtedadır."),
  tok("كَالْبَيْعِ","bay","noun",["huruf-jarr","tashbih","mubtada-khabar"],
      "الْكَافُ لِلتَّشْبِيهِ — وَالْجَارُّ وَالْمَجْرُورُ خَبَرٌ.",
      "The kaf of likeness — the phrase is the khabar.",
      "Teşbih kâfı — câr-mecrûr haberdir.", punct="."),
 ],
 "jumal": [
  J("إِذَا وَقَعَ عَلَى مَالٍ فَهُوَ كَالْبَيْعِ",
    "جُمْلَةُ شَرْطٍ ظَرْفِيَّةٌ، جَوَابُهَا بِالْفَاءِ — وَالْجُمْلَتَانِ خَبَرٌ عَنِ الصُّلْحِ.",
    "A when-condition whose answer rides the fa — together the khabar of «sulh».",
    "Zarf yollu şart; cevabı fâ iledir — ikisi birlikte «sulh»un haberidir."),
 ]})

S2.append({"id": "s9", "translation": {
 "en": "And when it falls on a usufruct, it is like a hire.",
 "tr": "Bir menfaat üzerine vâki olursa kira (icâre) gibidir."},
 "tokens": [
  tok("وَإِذَا","idha","part",["atf-nasaq","idha-shartiyya"],
      "الْوَاوُ عَاطِفَةٌ وَ«إِذَا» ظَرْفُ شَرْطٍ.",
      "The waw joins; «when» the conditional adverbial.",
      "Vav atıftır; «إذا» şart zarfıdır."),
  tok("وَقَعَ","waqaa","verb",["idha-shartiyya","mithal-verbs"],
      "فِعْلُ الشَّرْطِ.","The condition verb.","Şart fiilidir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("مَنْفَعَةٍ","manfaa","noun",["huruf-jarr"],
      "مَجْرُورٌ — مَصْدَرٌ مِيمِيٌّ مِنَ النَّفْعِ.",
      "In jarr — a mimic masdar of «benefit».",
      "Mecrur — نفع'den mîmî masdardır."),
  tok("فَهُوَ","huwa","pron",["mubtada-khabar"],
      "الْفَاءُ رَابِطَةٌ وَ«هُوَ» مُبْتَدَأٌ.",
      "The fa ties; «it» a mubtada.",
      "Fâ bağlayıcıdır; «هو» mübtedadır."),
  tok("كَالْإِجَارَةِ","ijara","noun",["huruf-jarr","tashbih","mubtada-khabar"],
      "الْكَافُ لِلتَّشْبِيهِ — وَالْجَارُّ وَالْمَجْرُورُ خَبَرٌ.",
      "The kaf of likeness — the phrase is the khabar.",
      "Teşbih kâfı — câr-mecrûr haberdir.", punct="."),
 ],
 "jumal": [
  J("وَإِذَا وَقَعَ عَلَى مَنْفَعَةٍ فَهُوَ كَالْإِجَارَةِ",
    "جُمْلَةُ شَرْطٍ مَعْطُوفَةٌ — لَا مَحَلَّ لَهَا.",
    "A joined conditional sentence — i'rabless.",
    "Matuf şart cümlesi — mahalli yoktur."),
 ]})

S2.append({"id": "s10", "translation": {
 "en": "And sulh upon denial is permissible — to cut the litigation short.",
 "tr": "İnkâr üzerine sulh câizdir — husumeti kesmek için."},
 "tokens": [
  tok("وَالصُّلْحُ","sulh","noun",["atf-nasaq","mubtada-khabar"],
      "الْوَاوُ عَاطِفَةٌ وَ«الصُّلْحُ» مُبْتَدَأٌ.",
      "The waw joins; «al-sulh» a mubtada.",
      "Vav atıftır; «الصلح» mübtedadır."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("إِنْكَارٍ","inkar","noun",["huruf-jarr","masdar"],
      "مَجْرُورٌ.","In jarr.","Mecrurdur."),
  tok("جَائِزٌ","jaiz","noun",["mubtada-khabar","ism-fail"],
      "خَبَرٌ مَرْفُوعٌ.","The khabar in raf'.","Merfû haberdir."),
  tok("لِقَطْعِ","qat","noun",["huruf-jarr","lam-taleel","masdar","idafa-definiteness"],
      "اللَّامُ لِلتَّعْلِيلِ وَ«قَطْعِ» مَجْرُورٌ مُضَافٌ.",
      "The lam of purpose; «cutting» in jarr, mudaf.",
      "Ta'lîl lâmı; «قطع» mecrur ve muzâftır."),
  tok("الْخُصُومَةِ","khusuma","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ.",
      "Mudaf ilayh in jarr.",
      "Mecrur muzâfun ileyhtir.", punct="."),
 ],
 "jumal": [
  J("وَالصُّلْحُ عَنْ إِنْكَارٍ جَائِزٌ",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ — لَا مَحَلَّ لَهَا.",
    "A joined nominal sentence — i'rabless.",
    "Matuf isim cümlesi — mahalli yoktur."),
 ]})

S2.append({"id": "s11", "translation": {
 "en": "And no sulh is valid over what is not lawful property — like wine.",
 "tr": "Mütekavvim mal olmayan şey üzerine sulh câiz olmaz — şarap gibi."},
 "tokens": [
  tok("وَلَا","la-nafiya","part",["atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«لَا» نَافِيَةٌ.",
      "The waw joins; «la» negates.",
      "Vav atıftır; «لا» nâfiyedir."),
  tok("يَجُوزُ","jawaza","verb",["mudari-marfu","hollow-verbs"],
      "مُضَارِعٌ مَرْفُوعٌ — أَجْوَفُ.",
      "A mudari' in raf' — hollow.",
      "Merfû muzâri — ecveftir."),
  tok("الصُّلْحُ","sulh","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ.","Fa'il in raf'.","Merfû fâildir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("مَا","ma-mawsula","pron",["ism-mawsul","huruf-jarr"],
      "اسْمٌ مَوْصُولٌ فِي مَحَلِّ جَرٍّ.",
      "A relative noun in jarr's position.",
      "İsm-i mevsûl; mahallen mecrurdur."),
  tok("لَيْسَ","laysa","verb",["kana-wa-akhawatuha","ism-mawsul"],
      "«لَيْسَ» وَاسْمُهَا مُسْتَتِرٌ — وَالْجُمْلَةُ صِلَةُ «مَا».",
      "«Laysa» with its concealed noun — the clause is ma's sila.",
      "«ليس»; ismi gizlidir — cümle «ما»nın sılasıdır."),
  tok("بِمَالٍ","mal","noun",["kana-wa-akhawatuha","tawkid","huruf-jarr"],
      "الْبَاءُ زَائِدَةٌ فِي خَبَرِ «لَيْسَ»، وَ«مَالٍ» مَجْرُورٌ لَفْظًا مَنْصُوبٌ مَحَلًّا.",
      "An EXTRA ba on laysa's khabar; «property» jarr in form, nasb in place.",
      "«ليس»nin haberinde ZÂİD بِ; «مال» lafzan mecrur, mahallen mensubdur."),
  tok("مُتَقَوِّمٍ","mutaqawwim","noun",["naat-sifa","ism-fail"],
      "نَعْتٌ مَجْرُورٌ — اسْمُ فَاعِلِ التَّفَعُّلِ: مَا يُبَاحُ الِانْتِفَاعُ بِهِ شَرْعًا.",
      "A na't in jarr — the Form V participle: property the Law lets one use.",
      "Mecrur na't — tefe''ulün ism-i fâili: şer'an intifaı mübah maldır."),
  tok("كَالْخَمْرِ","khamr","noun",["huruf-jarr","tashbih"],
      "الْكَافُ لِلتَّمْثِيلِ.",
      "The kaf of exemplifying.",
      "Temsil kâfıdır.", punct="."),
 ],
 "jumal": [
  J("لَيْسَ بِمَالٍ مُتَقَوِّمٍ",
    "جُمْلَةُ الصِّلَةِ — لَا مَحَلَّ لَهَا؛ وَالْبَاءُ الزَّائِدَةُ تُؤَكِّدُ النَّفْيَ.",
    "The sila clause — i'rabless; the extra ba presses the negation.",
    "Sıla cümlesi — mahalsiz; zâid بِ nefyi pekiştirir."),
 ]})

S2.append({"id": "s12", "translation": {
 "en": "And whoever settles for part of his debt has dropped the rest.",
 "tr": "Kim alacağının bir kısmı üzerine sulh yaparsa, kalanını düşürmüş olur."},
 "tokens": [
  tok("وَمَنْ","man-shart","pron",["in-shartiyya","mubtada-khabar"],
      "اسْمُ شَرْطٍ جَازِمٌ فِي مَحَلِّ رَفْعٍ مُبْتَدَأٌ.",
      "A jazm-working conditional noun, mubtada in raf's position.",
      "Cezm eden şart ismi; mahallen merfû mübtedadır."),
  tok("صَالَحَ","salaha","verb",["in-shartiyya","form-iii-verbs"],
      "فِعْلُ الشَّرْطِ — مَاضٍ فِي مَحَلِّ جَزْمٍ، مِنَ الْمُفَاعَلَةِ.",
      "The condition verb — a past in jazm's position, Form III.",
      "Şart fiili — mahallen meczum mâzî; müfâale bâbındandır."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("بَعْضِ","baad","noun",["huruf-jarr","idafa-definiteness"],
      "مَجْرُورٌ وَهُوَ مُضَافٌ.","In jarr, mudaf.","Mecrur; muzâftır."),
  tok("دَيْنِهِ","dayn","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ، مُضَافٌ إِلَى الْهَاءِ.",
      "Mudaf ilayh in jarr, itself mudaf to «his».",
      "Mecrur muzâfun ileyh; هُ'ya muzâftır."),
  tok("فَقَدْ","qad","part",["in-shartiyya","tawkid"],
      "الْفَاءُ رَابِطَةٌ لِلْجَوَابِ وَ«قَدْ» لِلتَّحْقِيقِ.",
      "The fa ties the answer; «qad» affirms.",
      "Fâ cevabı bağlar; «قد» tahkik içindir."),
  tok("أَسْقَطَ","asqata","verb",["in-shartiyya","form-iv-verbs"],
      "جَوَابُ الشَّرْطِ — مَاضٍ فِي مَحَلِّ جَزْمٍ، مِنَ الْإِفْعَالِ.",
      "The answer — a past in jazm's position, Form IV.",
      "Şartın cevabı — mahallen meczum mâzî; if'âl bâbındandır."),
  tok("الْبَاقِيَ","baqi","noun",["maful-bihi","ism-maqsur-manqus","ism-fail"],
      "مَفْعُولٌ بِهِ مَنْصُوبٌ بِفَتْحَةٍ ظَاهِرَةٍ — مَنْقُوصٌ تَظْهَرُ فَتْحَتُهُ.",
      "The object in nasb — a manqus whose fatha shows plainly.",
      "Mensub mef'ûlün bih — menkûstur; fethası açıkça görünür.", punct="."),
 ],
 "jumal": [
  J("وَمَنْ صَالَحَ… فَقَدْ أَسْقَطَ…",
    "جُمْلَةُ شَرْطٍ: فِعْلُهَا وَجَوَابُهَا مَاضِيَانِ فِي مَحَلِّ جَزْمٍ — وَالْمَجْمُوعُ خَبَرُ «مَنْ».",
    "A conditional whose verb and answer are both pasts in jazm's position — together the khabar of «whoever».",
    "Şart cümlesi: fiili ve cevabı mahallen meczum iki mâzîdir — bütünü «من»in haberidir."),
 ]})

TITLE2 = {"ar": "أَنْوَاعُ الصُّلْحِ وَأَحْكَامُهَا",
          "en": "The Kinds of Sulh, and Their Rulings",
          "tr": "Sulhun Nevileri ve Hükümleri"}

GLOSS = {
 "sulh": {"lemma": "صُلْح", "root": "ص ل ح", "pos": "noun",
   "gloss": {"en": "sulh — amicable settlement", "tr": "sulh, barış"}, "level": 2},
 "aqd": {"lemma": "عَقْد", "root": "ع ق د", "pos": "noun", "plural": "عُقُود",
   "gloss": {"en": "contract", "tr": "akit"}, "level": 2},
 "rafaa": {"lemma": "رَفَعَ", "root": "ر ف ع", "pos": "verb", "form": "I",
   "gloss": {"en": "to lift, remove", "tr": "kaldırmak"}, "level": 2},
 "niza": {"lemma": "نِزَاع", "root": "ن ز ع", "pos": "noun",
   "gloss": {"en": "dispute (Form III masdar)", "tr": "nizâ, çekişme"}, "level": 3},
 "bayna": {"lemma": "بَيْنَ", "root": "ب ي ن", "pos": "noun",
   "gloss": {"en": "between (adverbial)", "tr": "arasında (zarf)"}, "level": 1},
 "mutakhasim": {"lemma": "مُتَخَاصِم", "root": "خ ص م", "pos": "noun",
   "gloss": {"en": "contending party (Form VI participle)", "tr": "çekişen taraf (tefâul ism-i fâili)"}, "level": 4},
 "qala": {"lemma": "قَالَ", "root": "ق و ل", "pos": "verb", "form": "I",
   "gloss": {"en": "to say", "tr": "demek, söylemek"}, "level": 1},
 "allah": {"lemma": "اللَّه", "pos": "propn", "gloss": {"en": "Allah", "tr": "Allah"}, "level": 0},
 "taala": {"lemma": "تَعَالَى", "root": "ع ل و", "pos": "verb", "form": "VI",
   "gloss": {"en": "to be exalted (said of Allah)", "tr": "yüce olmak (Allah hakkında)"}, "level": 2},
 "khayr": {"lemma": "خَيْر", "root": "خ ي ر", "pos": "noun",
   "gloss": {"en": "good; best", "tr": "hayır; daha hayırlı"}, "level": 1},
 "nabi": {"lemma": "نَبِيّ", "root": "ن ب أ", "pos": "noun", "plural": "أَنْبِيَاء",
   "gloss": {"en": "prophet", "tr": "nebî, peygamber"}, "level": 1},
 "alayhi": {"lemma": "عَلَيْهِ", "pos": "part",
   "gloss": {"en": "upon him", "tr": "onun üzerine"}, "level": 1},
 "salam": {"lemma": "سَلَام", "root": "س ل م", "pos": "noun",
   "gloss": {"en": "peace", "tr": "selâm"}, "level": 1},
 "jaiz": {"lemma": "جَائِز", "root": "ج و ز", "pos": "noun",
   "gloss": {"en": "permissible (ism fa'il of جَازَ)", "tr": "câiz"}, "level": 2},
 "muslim": {"lemma": "مُسْلِم", "root": "س ل م", "pos": "noun", "plural": "مُسْلِمُون",
   "gloss": {"en": "Muslim (Form IV participle)", "tr": "Müslüman"}, "level": 1},
 "illa": {"lemma": "إِلَّا", "pos": "part",
   "gloss": {"en": "except", "tr": "ancak, müstesnâ"}, "level": 1},
 "harrama": {"lemma": "حَرَّمَ", "root": "ح ر م", "pos": "verb", "form": "II",
   "gloss": {"en": "to forbid", "tr": "haram kılmak"}, "level": 2},
 "halal": {"lemma": "حَلَال", "root": "ح ل ل", "pos": "noun",
   "gloss": {"en": "the lawful", "tr": "helâl"}, "level": 1},
 "ahalla": {"lemma": "أَحَلَّ", "root": "ح ل ل", "pos": "verb", "form": "IV",
   "gloss": {"en": "to make lawful", "tr": "helâl kılmak"}, "level": 3},
 "haram": {"lemma": "حَرَام", "root": "ح ر م", "pos": "noun",
   "gloss": {"en": "the forbidden", "tr": "haram"}, "level": 1},
 "mandub": {"lemma": "مَنْدُوب", "root": "ن د ب", "pos": "noun",
   "gloss": {"en": "commended (ism maf'ul)", "tr": "mendup"}, "level": 3},
 "qadi": {"lemma": "قَاضٍ (الْقَاضِي)", "root": "ق ض ي", "pos": "noun", "plural": "قُضَاة",
   "gloss": {"en": "judge (a manqus ism fa'il)", "tr": "kadı, hâkim (menkûs ism-i fâil)"}, "level": 2},
 "raggaba": {"lemma": "رَغَّبَ", "root": "ر غ ب", "pos": "verb", "form": "II",
   "gloss": {"en": "to urge, make desirous (with في)", "tr": "teşvik etmek (في ile)"}, "level": 3},
 "fi": {"lemma": "فِي", "pos": "part", "gloss": {"en": "in", "tr": "içinde, -de"}, "level": 1},
 "khasm": {"lemma": "خَصْم", "root": "خ ص م", "pos": "noun", "plural": "خُصُوم",
   "gloss": {"en": "disputant, adversary", "tr": "hasım"}, "level": 3},
 "huwa": {"lemma": "هُوَ", "pos": "pron", "gloss": {"en": "he, it", "tr": "o"}, "level": 1},
 "thalatha": {"lemma": "ثَلَاثَة", "root": "ث ل ث", "pos": "noun",
   "gloss": {"en": "three (keeps its ta before a masculine noun)", "tr": "üç (müzekker ma'dûd önünde tâ'lı)"}, "level": 1},
 "naw": {"lemma": "نَوْع", "root": "ن و ع", "pos": "noun", "plural": "أَنْوَاع",
   "gloss": {"en": "kind, sort", "tr": "nevi, tür"}, "level": 2},
 "aw": {"lemma": "أَوْ", "pos": "part",
   "gloss": {"en": "or", "tr": "veya, yahut"}, "level": 1},
 "an-prep": {"lemma": "عَنْ", "pos": "part",
   "gloss": {"en": "from, upon (here: based on)", "tr": "-den; (burada) üzerine"}, "level": 1},
 "iqrar": {"lemma": "إِقْرَار", "root": "ق ر ر", "pos": "noun",
   "gloss": {"en": "acknowledgment (Form IV masdar)", "tr": "ikrar (if'âl masdarı)"}, "level": 3},
 "inkar": {"lemma": "إِنْكَار", "root": "ن ك ر", "pos": "noun",
   "gloss": {"en": "denial (Form IV masdar)", "tr": "inkâr (if'âl masdarı)"}, "level": 3},
 "sukut": {"lemma": "سُكُوت", "root": "س ك ت", "pos": "noun",
   "gloss": {"en": "silence", "tr": "sükût"}, "level": 3},
 "rukn": {"lemma": "رُكْن", "root": "ر ك ن", "pos": "noun", "plural": "أَرْكَان",
   "gloss": {"en": "pillar, essential element", "tr": "rükün"}, "level": 2},
 "ijab": {"lemma": "إِيجَاب", "root": "و ج ب", "pos": "noun",
   "gloss": {"en": "the offer (Form IV masdar of وَجَبَ)", "tr": "icap (وَجَبَ'nin if'âl masdarı)"}, "level": 3},
 "qabul": {"lemma": "قَبُول", "root": "ق ب ل", "pos": "noun",
   "gloss": {"en": "the acceptance", "tr": "kabul"}, "level": 2},
 "idha": {"lemma": "إِذَا", "pos": "part",
   "gloss": {"en": "when, whenever", "tr": "-dığı zaman"}, "level": 1},
 "ala": {"lemma": "عَلَى", "pos": "part",
   "gloss": {"en": "on, over", "tr": "üzerine, üzerinde"}, "level": 1},
 "la-nafiya": {"lemma": "لَا", "pos": "part",
   "gloss": {"en": "no; not", "tr": "hayır; değil"}, "level": 1},
 "laysa": {"lemma": "لَيْسَ", "root": "ل ي س", "pos": "verb", "form": "I",
   "gloss": {"en": "is not (conjugates in the past only)", "tr": "değildir (yalnız mâzîde çekilir)"}, "level": 2},
 "waqaa": {"lemma": "وَقَعَ", "root": "و ق ع", "pos": "verb", "form": "I",
   "gloss": {"en": "to fall, occur", "tr": "vâki olmak, düşmek"}, "level": 2},
 "mal": {"lemma": "مَال", "root": "م و ل", "pos": "noun", "plural": "أَمْوَال",
   "gloss": {"en": "property, wealth", "tr": "mal"}, "level": 1},
 "bay": {"lemma": "بَيْع", "root": "ب ي ع", "pos": "noun", "plural": "بُيُوع",
   "gloss": {"en": "sale", "tr": "satım, bey'"}, "level": 2},
 "manfaa": {"lemma": "مَنْفَعَة", "root": "ن ف ع", "pos": "noun", "plural": "مَنَافِع",
   "gloss": {"en": "usufruct, benefit", "tr": "menfaat"}, "level": 3},
 "ijara": {"lemma": "إِجَارَة", "root": "أ ج ر", "pos": "noun",
   "gloss": {"en": "hire, lease", "tr": "icâre, kira"}, "level": 3},
 "jawaza": {"lemma": "جَازَ", "root": "ج و ز", "pos": "verb", "form": "I",
   "gloss": {"en": "to be permissible", "tr": "câiz olmak"}, "level": 2},
 "ma-mawsula": {"lemma": "مَا (الْمَوْصُولَة)", "pos": "pron",
   "gloss": {"en": "that which (relative)", "tr": "şey ki (ism-i mevsûl)"}, "level": 3},
 "mutaqawwim": {"lemma": "مُتَقَوِّم", "root": "ق و م", "pos": "noun",
   "gloss": {"en": "lawful to use — of property (Form V participle)", "tr": "mütekavvim (intifaı mübah mal)"}, "level": 5},
 "khamr": {"lemma": "خَمْر", "root": "خ م ر", "pos": "noun",
   "gloss": {"en": "wine", "tr": "şarap, hamr"}, "level": 3},
 "qat": {"lemma": "قَطْع", "root": "ق ط ع", "pos": "noun",
   "gloss": {"en": "cutting off", "tr": "kesme, kat'"}, "level": 2},
 "khusuma": {"lemma": "خُصُومَة", "root": "خ ص م", "pos": "noun",
   "gloss": {"en": "litigation, quarrel", "tr": "husumet, dava"}, "level": 4},
 "man-shart": {"lemma": "مَنْ (الشَّرْطِيَّة)", "pos": "pron",
   "gloss": {"en": "whoever (conditional)", "tr": "her kim (şart)"}, "level": 2},
 "salaha": {"lemma": "صَالَحَ", "root": "ص ل ح", "pos": "verb", "form": "III",
   "gloss": {"en": "to make settlement with", "tr": "sulh yapmak, uzlaşmak"}, "level": 3},
 "baad": {"lemma": "بَعْض", "root": "ب ع ض", "pos": "noun",
   "gloss": {"en": "part, some", "tr": "bazı, kısım"}, "level": 2},
 "dayn": {"lemma": "دَيْن", "root": "د ي ن", "pos": "noun", "plural": "دُيُون",
   "gloss": {"en": "debt", "tr": "borç, deyn"}, "level": 3},
 "qad": {"lemma": "قَدْ", "pos": "part",
   "gloss": {"en": "indeed (with the past: completion)", "tr": "gerçekten (mâzî ile: tahkik)"}, "level": 2},
 "asqata": {"lemma": "أَسْقَطَ", "root": "س ق ط", "pos": "verb", "form": "IV",
   "gloss": {"en": "to drop, waive", "tr": "düşürmek, ıskat etmek"}, "level": 3},
 "baqi": {"lemma": "بَاقٍ (الْبَاقِي)", "root": "ب ق ي", "pos": "noun",
   "gloss": {"en": "the remainder (ism fa'il of بَقِيَ)", "tr": "bâkî, kalan"}, "level": 3},
 "mana": {"lemma": "مَعْنًى", "root": "ع ن ي", "pos": "noun", "plural": "مَعَانٍ",
   "gloss": {"en": "meaning, sense", "tr": "mâna"}, "level": 2},
 "sitta": {"lemma": "سِتَّة", "root": "س ت ت", "pos": "noun",
   "gloss": {"en": "six", "tr": "altı"}, "level": 1},
 "hasab": {"lemma": "حَسَب", "root": "ح س ب", "pos": "noun",
   "gloss": {"en": "measure, accordance (عَلَى حَسَبِ: according to)", "tr": "ölçü (عَلَى حَسَبِ: -e göre)"}, "level": 4},
 "badal-iwad": {"lemma": "بَدَل", "root": "ب د ل", "pos": "noun", "plural": "أَبْدَال",
   "gloss": {"en": "consideration, exchange-value (of the sulh)", "tr": "bedel (sulh bedeli)"}, "level": 3},
 "in-shart": {"lemma": "إِنْ (الشَّرْطِيَّة)", "pos": "part",
   "gloss": {"en": "if (conditional, governs jazm)", "tr": "eğer (şart edatı, cezmeder)"}, "level": 2},
 "ayn-thing": {"lemma": "عَيْن", "root": "ع ي ن", "pos": "noun", "plural": "أَعْيَان",
   "gloss": {"en": "specified thing, corporeal object (fiqh)", "tr": "ayn — muayyen şey (fıkıh)"}, "level": 4},
 "ukhra": {"lemma": "أُخْرَى", "root": "أ خ ر", "pos": "noun",
   "gloss": {"en": "other (feminine)", "tr": "başka, diğer (müennes)"}, "level": 2},
 "aqall": {"lemma": "أَقَلّ", "root": "ق ل ل", "pos": "noun",
   "gloss": {"en": "less, fewer (ism tafdil)", "tr": "daha az (ism-i tafdîl)"}, "level": 3},
 "min": {"lemma": "مِنْ", "pos": "prep",
   "gloss": {"en": "from, than", "tr": "-den; -e göre"}, "level": 1},
 "hiba": {"lemma": "هِبَة", "root": "و هـ ب", "pos": "noun",
   "gloss": {"en": "gift (contract)", "tr": "hibe (akdi)"}, "level": 3},
 "mudda": {"lemma": "مُدَّة", "root": "م د د", "pos": "noun", "plural": "مُدَد",
   "gloss": {"en": "period, term", "tr": "müddet, süre"}, "level": 2},
 "malum": {"lemma": "مَعْلُوم", "root": "ع ل م", "pos": "noun",
   "gloss": {"en": "known (ism maf'ul)", "tr": "malum, bilinen (ism-i mef'ûl)"}, "level": 2},
 "intifa": {"lemma": "اِنْتِفَاع", "root": "ن ف ع", "pos": "noun",
   "gloss": {"en": "use, benefiting (Form VIII masdar)", "tr": "intifa, yararlanma (iftiâl masdarı)"}, "level": 4},
 "bi-la": {"lemma": "بِلَا", "pos": "prep",
   "gloss": {"en": "without", "tr": "-sız, olmaksızın"}, "level": 2},
 "ariya": {"lemma": "عَارِيَّة", "root": "ع و ر", "pos": "noun",
   "gloss": {"en": "loan for use (contract)", "tr": "âriyet (akdi)"}, "level": 4},
 "muajjal": {"lemma": "مُؤَجَّل", "root": "أ ج ل", "pos": "noun",
   "gloss": {"en": "deferred to a term (Form II ism maf'ul)", "tr": "müeccel, vadeli (tef'îl ism-i mef'ûlü)"}, "level": 4},
 "salam-aqd": {"lemma": "سَلَم", "root": "س ل م", "pos": "noun",
   "gloss": {"en": "salam — forward purchase (contract)", "tr": "selem (akdi)"}, "level": 5},
 "shart": {"lemma": "شَرْط", "root": "ش ر ط", "pos": "noun", "plural": "شُرُوط",
   "gloss": {"en": "condition", "tr": "şart"}, "level": 2},
 "an-nasiba": {"lemma": "أَنْ", "pos": "part",
   "gloss": {"en": "that (masdar-maker, governs nasb)", "tr": "-mesi (masdariyye, nasb eder)"}, "level": 2},
 "kana": {"lemma": "كَانَ", "root": "ك و ن", "pos": "verb", "form": "I",
   "gloss": {"en": "to be", "tr": "olmak, idi"}, "level": 1},
 "maqdur": {"lemma": "مَقْدُور", "root": "ق د ر", "pos": "noun",
   "gloss": {"en": "within one's power (ism maf'ul)", "tr": "makdur, güç yetirilen (ism-i mef'ûl)"}, "level": 4},
 "taslim": {"lemma": "تَسْلِيم", "root": "س ل م", "pos": "noun",
   "gloss": {"en": "delivery, handing over (Form II masdar)", "tr": "teslim (tef'îl masdarı)"}, "level": 3},
 "ishtarata": {"lemma": "اِشْتَرَطَ", "root": "ش ر ط", "pos": "verb", "form": "VIII",
   "gloss": {"en": "to stipulate", "tr": "şart koşmak"}, "level": 4},
 "mutasalih": {"lemma": "مُتَصَالِح", "root": "ص ل ح", "pos": "noun",
   "gloss": {"en": "party to a sulh (Form VI ism fa'il)", "tr": "sulh yapan taraf (tefâul ism-i fâili)"}, "level": 5},
 "aql": {"lemma": "عَقْل", "root": "ع ق ل", "pos": "noun", "plural": "عُقُول",
   "gloss": {"en": "reason, intellect", "tr": "akıl"}, "level": 1},
 "majnun": {"lemma": "مَجْنُون", "root": "ج ن ن", "pos": "noun",
   "gloss": {"en": "insane (ism maf'ul)", "tr": "mecnun, deli (ism-i mef'ûl)"}, "level": 3},
 "sabiy": {"lemma": "صَبِيّ", "root": "ص ب ي", "pos": "noun", "plural": "صِبْيَان",
   "gloss": {"en": "boy, minor", "tr": "sabî, çocuk"}, "level": 3},
 "alladhi": {"lemma": "الَّذِي", "pos": "pron",
   "gloss": {"en": "who, which (relative)", "tr": "ki o (ism-i mevsûl)"}, "level": 1},
 "mayyaza": {"lemma": "مَيَّزَ", "root": "م ي ز", "pos": "verb", "form": "II",
   "gloss": {"en": "to discern, distinguish", "tr": "temyiz etmek, ayırt etmek"}, "level": 3},
 "bulugh": {"lemma": "بُلُوغ", "root": "ب ل غ", "pos": "noun",
   "gloss": {"en": "puberty (masdar)", "tr": "bülûğ (masdar)"}, "level": 3},
 "madhun": {"lemma": "مَأْذُون", "root": "أ ذ ن", "pos": "noun",
   "gloss": {"en": "permitted (to trade) — ism maf'ul", "tr": "me'zun, izinli (ism-i mef'ûl)"}, "level": 5},
 "lahu": {"lemma": "لَهُ", "pos": "part",
   "gloss": {"en": "to him, his", "tr": "onun, ona ait"}, "level": 1},
 "naf": {"lemma": "نَفْع", "root": "ن ف ع", "pos": "noun",
   "gloss": {"en": "benefit", "tr": "yarar, nef'"}, "level": 2},
 "zahir": {"lemma": "ظَاهِر", "root": "ظ هـ ر", "pos": "noun",
   "gloss": {"en": "clear, evident (ism fa'il)", "tr": "zâhir, açık (ism-i fâil)"}, "level": 2},
 "saghir": {"lemma": "صَغِير", "root": "ص غ ر", "pos": "noun", "plural": "صِغَار",
   "gloss": {"en": "small; the minor", "tr": "küçük; sagîr"}, "level": 1},
 "darar": {"lemma": "ضَرَر", "root": "ض ر ر", "pos": "noun",
   "gloss": {"en": "harm", "tr": "zarar"}, "level": 2},
 "bayyin": {"lemma": "بَيِّن", "root": "ب ي ن", "pos": "noun",
   "gloss": {"en": "plain, manifest", "tr": "açık, belli"}, "level": 4},
 "innama": {"lemma": "إِنَّمَا", "pos": "part",
   "gloss": {"en": "only, no more than", "tr": "ancak, yalnızca"}, "level": 2},
 "ab": {"lemma": "أَب", "root": "أ ب و", "pos": "noun", "plural": "آبَاء",
   "gloss": {"en": "father (one of the five nouns)", "tr": "baba (esmâ-i hamseden)"}, "level": 1},
 "jadd": {"lemma": "جَدّ", "root": "ج د د", "pos": "noun", "plural": "أَجْدَاد",
   "gloss": {"en": "grandfather", "tr": "dede"}, "level": 2},
 "wasi": {"lemma": "وَصِيّ", "root": "و ص ي", "pos": "noun", "plural": "أَوْصِيَاء",
   "gloss": {"en": "appointed guardian", "tr": "vasî"}, "level": 4},
 "murtadd": {"lemma": "مُرْتَدّ", "root": "ر د د", "pos": "noun",
   "gloss": {"en": "apostate (Form VIII ism fa'il)", "tr": "mürted (iftiâl ism-i fâili)"}, "level": 5},
 "mawquf": {"lemma": "مَوْقُوف", "root": "و ق ف", "pos": "noun",
   "gloss": {"en": "suspended (ism maf'ul)", "tr": "mevkuf, askıda (ism-i mef'ûl)"}, "level": 4},
 "inda": {"lemma": "عِنْدَ", "pos": "noun",
   "gloss": {"en": "with, in the view of", "tr": "yanında; -e göre"}, "level": 1},
 "abu-hanifa": {"lemma": "أَبُو حَنِيفَةَ", "pos": "propn",
   "gloss": {"en": "Abu Hanifa (d. 150 AH)", "tr": "Ebû Hanîfe (v. 150 h.)"}, "level": 0},
 "nafidh": {"lemma": "نَافِذ", "root": "ن ف ذ", "pos": "noun",
   "gloss": {"en": "effective, operative (ism fa'il)", "tr": "nâfiz, geçerli (ism-i fâil)"}, "level": 5},
 "dhahab": {"lemma": "ذَهَب", "root": "ذ هـ ب", "pos": "noun",
   "gloss": {"en": "gold", "tr": "altın"}, "level": 2},
 "akhdh": {"lemma": "أَخْذ", "root": "أ خ ذ", "pos": "noun",
   "gloss": {"en": "taking (masdar)", "tr": "alma, ahz (masdar)"}, "level": 3},
 "haqq-sulh": {"lemma": "حَقّ", "root": "ح ق ق", "pos": "noun", "plural": "حُقُوق",
   "gloss": {"en": "right, due", "tr": "hak"}, "level": 1},
 "ibra": {"lemma": "إِبْرَاء", "root": "ب ر أ", "pos": "noun",
   "gloss": {"en": "release, discharge (Form IV masdar)", "tr": "ibrâ (if'âl masdarı)"}, "level": 4},
 "akthar": {"lemma": "أَكْثَر", "root": "ك ث ر", "pos": "noun",
   "gloss": {"en": "more (ism tafdil)", "tr": "daha çok (ism-i tafdîl)"}, "level": 2},
 "lam-jazima": {"lemma": "لَمْ", "pos": "part",
   "gloss": {"en": "did not (jazm + past sense)", "tr": "-medi (cezmeder, mâzîye çevirir)"}, "level": 1},
 "lianna": {"lemma": "لِأَنَّ", "pos": "part",
   "gloss": {"en": "because", "tr": "çünkü"}, "level": 2},
 "ziyada": {"lemma": "زِيَادَة", "root": "ز ي د", "pos": "noun",
   "gloss": {"en": "excess, increase", "tr": "ziyade, fazlalık"}, "level": 3},
 "riba": {"lemma": "رِبًا", "root": "ر ب و", "pos": "noun",
   "gloss": {"en": "riba — usurious excess", "tr": "ribâ, faiz"}, "level": 3},
 "ikhtalafa": {"lemma": "اِخْتَلَفَ", "root": "خ ل ف", "pos": "verb", "form": "VIII",
   "gloss": {"en": "to differ", "tr": "ihtilâf etmek, farklı olmak"}, "level": 3},
 "qabd": {"lemma": "قَبْض", "root": "ق ب ض", "pos": "noun",
   "gloss": {"en": "taking possession (masdar)", "tr": "kabz (masdar)"}, "level": 4},
 "majlis": {"lemma": "مَجْلِس", "root": "ج ل س", "pos": "noun", "plural": "مَجَالِس",
   "gloss": {"en": "session; the contract session", "tr": "meclis; akit meclisi"}, "level": 2},
 "hall-due": {"lemma": "حَالّ", "root": "ح ل ل", "pos": "noun",
   "gloss": {"en": "due now, immediate (of debt)", "tr": "hâll — vadesi gelmiş, peşin"}, "level": 5},
 "mithl": {"lemma": "مِثْل", "root": "م ث ل", "pos": "noun", "plural": "أَمْثَال",
   "gloss": {"en": "the like of", "tr": "misil, benzeri"}, "level": 2},
 "jins": {"lemma": "جِنْس", "root": "ج ن س", "pos": "noun", "plural": "أَجْنَاس",
   "gloss": {"en": "kind, genus", "tr": "cins"}, "level": 3},
 "sahib": {"lemma": "صَاحِب", "root": "ص ح ب", "pos": "noun", "plural": "أَصْحَاب",
   "gloss": {"en": "owner, holder", "tr": "sahip"}, "level": 1},
 "tajil-haste": {"lemma": "تَعْجِيل", "root": "ع ج ل", "pos": "noun",
   "gloss": {"en": "demanding prompt payment (Form II masdar)", "tr": "ta'cîl — peşin isteme (tef'îl masdarı)"}, "level": 5},
 "akhar": {"lemma": "آخَر", "root": "أ خ ر", "pos": "noun",
   "gloss": {"en": "another (diptote)", "tr": "başka, diğer (gayr-ı munsarif)"}, "level": 2},
}

# ---------------------------------------------------------------- chapter 3 (s13-s18)
S3 = []

S3.append({"id": "s13", "translation": {
 "en": "Sulh takes effect in the sense of six different contracts, according to its consideration.",
 "tr": "Sulh, bedeline göre altı akit mânasında vâki olur."},
 "tokens": [
  tok("وَيَقَعُ","waqaa","verb",["fail","mudari-marfu","mithal-verbs"],
      "الْوَاوُ اسْتِئْنَافِيَّةٌ وَ«يَقَعُ» مُضَارِعٌ مَرْفُوعٌ — مِثَالٌ وَاوِيٌّ حُذِفَتْ وَاوُهُ فِي الْمُضَارِعِ.",
      "The waw resumes; «it falls» a mudari' in raf' — a waw-initial verb whose waw drops in the mudari'.",
      "İsti'nâf vâvı; «يقع» merfû muzâri — misâl-i vâvî, muzâride vâvı düşer."),
  tok("الصُّلْحُ","sulh","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ.","The fa'il in raf'.","Merfû fâildir."),
  tok("بِمَعْنَى","mana","noun",["huruf-jarr","idafa-definiteness","ism-maqsur-manqus"],
      "الْبَاءُ جَارَّةٌ وَ«مَعْنَى» مَجْرُورٌ بِكَسْرَةٍ مُقَدَّرَةٍ — مَقْصُورٌ — وَهُوَ مُضَافٌ.",
      "The ba governs; «sense» in jarr by an assumed kasra — maqsur — and mudaf.",
      "بِ cer harfi; «معنى» takdîrî kesreyle mecrur — maksûr — ve muzâftır."),
  tok("سِتَّةِ","sitta","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ وَهُوَ مُضَافٌ — الْعَدَدُ مِنْ ثَلَاثَةٍ إِلَى عَشَرَةٍ يُضَافُ إِلَى جَمْعٍ.",
      "Mudaf ilayh in jarr, itself mudaf — three through ten annex to a plural.",
      "Mecrur muzâfun ileyh; kendisi de muzâf — üçten ona kadar sayı cemîye muzâf olur."),
  tok("عُقُودٍ","aqd","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ — جَمْعُ «عَقْد».",
      "Mudaf ilayh in jarr — the plural of «contract».",
      "Mecrur muzâfun ileyh — «عقد»in cem'idir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("حَسَبِ","hasab","noun",["huruf-jarr","idafa-definiteness"],
      "اسْمٌ مَجْرُورٌ وَهُوَ مُضَافٌ — أَيْ بِمِقْدَارِهِ.",
      "In jarr, mudaf — «according to».",
      "Mecrur isim; muzâf — «-e göre» demektir."),
  tok("الْبَدَلِ","badal-iwad","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ — بَدَلُ الصُّلْحِ: الْعِوَضُ الْمُصَالَحُ عَلَيْهِ.",
      "Mudaf ilayh in jarr — the sulh's consideration: what is settled upon.",
      "Mecrur muzâfun ileyh — sulh bedeli: üzerinde anlaşılan ivazdır.", punct="."),
 ],
 "jumal": [
  J("وَيَقَعُ الصُّلْحُ…",
    "جُمْلَةٌ فِعْلِيَّةٌ مُسْتَأْنَفَةٌ — لَا مَحَلَّ لَهَا.",
    "A resumed verbal clause — i'rabless.",
    "Müste'nefe fiil cümlesi — mahalsizdir."),
 ]})

S3.append({"id": "s14", "translation": {
 "en": "If it falls on a different specified thing it is a sale; and if on less than the debt, it is a gift.",
 "tr": "Başka bir ayn üzerine vâki olursa bey'dir; alacaktan daha azı üzerine olursa hibedir."},
 "tokens": [
  tok("فَإِنْ","in-shart","part",["in-shartiyya"],
      "الْفَاءُ لِلتَّفْرِيعِ وَ«إِنْ» شَرْطِيَّةٌ تَجْزِمُ فِعْلَيْنِ.",
      "The fa branches; «if» conditional, jazm on two verbs.",
      "Tefrî' fâsı; «إن» şartiyedir, iki fiili cezmeder."),
  tok("وَقَعَ","waqaa","verb",["in-shartiyya","fail","mithal-verbs"],
      "فِعْلُ الشَّرْطِ مَاضٍ فِي مَحَلِّ جَزْمٍ وَالْفَاعِلُ مُسْتَتِرٌ.",
      "The condition verb, past, in jazm position, agent hidden.",
      "Şart fiili; mâzî, mahallen meczum; fâili gizlidir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("عَيْنٍ","ayn-thing","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ — الْعَيْنُ: الشَّيْءُ الْمُعَيَّنُ الْقَائِمُ.",
      "In jarr — «'ayn»: a specified, existing thing.",
      "Mecrur isim — «ayn»: muayyen, mevcut şeydir."),
  tok("أُخْرَى","ukhra","noun",["naat-sifa","ism-maqsur-manqus"],
      "نَعْتٌ مَجْرُورٌ بِكَسْرَةٍ مُقَدَّرَةٍ — مَقْصُورٌ.",
      "An attribute in jarr by an assumed kasra — maqsur.",
      "Takdîrî kesreyle mecrur sıfat — maksûrdur."),
  tok("فَهُوَ","huwa","pron",["in-shartiyya","mubtada-khabar"],
      "الْفَاءُ رَابِطَةٌ لِلْجَوَابِ وَ«هُوَ» مُبْتَدَأٌ — وَالْجُمْلَةُ جَوَابُ الشَّرْطِ فِي مَحَلِّ جَزْمٍ.",
      "The fa binds the answer; «it» a mubtada — the clause the condition's answer, in jazm position.",
      "Cevabı bağlayan fâ; «هو» mübteda — cümle, şartın cevabı olarak mahallen meczumdur."),
  tok("بَيْعٌ","bay","noun",["mubtada-khabar"],
      "خَبَرٌ مَرْفُوعٌ.","The khabar in raf'.","Merfû haberdir.", punct="•"),
  tok("وَإِنْ","in-shart","part",["in-shartiyya","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«إِنْ» شَرْطِيَّةٌ.",
      "The waw joins; «if» conditional.",
      "Atıf vâvı; «إن» şartiyedir."),
  tok("وَقَعَ","waqaa","verb",["in-shartiyya","fail"],
      "فِعْلُ الشَّرْطِ فِي مَحَلِّ جَزْمٍ.",
      "The condition verb in jazm position.",
      "Şart fiili; mahallen meczumdur."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("أَقَلَّ","aqall","noun",["huruf-jarr","ism-tafdil","mamnu-min-sarf"],
      "اسْمٌ مَجْرُورٌ وَعَلَامَةُ جَرِّهِ الْفَتْحَةُ — اسْمُ تَفْضِيلٍ مَمْنُوعٌ مِنَ الصَّرْفِ.",
      "In jarr marked by FATHA — an ism tafdil, barred from tanwin.",
      "Mecrur; cer alâmeti FETHADIR — gayr-ı munsarif ism-i tafdîldir."),
  tok("مِنَ","min","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ — صِلَةُ «أَقَلَّ».",
      "A jarr particle — completing «less».",
      "Cer harfi — «أقلّ»in sılasıdır."),
  tok("الدَّيْنِ","dayn","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("فَهُوَ","huwa","pron",["in-shartiyya","mubtada-khabar"],
      "الْفَاءُ رَابِطَةٌ وَ«هُوَ» مُبْتَدَأٌ.",
      "The binding fa; «it» a mubtada.",
      "Râbıta fâsı; «هو» mübtedadır."),
  tok("هِبَةٌ","hiba","noun",["mubtada-khabar"],
      "خَبَرٌ مَرْفُوعٌ — لِأَنَّهُ تَرَكَ بَعْضَ حَقِّهِ بِلَا عِوَضٍ.",
      "The khabar in raf' — for he left part of his right with nothing in return.",
      "Merfû haber — çünkü hakkının bir kısmını ivazsız bırakmıştır.", punct="."),
 ],
 "jumal": [
  J("فَإِنْ وَقَعَ… فَهُوَ بَيْعٌ",
    "جُمْلَةُ شَرْطٍ وَجَوَابُهَا الِاسْمِيُّ الْمَقْرُونُ بِالْفَاءِ فِي مَحَلِّ جَزْمٍ.",
    "A conditional clause; its nominal answer, fa-bound, in jazm position.",
    "Şart cümlesi; fâ ile bağlanan isim cümlesi cevabı mahallen meczumdur."),
  J("وَإِنْ وَقَعَ… فَهُوَ هِبَةٌ",
    "جُمْلَةُ شَرْطٍ مَعْطُوفَةٌ عَلَى الْأُولَى.",
    "A second conditional clause, joined to the first.",
    "İlk şart cümlesine matuf ikinci şart cümlesidir."),
 ]})

S3.append({"id": "s15", "translation": {
 "en": "And if it falls on a benefit for a known period, it is a hire.",
 "tr": "Bilinen bir süre için bir menfaat üzerine vâki olursa icâredir."},
 "tokens": [
  tok("وَإِنْ","in-shart","part",["in-shartiyya","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«إِنْ» شَرْطِيَّةٌ.",
      "The waw joins; «if» conditional.",
      "Atıf vâvı; «إن» şartiyedir."),
  tok("وَقَعَ","waqaa","verb",["in-shartiyya","fail"],
      "فِعْلُ الشَّرْطِ فِي مَحَلِّ جَزْمٍ.",
      "The condition verb in jazm position.",
      "Şart fiili; mahallen meczumdur."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("مَنْفَعَةٍ","manfaa","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("مُدَّةً","mudda","noun",["maful-fih"],
      "ظَرْفُ زَمَانٍ مَنْصُوبٌ.",
      "An adverbial of time in nasb.",
      "Mensub zaman zarfıdır."),
  tok("مَعْلُومَةً","malum","noun",["naat-sifa","ism-maful"],
      "نَعْتٌ مَنْصُوبٌ — اسْمُ مَفْعُولٍ.",
      "An attribute in nasb — a passive participle.",
      "Mensub sıfat — ism-i mef'ûldür."),
  tok("فَهُوَ","huwa","pron",["in-shartiyya","mubtada-khabar"],
      "الْفَاءُ رَابِطَةٌ وَ«هُوَ» مُبْتَدَأٌ.",
      "The binding fa; «it» a mubtada.",
      "Râbıta fâsı; «هو» mübtedadır."),
  tok("إِجَارَةٌ","ijara","noun",["mubtada-khabar"],
      "خَبَرٌ مَرْفُوعٌ — لِأَنَّهُ تَمْلِيكُ الْمَنَافِعِ بِعِوَضٍ.",
      "The khabar in raf' — for it grants uses in exchange for value.",
      "Merfû haber — çünkü menfaatleri ivaz karşılığı temliktir.", punct="."),
 ],
 "jumal": [
  J("وَإِنْ وَقَعَ… فَهُوَ إِجَارَةٌ",
    "جُمْلَةُ شَرْطٍ مَعْطُوفَةٌ؛ جَوَابُهَا فِي مَحَلِّ جَزْمٍ.",
    "A joined conditional; its answer in jazm position.",
    "Matuf şart cümlesi; cevabı mahallen meczumdur."),
 ]})

S3.append({"id": "s16", "translation": {
 "en": "And sulh over mere use, with no consideration, is a loan for use.",
 "tr": "Bedelsiz yararlanma üzerine sulh, âriyettir."},
 "tokens": [
  tok("وَالصُّلْحُ","sulh","noun",["mubtada-khabar","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«الصُّلْحُ» مُبْتَدَأٌ مَرْفُوعٌ.",
      "The waw joins; «sulh» a mubtada in raf'.",
      "Atıf vâvı; «الصلح» merfû mübtedadır."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("الِانْتِفَاعِ","intifa","noun",["huruf-jarr","masdar","form-viii-verbs"],
      "اسْمٌ مَجْرُورٌ — مَصْدَرُ الِافْتِعَالِ مِنَ النَّفْعِ.",
      "In jarr — the Form VIII masdar of «benefit».",
      "Mecrur isim — nef'den iftiâl masdarıdır."),
  tok("بِلَا","bi-la","part",["huruf-jarr"],
      "الْبَاءُ جَارَّةٌ وَ«لَا» مُقْحَمَةٌ.",
      "The ba governs; «la» slipped in between.",
      "بِ cer harfi; «لا» araya girmiştir."),
  tok("بَدَلٍ","badal-iwad","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("عَارِيَّةٌ","ariya","noun",["mubtada-khabar"],
      "خَبَرٌ مَرْفُوعٌ — الْعَارِيَّةُ: تَمْلِيكُ الْمَنَافِعِ بِلَا عِوَضٍ.",
      "The khabar in raf' — the 'ariyya: granting uses with nothing in return.",
      "Merfû haber — âriyet: menfaatleri ivazsız temliktir.", punct="."),
 ],
 "jumal": [
  J("وَالصُّلْحُ عَلَى الِانْتِفَاعِ… عَارِيَّةٌ",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ — لَا مَحَلَّ لَهَا.",
    "A joined nominal clause — i'rabless.",
    "Matuf isim cümlesi — mahalsizdir."),
 ]})

S3.append({"id": "s17", "translation": {
 "en": "And sulh over a known, deferred consideration is a salam.",
 "tr": "Vadeli, bilinen bir bedel üzerine sulh ise selemdir."},
 "tokens": [
  tok("وَالصُّلْحُ","sulh","noun",["mubtada-khabar","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«الصُّلْحُ» مُبْتَدَأٌ.",
      "The waw joins; «sulh» a mubtada.",
      "Atıf vâvı; «الصلح» mübtedadır."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("بَدَلٍ","badal-iwad","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("مُؤَجَّلٍ","muajjal","noun",["naat-sifa","ism-maful","form-ii-verbs"],
      "نَعْتٌ مَجْرُورٌ — اسْمُ مَفْعُولِ التَّفْعِيلِ: مُؤَخَّرٌ إِلَى أَجَلٍ.",
      "An attribute in jarr — the Form II passive participle: put off to a term.",
      "Mecrur sıfat — tef'îlin ism-i mef'ûlü: bir ecele ertelenmiş demektir."),
  tok("مَعْلُومٍ","malum","noun",["naat-sifa","ism-maful"],
      "نَعْتٌ ثَانٍ مَجْرُورٌ.",
      "A second attribute in jarr.",
      "İkinci sıfat; mecrurdur."),
  tok("سَلَمٌ","salam-aqd","noun",["mubtada-khabar"],
      "خَبَرٌ مَرْفُوعٌ — السَّلَمُ: بَيْعُ آجِلٍ بِعَاجِلٍ.",
      "The khabar in raf' — salam: buying the deferred with the present.",
      "Merfû haber — selem: veresiyeyi peşinle satın almaktır.", punct="."),
 ],
 "jumal": [
  J("وَالصُّلْحُ عَلَى بَدَلٍ مُؤَجَّلٍ… سَلَمٌ",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ — لَا مَحَلَّ لَهَا.",
    "A joined nominal clause — i'rabless.",
    "Matuf isim cümlesi — mahalsizdir."),
 ]})

S3.append({"id": "s18", "translation": {
 "en": "And the consideration's condition: that it be known, and within one's power to deliver.",
 "tr": "Bedelin şartı: bilinen ve teslimine güç yetirilen olmasıdır."},
 "tokens": [
  tok("وَشَرْطُ","shart","noun",["mubtada-khabar","idafa-definiteness"],
      "الْوَاوُ عَاطِفَةٌ وَ«شَرْطُ» مُبْتَدَأٌ مَرْفُوعٌ وَهُوَ مُضَافٌ.",
      "The waw joins; «condition» a mubtada in raf', mudaf.",
      "Atıf vâvı; «شرط» merfû mübteda; muzâftır."),
  tok("الْبَدَلِ","badal-iwad","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ.","Mudaf ilayh in jarr.","Mecrur muzâfun ileyhtir."),
  tok("أَنْ","an-nasiba","part",["an-masdariyya"],
      "«أَنْ» مَصْدَرِيَّةٌ نَاصِبَةٌ — وَالْمَصْدَرُ الْمُؤَوَّلُ خَبَرُ الْمُبْتَدَإِ.",
      "«An», the masdar-maker, governing nasb — the derived masdar is the khabar.",
      "«أن» masdariyye ve nâsıbedir — müevvel masdar, mübtedanın haberidir."),
  tok("يَكُونَ","kana","verb",["an-masdariyya","kana-wa-akhawatuha"],
      "مُضَارِعُ «كَانَ» مَنْصُوبٌ بِأَنْ وَاسْمُهَا مُسْتَتِرٌ.",
      "Kana's mudari' in nasb after «an», its noun concealed.",
      "«كان»ın muzârisi; «أن» ile mensub, ismi gizlidir."),
  tok("مَعْلُومًا","malum","noun",["kana-wa-akhawatuha","ism-maful"],
      "خَبَرُ «يَكُونَ» مَنْصُوبٌ.",
      "Kana's khabar in nasb.",
      "«يكون»un haberi; mensubdur."),
  tok("مَقْدُورًا","maqdur","noun",["kana-wa-akhawatuha","ism-maful"],
      "خَبَرٌ ثَانٍ مَنْصُوبٌ — اسْمُ مَفْعُولٍ.",
      "A second khabar in nasb — a passive participle.",
      "İkinci haber; mensub — ism-i mef'ûldür."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ — صِلَةُ «مَقْدُورًا».",
      "A jarr particle — completing «within power».",
      "Cer harfi — «مقدورًا»nın sılasıdır."),
  tok("تَسْلِيمِهِ","taslim","noun",["huruf-jarr","masdar","form-ii-verbs","idafa-definiteness"],
      "اسْمٌ مَجْرُورٌ وَهُوَ مُضَافٌ وَالْهَاءُ مُضَافٌ إِلَيْهِ — مَصْدَرُ التَّفْعِيلِ.",
      "In jarr, mudaf, the ha its mudaf ilayh — the Form II masdar.",
      "Mecrur isim; muzâf, hâ muzâfun ileyh — tef'îl masdarıdır.", punct="."),
 ],
 "jumal": [
  J("وَشَرْطُ الْبَدَلِ أَنْ يَكُونَ…",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ؛ خَبَرُهَا الْمَصْدَرُ الْمُؤَوَّلُ مِنْ «أَنْ» وَمَا بَعْدَهَا.",
    "A joined nominal clause; its khabar the masdar derived from «an» and what follows.",
    "Matuf isim cümlesi; haberi, «أن» ve sonrasından müevvel masdardır."),
 ]})

TITLE3 = {"ar": "صِلَةُ الصُّلْحِ بِالْعُقُودِ وَشَرْطُ الْبَدَلِ",
          "en": "Sulh in the Guise of Other Contracts, and the Condition of the Consideration",
          "tr": "Sulhun Diğer Akitlerle İlişkisi ve Bedelin Şartı"}

# ---------------------------------------------------------------- chapter 4 (s19-s23)
S4 = []

S4.append({"id": "s19", "translation": {
 "en": "Reason is a condition in the two parties: the sulh of the insane, and of the child who cannot yet discern, is not valid.",
 "tr": "Sulh yapan iki tarafta akıl şarttır: delinin ve henüz temyiz edemeyen çocuğun sulhu geçerli olmaz."},
 "tokens": [
  tok("وَيُشْتَرَطُ","ishtarata","verb",["naib-al-fail","form-viii-verbs","mudari-marfu"],
      "الْوَاوُ اسْتِئْنَافِيَّةٌ وَ«يُشْتَرَطُ» مُضَارِعُ الِافْتِعَالِ مَبْنِيٌّ لِلْمَجْهُولِ مَرْفُوعٌ.",
      "The waw resumes; «it is stipulated» the Form VIII passive mudari' in raf'.",
      "İsti'nâf vâvı; «يشترط» iftiâlin meçhul muzârisi; merfûdur."),
  tok("فِي","fi","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("الْمُتَصَالِحَيْنِ","mutasalih","noun",["huruf-jarr","ism-fail","form-vi-verbs"],
      "اسْمٌ مَجْرُورٌ بِالْيَاءِ لِأَنَّهُ مُثَنًّى — اسْمُ فَاعِلِ التَّفَاعُلِ.",
      "In jarr by the YA, being dual — the Form VI participle.",
      "Tesniye olduğu için YÂ ile mecrur — tefâulün ism-i fâilidir."),
  tok("الْعَقْلُ","aql","noun",["naib-al-fail"],
      "نَائِبُ الْفَاعِلِ مَرْفُوعٌ.",
      "The deputy fa'il in raf'.",
      "Merfû nâib-i fâildir.", punct="•"),
  tok("فَلَا","la-nafiya","part",[],
      "الْفَاءُ لِلتَّفْرِيعِ وَ«لَا» نَافِيَةٌ.",
      "The fa branches; «la» negates.",
      "Tefrî' fâsı; «لا» nâfiyedir."),
  tok("يَجُوزُ","jawaza","verb",["fail","hollow-verbs","mudari-marfu"],
      "مُضَارِعٌ مَرْفُوعٌ — أَجْوَفُ.",
      "A mudari' in raf' — hollow.",
      "Merfû muzâri — ecveftir."),
  tok("صُلْحُ","sulh","noun",["fail","idafa-definiteness"],
      "فَاعِلٌ مَرْفُوعٌ وَهُوَ مُضَافٌ.",
      "The fa'il in raf', mudaf.",
      "Merfû fâil; muzâftır."),
  tok("الْمَجْنُونِ","majnun","noun",["idafa-definiteness","ism-maful"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ — اسْمُ مَفْعُولٍ.",
      "Mudaf ilayh in jarr — a passive participle.",
      "Mecrur muzâfun ileyh — ism-i mef'ûldür."),
  tok("وَالصَّبِيِّ","sabiy","noun",["atf-nasaq"],
      "مَعْطُوفٌ مَجْرُورٌ.",
      "Joined, in jarr.",
      "Matuf; mecrurdur."),
  tok("الَّذِي","alladhi","pron",["ism-mawsul","naat-sifa"],
      "اسْمٌ مَوْصُولٌ نَعْتٌ لِلصَّبِيِّ فِي مَحَلِّ جَرٍّ.",
      "A relative, attribute of the child, in jarr position.",
      "İsm-i mevsûl; çocuğun sıfatı olarak mahallen mecrurdur."),
  tok("لَا","la-nafiya","part",[],
      "«لَا» نَافِيَةٌ.","The negating «la».","Nefiy «لا»sıdır."),
  tok("يُمَيِّزُ","mayyaza","verb",["fail","form-ii-verbs","ism-mawsul","mudari-marfu"],
      "مُضَارِعُ التَّفْعِيلِ مَرْفُوعٌ وَالْفَاعِلُ مُسْتَتِرٌ — وَالْجُمْلَةُ صِلَةُ الْمَوْصُولِ.",
      "The Form II mudari' in raf', agent hidden — the clause the relative's sila.",
      "Tef'îlin muzârisi; merfû, fâili gizli — cümle, mevsûlün sılasıdır.", punct="."),
 ],
 "jumal": [
  J("وَيُشْتَرَطُ فِي الْمُتَصَالِحَيْنِ الْعَقْلُ",
    "جُمْلَةٌ فِعْلِيَّةٌ مُسْتَأْنَفَةٌ — لَا مَحَلَّ لَهَا.",
    "A resumed verbal clause — i'rabless.",
    "Müste'nefe fiil cümlesi — mahalsizdir."),
  J("لَا يُمَيِّزُ",
    "جُمْلَةٌ فِعْلِيَّةٌ صِلَةُ الْمَوْصُولِ — لَا مَحَلَّ لَهَا.",
    "A verbal clause, the relative's sila — i'rabless.",
    "Mevsûlün sılası olan fiil cümlesi — mahalsizdir."),
 ]})

S4.append({"id": "s20", "translation": {
 "en": "And puberty is not a condition: the sulh of a child permitted to trade is valid when a clear benefit is his.",
 "tr": "Bülûğ şart değildir: ticarete izinli çocuğun sulhu, açık bir yararı olduğunda geçerlidir."},
 "tokens": [
  tok("وَالْبُلُوغُ","bulugh","noun",["mubtada-khabar","masdar"],
      "الْوَاوُ عَاطِفَةٌ وَ«الْبُلُوغُ» مُبْتَدَأٌ مَرْفُوعٌ.",
      "The waw joins; «puberty» a mubtada in raf'.",
      "Atıf vâvı; «البلوغ» merfû mübtedadır."),
  tok("لَيْسَ","laysa","verb",["kana-wa-akhawatuha"],
      "«لَيْسَ» وَاسْمُهَا مُسْتَتِرٌ — وَالْجُمْلَةُ خَبَرُ الْمُبْتَدَإِ.",
      "«Laysa», its noun concealed — the clause the mubtada's khabar.",
      "«ليس»; ismi gizli — cümle, mübtedanın haberidir."),
  tok("بِشَرْطٍ","shart","noun",["kana-wa-akhawatuha","tawkid","huruf-jarr"],
      "الْبَاءُ زَائِدَةٌ فِي خَبَرِ «لَيْسَ»، وَ«شَرْطٍ» مَجْرُورٌ لَفْظًا مَنْصُوبٌ مَحَلًّا.",
      "An EXTRA ba on laysa's khabar; «condition» jarr in form, nasb in place.",
      "«ليس»nin haberinde ZÂİD بِ; «شرط» lafzan mecrur, mahallen mensubdur.", punct="•"),
  tok("فَيَجُوزُ","jawaza","verb",["fail","hollow-verbs","mudari-marfu"],
      "الْفَاءُ لِلتَّفْرِيعِ وَ«يَجُوزُ» مُضَارِعٌ مَرْفُوعٌ.",
      "The fa branches; «is valid» a mudari' in raf'.",
      "Tefrî' fâsı; «يجوز» merfû muzâridir."),
  tok("صُلْحُ","sulh","noun",["fail","idafa-definiteness"],
      "فَاعِلٌ مَرْفُوعٌ مُضَافٌ.","The fa'il in raf', mudaf.","Merfû fâil; muzâftır."),
  tok("الصَّبِيِّ","sabiy","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ.","Mudaf ilayh in jarr.","Mecrur muzâfun ileyhtir."),
  tok("الْمَأْذُونِ","madhun","noun",["naat-sifa","ism-maful"],
      "نَعْتٌ مَجْرُورٌ — اسْمُ مَفْعُولٍ: الَّذِي أُذِنَ لَهُ فِي التِّجَارَةِ.",
      "An attribute in jarr — the participle: one permitted to trade.",
      "Mecrur sıfat — ism-i mef'ûl: ticarete izin verilmiş demektir."),
  tok("إِذَا","idha","part",["idha-shartiyya"],
      "«إِذَا» ظَرْفٌ لِمَا يُسْتَقْبَلُ مُتَضَمِّنٌ مَعْنَى الشَّرْطِ.",
      "«Idha», a future adverbial carrying conditional force.",
      "«إذا», şart mânası taşıyan istikbal zarfıdır."),
  tok("كَانَ","kana","verb",["idha-shartiyya","kana-wa-akhawatuha"],
      "فِعْلُ الشَّرْطِ — «كَانَ» النَّاقِصَةُ.",
      "The condition verb — defective kana.",
      "Şart fiili — nâkıs «كان»dır."),
  tok("لَهُ","lahu","part",["huruf-jarr","kana-wa-akhawatuha","anwa-al-khabar"],
      "اللَّامُ جَارَّةٌ وَالْهَاءُ مَجْرُورٌ — وَالْجَارُّ خَبَرُ «كَانَ» مُقَدَّمٌ.",
      "The lam governs the ha — the phrase kana's fronted khabar.",
      "Lâm cer harfi, hâ mecrur — câr, «كان»ın öne alınmış haberidir."),
  tok("نَفْعٌ","naf","noun",["kana-wa-akhawatuha"],
      "اسْمُ «كَانَ» مُؤَخَّرٌ مَرْفُوعٌ.",
      "Kana's delayed noun in raf'.",
      "«كان»ın sona kalmış ismi; merfûdur."),
  tok("ظَاهِرٌ","zahir","noun",["naat-sifa","ism-fail"],
      "نَعْتٌ مَرْفُوعٌ — اسْمُ فَاعِلٍ.",
      "An attribute in raf' — an active participle.",
      "Merfû sıfat — ism-i fâildir.", punct="."),
 ],
 "jumal": [
  J("وَالْبُلُوغُ لَيْسَ بِشَرْطٍ",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ؛ خَبَرُهَا جُمْلَةُ «لَيْسَ».",
    "A joined nominal clause; its khabar the laysa-clause.",
    "Matuf isim cümlesi; haberi «ليس» cümlesidir."),
  J("إِذَا كَانَ لَهُ نَفْعٌ ظَاهِرٌ",
    "جُمْلَةُ شَرْطٍ غَيْرِ جَازِمٍ — فِي مَحَلِّ نَصْبٍ عَلَى الظَّرْفِيَّةِ.",
    "A non-jazm conditional clause — in nasb position as an adverbial.",
    "Cezmetmeyen şart cümlesi — zarfiyet üzere mahallen mensubdur."),
 ]})

S4.append({"id": "s21", "translation": {
 "en": "And sulh on the minor's behalf is not permitted when it carries a clear harm to him.",
 "tr": "Küçük aleyhine sulh, ona açık bir zarar taşıdığında câiz olmaz."},
 "tokens": [
  tok("وَلَا","la-nafiya","part",[],
      "الْوَاوُ عَاطِفَةٌ وَ«لَا» نَافِيَةٌ.",
      "The waw joins; «la» negates.",
      "Atıf vâvı; «لا» nâfiyedir."),
  tok("يَجُوزُ","jawaza","verb",["fail","hollow-verbs","mudari-marfu"],
      "مُضَارِعٌ مَرْفُوعٌ.","A mudari' in raf'.","Merfû muzâridir."),
  tok("الصُّلْحُ","sulh","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ.","The fa'il in raf'.","Merfû fâildir."),
  tok("عَنِ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ — أَيْ نِيَابَةً عَنْهُ.",
      "A jarr particle — on his behalf.",
      "Cer harfi — onun adına demektir."),
  tok("الصَّغِيرِ","saghir","noun",["huruf-jarr","sifa-mushabbaha"],
      "اسْمٌ مَجْرُورٌ — صِفَةٌ مُشَبَّهَةٌ.",
      "In jarr — a sifa mushabbaha.",
      "Mecrur isim — sıfat-ı müşebbehedir."),
  tok("إِذَا","idha","part",["idha-shartiyya"],
      "ظَرْفٌ مُتَضَمِّنٌ مَعْنَى الشَّرْطِ.",
      "An adverbial with conditional force.",
      "Şart mânası taşıyan zarftır."),
  tok("كَانَ","kana","verb",["idha-shartiyya","kana-wa-akhawatuha"],
      "فِعْلُ الشَّرْطِ.","The condition verb.","Şart fiilidir."),
  tok("فِيهِ","fi","part",["huruf-jarr","kana-wa-akhawatuha","anwa-al-khabar"],
      "«فِي» جَارَّةٌ وَالْهَاءُ مَجْرُورٌ — وَالْجَارُّ خَبَرُ «كَانَ» مُقَدَّمٌ.",
      "«In» governs the ha — kana's fronted khabar.",
      "«في» cer harfi, hâ mecrur — «كان»ın öne alınmış haberidir."),
  tok("ضَرَرٌ","darar","noun",["kana-wa-akhawatuha"],
      "اسْمُ «كَانَ» مُؤَخَّرٌ مَرْفُوعٌ.",
      "Kana's delayed noun in raf'.",
      "«كان»ın sona kalmış ismi; merfûdur."),
  tok("بَيِّنٌ","bayyin","noun",["naat-sifa","sifa-mushabbaha"],
      "نَعْتٌ مَرْفُوعٌ.","An attribute in raf'.","Merfû sıfattır.", punct="."),
 ],
 "jumal": [
  J("وَلَا يَجُوزُ الصُّلْحُ عَنِ الصَّغِيرِ…",
    "جُمْلَةٌ فِعْلِيَّةٌ مَعْطُوفَةٌ — لَا مَحَلَّ لَهَا.",
    "A joined verbal clause — i'rabless.",
    "Matuf fiil cümlesi — mahalsizdir."),
 ]})

S4.append({"id": "s22", "translation": {
 "en": "Only his father, his grandfather, or his guardian settles on his behalf.",
 "tr": "Onun adına ancak babası, dedesi yahut vasîsi sulh yapar."},
 "tokens": [
  tok("وَإِنَّمَا","innama","part",["innama-kaffa","qasr"],
      "الْوَاوُ عَاطِفَةٌ وَ«إِنَّمَا» أَدَاةُ حَصْرٍ — كَفَّتْ «مَا» عَمَلَ «إِنَّ».",
      "The waw joins; «innama» restricts — the ma has muzzled inna's government.",
      "Atıf vâvı; «إنما» hasr edatıdır — «ما», «إنّ»in amelini keffetmiştir."),
  tok("يُصَالِحُ","salaha","verb",["fail","form-iii-verbs","mudari-marfu"],
      "مُضَارِعُ الْمُفَاعَلَةِ مَرْفُوعٌ.",
      "The Form III mudari' in raf'.",
      "Müfâalenin muzârisi; merfûdur."),
  tok("عَنْهُ","an-prep","part",["huruf-jarr"],
      "«عَنْ» جَارَّةٌ وَالْهَاءُ مَجْرُورٌ.",
      "«On behalf» governs the ha.",
      "«عن» cer harfi; hâ mecrurdur."),
  tok("أَبُوهُ","ab","noun",["fail","five-nouns","idafa-definiteness"],
      "فَاعِلٌ مَرْفُوعٌ بِالْوَاوِ — مِنَ الْأَسْمَاءِ الْخَمْسَةِ — وَالْهَاءُ مُضَافٌ إِلَيْهِ.",
      "The fa'il in raf' by the WAW — one of the five nouns — the ha its mudaf ilayh.",
      "VAV ile merfû fâil — esmâ-i hamseden — hâ, muzâfun ileyhtir."),
  tok("أَوْ","aw","part",["atf-nasaq"],
      "حَرْفُ عَطْفٍ لِلتَّخْيِيرِ.",
      "A joining particle of alternatives.",
      "Muhayyerlik bildiren atıf harfidir."),
  tok("جَدُّهُ","jadd","noun",["atf-nasaq","idafa-definiteness"],
      "مَعْطُوفٌ مَرْفُوعٌ وَالْهَاءُ مُضَافٌ إِلَيْهِ.",
      "Joined, in raf'; the ha its mudaf ilayh.",
      "Matuf; merfû — hâ, muzâfun ileyhtir."),
  tok("أَوْ","aw","part",["atf-nasaq"],
      "حَرْفُ عَطْفٍ.","A joining particle.","Atıf harfidir."),
  tok("وَصِيُّهُ","wasi","noun",["atf-nasaq","idafa-definiteness"],
      "مَعْطُوفٌ مَرْفُوعٌ وَالْهَاءُ مُضَافٌ إِلَيْهِ.",
      "Joined, in raf'; the ha its mudaf ilayh.",
      "Matuf; merfû — hâ, muzâfun ileyhtir.", punct="."),
 ],
 "jumal": [
  J("وَإِنَّمَا يُصَالِحُ عَنْهُ أَبُوهُ…",
    "جُمْلَةٌ فِعْلِيَّةٌ مَعْطُوفَةٌ — وَ«إِنَّمَا» تُفِيدُ قَصْرَ الْحُكْمِ عَلَى هَؤُلَاءِ.",
    "A joined verbal clause — «innama» restricts the ruling to these three.",
    "Matuf fiil cümlesi — «إنما», hükmü bu üçüne hasreder."),
 ]})

S4.append({"id": "s23", "translation": {
 "en": "And the apostate's sulh is suspended according to Abu Hanifa, and effective according to the Two Companions.",
 "tr": "Mürtedin sulhu, Ebû Hanîfe'ye göre askıda; İmâmeyn'e göre ise geçerlidir."},
 "tokens": [
  tok("وَصُلْحُ","sulh","noun",["mubtada-khabar","idafa-definiteness"],
      "الْوَاوُ عَاطِفَةٌ وَ«صُلْحُ» مُبْتَدَأٌ مَرْفُوعٌ مُضَافٌ.",
      "The waw joins; «sulh» a mubtada in raf', mudaf.",
      "Atıf vâvı; «صلح» merfû mübteda; muzâftır."),
  tok("الْمُرْتَدِّ","murtadd","noun",["idafa-definiteness","ism-fail","form-viii-verbs"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ — اسْمُ فَاعِلِ الِافْتِعَالِ مِنَ الرِّدَّةِ.",
      "Mudaf ilayh in jarr — the Form VIII participle, from apostasy.",
      "Mecrur muzâfun ileyh — riddetten iftiâlin ism-i fâilidir."),
  tok("مَوْقُوفٌ","mawquf","noun",["mubtada-khabar","ism-maful"],
      "خَبَرٌ مَرْفُوعٌ — اسْمُ مَفْعُولٍ: مُعَلَّقٌ لَا يَنْفُذُ حَتَّى يُسْلِمَ.",
      "The khabar in raf' — a participle: suspended, taking no effect till he returns to Islam.",
      "Merfû haber — ism-i mef'ûl: askıdadır, İslâm'a dönmedikçe geçmez."),
  tok("عِنْدَ","inda","noun",["maful-fih","idafa-definiteness"],
      "ظَرْفٌ مَنْصُوبٌ وَهُوَ مُضَافٌ — أَيْ فِي قَوْلِهِ.",
      "An adverbial in nasb, mudaf — in his view.",
      "Mensub zarf; muzâf — onun kavlince demektir."),
  tok("أَبِي","ab","noun",["idafa-definiteness","five-nouns"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ بِالْيَاءِ — مِنَ الْأَسْمَاءِ الْخَمْسَةِ — وَهُوَ مُضَافٌ.",
      "Mudaf ilayh in jarr by the YA — one of the five nouns — itself mudaf.",
      "YÂ ile mecrur muzâfun ileyh — esmâ-i hamseden — kendisi de muzâftır."),
  tok("حَنِيفَةَ","abu-hanifa","propn",["idafa-definiteness","mamnu-min-sarf"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ بِالْفَتْحَةِ — عَلَمٌ مَمْنُوعٌ مِنَ الصَّرْفِ.",
      "Mudaf ilayh in jarr by FATHA — a diptote proper name.",
      "FETHA ile mecrur muzâfun ileyh — gayr-ı munsarif özel isimdir.", punct="•"),
  tok("وَنَافِذٌ","nafidh","noun",["atf-nasaq","mubtada-khabar","ism-fail"],
      "مَعْطُوفٌ عَلَى «مَوْقُوفٌ» مَرْفُوعٌ — اسْمُ فَاعِلٍ.",
      "Joined to «suspended», in raf' — an active participle.",
      "«موقوف»a matuf; merfû — ism-i fâildir."),
  tok("عِنْدَهُمَا","inda","noun",["maful-fih","idafa-definiteness"],
      "ظَرْفٌ مَنْصُوبٌ وَ«هُمَا» مُضَافٌ إِلَيْهِ — يَعْنِي أَبَا يُوسُفَ وَمُحَمَّدًا.",
      "An adverbial in nasb, «their» its mudaf ilayh — Abu Yusuf and Muhammad.",
      "Mensub zarf; «هما» muzâfun ileyh — Ebû Yûsuf ile Muhammed kastedilir.", punct="."),
 ],
 "jumal": [
  J("وَصُلْحُ الْمُرْتَدِّ مَوْقُوفٌ… وَنَافِذٌ عِنْدَهُمَا",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ — وَفِيهَا حِكَايَةُ الْخِلَافِ بَيْنَ الْإِمَامِ وَصَاحِبَيْهِ.",
    "A joined nominal clause — carrying the khilaf between the Imam and his two companions.",
    "Matuf isim cümlesi — İmam ile iki arkadaşı arasındaki ihtilâfı nakleder."),
 ]})

TITLE4 = {"ar": "شُرُوطُ الْمُتَصَالِحَيْنِ",
          "en": "The Conditions of the Two Parties",
          "tr": "Sulh Yapan Tarafların Şartları"}

# ---------------------------------------------------------------- chapter 5 (s24-s28)
S5 = []

S5.append({"id": "s24", "translation": {
 "en": "If sulh over gold falls on less gold of its kind, it is permitted — a taking of part of the right, and a release from its remainder.",
 "tr": "Altın alacağı üzerine, aynı cinsten daha az altına sulh yapılırsa câizdir — hakkın bir kısmını almak, kalanından ibrâ etmektir."},
 "tokens": [
  tok("فَإِنْ","in-shart","part",["in-shartiyya"],
      "الْفَاءُ لِلتَّفْرِيعِ وَ«إِنْ» شَرْطِيَّةٌ.",
      "The fa branches; «if» conditional.",
      "Tefrî' fâsı; «إن» şartiyedir."),
  tok("وَقَعَ","waqaa","verb",["in-shartiyya","fail","mithal-verbs"],
      "فِعْلُ الشَّرْطِ فِي مَحَلِّ جَزْمٍ.",
      "The condition verb in jazm position.",
      "Şart fiili; mahallen meczumdur."),
  tok("الصُّلْحُ","sulh","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ.","The fa'il in raf'.","Merfû fâildir."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("ذَهَبٍ","dhahab","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("أَقَلَّ","aqall","noun",["huruf-jarr","ism-tafdil","mamnu-min-sarf"],
      "مَجْرُورٌ بِالْفَتْحَةِ — مَمْنُوعٌ مِنَ الصَّرْفِ.",
      "In jarr by fatha — a diptote.",
      "Fetha ile mecrur — gayr-ı munsariftir."),
  tok("مِنْهُ","min","part",["huruf-jarr"],
      "«مِنْ» جَارَّةٌ وَالْهَاءُ مَجْرُورٌ — أَيْ مِنْ جِنْسِهِ.",
      "«Than» governs the ha — of its kind.",
      "«من» cer harfi; hâ mecrur — kendi cinsinden demektir."),
  tok("جَازَ","jawaza","verb",["in-shartiyya","fail","hollow-verbs"],
      "جَوَابُ الشَّرْطِ مَاضٍ فِي مَحَلِّ جَزْمٍ.",
      "The condition's answer, past, in jazm position.",
      "Şartın cevabı; mâzî, mahallen meczumdur.", punct="•"),
  tok("أَخْذًا","akhdh","noun",["maful-lah","masdar"],
      "مَفْعُولٌ لِأَجْلِهِ مَنْصُوبٌ — أَوْ مَصْدَرٌ فِي مَوْضِعِ الْحَالِ.",
      "A maf'ul li-ajlih in nasb — or a masdar standing as hal.",
      "Mensub mef'ûlün li-eclih — yahut hâl makamında masdardır."),
  tok("لِبَعْضِ","baad","noun",["huruf-jarr","idafa-definiteness"],
      "اللَّامُ جَارَّةٌ وَ«بَعْضِ» مَجْرُورٌ مُضَافٌ.",
      "The lam governs; «part» in jarr, mudaf.",
      "Lâm cer harfi; «بعض» mecrur ve muzâftır."),
  tok("الْحَقِّ","haqq-sulh","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ.","Mudaf ilayh in jarr.","Mecrur muzâfun ileyhtir."),
  tok("وَإِبْرَاءً","ibra","noun",["atf-nasaq","masdar","form-iv-verbs"],
      "مَعْطُوفٌ عَلَى «أَخْذًا» مَنْصُوبٌ — مَصْدَرُ الْإِفْعَالِ.",
      "Joined to «a taking», in nasb — the Form IV masdar.",
      "«أخذًا»ya matuf; mensub — if'âlin masdarıdır."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("بَاقِيهِ","baqi","noun",["huruf-jarr","idafa-definiteness","ism-maqsur-manqus"],
      "اسْمٌ مَجْرُورٌ بِكَسْرَةٍ مُقَدَّرَةٍ — مَنْقُوصٌ — وَالْهَاءُ مُضَافٌ إِلَيْهِ.",
      "In jarr by an assumed kasra — a manqus noun — the ha its mudaf ilayh.",
      "Takdîrî kesreyle mecrur — menkus — hâ, muzâfun ileyhtir.", punct="."),
 ],
 "jumal": [
  J("فَإِنْ وَقَعَ… جَازَ",
    "جُمْلَةُ شَرْطٍ وَجَوَابُهَا — لَا مَحَلَّ لَهَا.",
    "A condition and its answer — i'rabless.",
    "Şart ve cevabı — mahalsizdir."),
 ]})

S5.append({"id": "s25", "translation": {
 "en": "But if the consideration is more than the debt, it is not permitted — for the excess is riba.",
 "tr": "Fakat bedel alacaktan fazla olursa câiz olmaz — çünkü fazlalık ribâdır."},
 "tokens": [
  tok("وَإِنْ","in-shart","part",["in-shartiyya","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«إِنْ» شَرْطِيَّةٌ.",
      "The waw joins; «if» conditional.",
      "Atıf vâvı; «إن» şartiyedir."),
  tok("كَانَ","kana","verb",["in-shartiyya","kana-wa-akhawatuha"],
      "فِعْلُ الشَّرْطِ — «كَانَ» النَّاقِصَةُ فِي مَحَلِّ جَزْمٍ.",
      "The condition verb — defective kana in jazm position.",
      "Şart fiili — nâkıs «كان»; mahallen meczumdur."),
  tok("الْبَدَلُ","badal-iwad","noun",["kana-wa-akhawatuha"],
      "اسْمُ «كَانَ» مَرْفُوعٌ.","Kana's noun in raf'.","«كان»ın ismi; merfûdur."),
  tok("أَكْثَرَ","akthar","noun",["kana-wa-akhawatuha","ism-tafdil","mamnu-min-sarf"],
      "خَبَرُ «كَانَ» مَنْصُوبٌ — اسْمُ تَفْضِيلٍ.",
      "Kana's khabar in nasb — an ism tafdil.",
      "«كان»ın haberi; mensub — ism-i tafdîldir."),
  tok("مِنَ","min","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("الدَّيْنِ","dayn","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("لَمْ","lam-jazima","part",["lam-jazim"],
      "«لَمْ» حَرْفُ نَفْيٍ وَجَزْمٍ وَقَلْبٍ.",
      "«Lam»: negation, jazm, and past-shifting.",
      "«لم»: nefiy, cezm ve mâzîye çevirme harfidir."),
  tok("يَجُزْ","jawaza","verb",["lam-jazim","hollow-verbs","in-shartiyya"],
      "مُضَارِعٌ مَجْزُومٌ بِلَمْ وَعَلَامَةُ جَزْمِهِ السُّكُونُ — حُذِفَتْ عَيْنُهُ لِالْتِقَاءِ السَّاكِنَيْنِ؛ وَالْجُمْلَةُ جَوَابُ الشَّرْطِ.",
      "A mudari' in jazm after lam, marked by sukun — its hollow waw dropped where two sukuns met; the clause the condition's answer.",
      "«لم» ile meczum muzâri; alâmeti sükûn — iki sâkin buluşunca ecvefin vâvı düşmüştür; cümle, şartın cevabıdır.", punct="•"),
  tok("لِأَنَّ","lianna","part",["inna-wa-akhawatuha","huruf-jarr","lam-taleel"],
      "اللَّامُ لِلتَّعْلِيلِ وَ«أَنَّ» تَنْصِبُ الِاسْمَ وَتَرْفَعُ الْخَبَرَ.",
      "The lam of cause with «anna» — nasb on its noun, raf' on its khabar.",
      "Ta'lîl lâmı ile «أنّ» — ismini nasb, haberini raf eder."),
  tok("الزِّيَادَةَ","ziyada","noun",["inna-wa-akhawatuha"],
      "اسْمُ «أَنَّ» مَنْصُوبٌ.","Anna's noun in nasb.","«أنّ»nin ismi; mensubdur."),
  tok("رِبًا","riba","noun",["inna-wa-akhawatuha","ism-maqsur-manqus"],
      "خَبَرُ «أَنَّ» مَرْفُوعٌ بِضَمَّةٍ مُقَدَّرَةٍ — مَقْصُورٌ.",
      "Anna's khabar in raf' by an assumed damma — maqsur.",
      "«أنّ»nin haberi; takdîrî zamme ile merfû — maksûrdur.", punct="."),
 ],
 "jumal": [
  J("وَإِنْ كَانَ… لَمْ يَجُزْ",
    "جُمْلَةُ شَرْطٍ مَعْطُوفَةٌ؛ جَوَابُهَا الْمَجْزُومُ بِلَمْ.",
    "A joined conditional; its answer the lam-jazm clause.",
    "Matuf şart cümlesi; cevabı «لم» ile meczumdur."),
  J("لِأَنَّ الزِّيَادَةَ رِبًا",
    "الْمَصْدَرُ الْمُؤَوَّلُ مَجْرُورٌ بِاللَّامِ — تَعْلِيلٌ لِلْحُكْمِ.",
    "The derived masdar in jarr after the lam — the ruling's reason.",
    "Müevvel masdar, lâm ile mecrur — hükmün ta'lîlidir."),
 ]})

S5.append({"id": "s26", "translation": {
 "en": "And if the two kinds differ, sulh is permitted — and taking possession in the session is stipulated.",
 "tr": "İki cins farklı olursa sulh câizdir — ve mecliste kabz şart koşulmuştur."},
 "tokens": [
  tok("وَإِنِ","in-shart","part",["in-shartiyya","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«إِنْ» شَرْطِيَّةٌ — كُسِرَتْ نُونُهَا لِالْتِقَاءِ السَّاكِنَيْنِ.",
      "The waw joins; conditional «in» — its nun takes kasra where two sukuns meet.",
      "Atıf vâvı; şart «إن»i — iki sâkin buluştuğu için nûnu kesrelenmiştir."),
  tok("اخْتَلَفَ","ikhtalafa","verb",["in-shartiyya","fail","form-viii-verbs"],
      "فِعْلُ الشَّرْطِ — مَاضِي الِافْتِعَالِ فِي مَحَلِّ جَزْمٍ.",
      "The condition verb — the Form VIII past in jazm position.",
      "Şart fiili — iftiâlin mâzîsi; mahallen meczumdur."),
  tok("الْجِنْسَانِ","jins","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ بِالْأَلِفِ لِأَنَّهُ مُثَنًّى.",
      "The fa'il in raf' by the ALIF, being dual.",
      "Tesniye olduğu için ELİF ile merfû fâildir."),
  tok("جَازَ","jawaza","verb",["in-shartiyya","fail","hollow-verbs"],
      "جَوَابُ الشَّرْطِ فِي مَحَلِّ جَزْمٍ.",
      "The condition's answer in jazm position.",
      "Şartın cevabı; mahallen meczumdur."),
  tok("الصُّلْحُ","sulh","noun",["fail"],
      "فَاعِلٌ مَرْفُوعٌ.","The fa'il in raf'.","Merfû fâildir.", punct="•"),
  tok("وَاشْتُرِطَ","ishtarata","verb",["atf-nasaq","naib-al-fail","form-viii-verbs"],
      "مَعْطُوفٌ — مَاضِي الِافْتِعَالِ مَبْنِيٌّ لِلْمَجْهُولِ.",
      "Joined — the Form VIII past in the passive.",
      "Matuf — iftiâlin meçhul mâzîsidir."),
  tok("الْقَبْضُ","qabd","noun",["naib-al-fail","masdar"],
      "نَائِبُ الْفَاعِلِ مَرْفُوعٌ.",
      "The deputy fa'il in raf'.",
      "Merfû nâib-i fâildir."),
  tok("فِي","fi","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("الْمَجْلِسِ","majlis","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ — مَجْلِسُ الْعَقْدِ.",
      "In jarr — the contract session.",
      "Mecrur isim — akit meclisidir.", punct="."),
 ],
 "jumal": [
  J("وَإِنِ اخْتَلَفَ الْجِنْسَانِ جَازَ الصُّلْحُ",
    "جُمْلَةُ شَرْطٍ مَعْطُوفَةٌ.",
    "A joined conditional clause.",
    "Matuf şart cümlesidir."),
  J("وَاشْتُرِطَ الْقَبْضُ فِي الْمَجْلِسِ",
    "جُمْلَةٌ فِعْلِيَّةٌ مَعْطُوفَةٌ عَلَى الْجَوَابِ.",
    "A verbal clause joined to the answer.",
    "Cevaba matuf fiil cümlesidir."),
 ]})

S5.append({"id": "s27", "translation": {
 "en": "And sulh from a present debt to the same amount deferred is valid: the claimant has dropped his right to promptness.",
 "tr": "Peşin alacaktan, aynı miktarın vadelisine sulh geçerlidir: davacı, peşin alma (ta'cil) hakkını düşürmüştür."},
 "tokens": [
  tok("وَالصُّلْحُ","sulh","noun",["mubtada-khabar","atf-nasaq"],
      "الْوَاوُ عَاطِفَةٌ وَ«الصُّلْحُ» مُبْتَدَأٌ.",
      "The waw joins; «sulh» a mubtada.",
      "Atıf vâvı; «الصلح» mübtedadır."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("دَيْنٍ","dayn","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("حَالٍّ","hall-due","noun",["naat-sifa","ism-fail"],
      "نَعْتٌ مَجْرُورٌ — الْحَالُّ: الْوَاجِبُ أَدَاؤُهُ الْآنَ.",
      "An attribute in jarr — «due now».",
      "Mecrur sıfat — «hâll»: edası hemen gereken demektir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("مِثْلِهِ","mithl","noun",["huruf-jarr","idafa-definiteness"],
      "اسْمٌ مَجْرُورٌ وَالْهَاءُ مُضَافٌ إِلَيْهِ.",
      "In jarr, the ha its mudaf ilayh.",
      "Mecrur isim; hâ, muzâfun ileyhtir."),
  tok("مُؤَجَّلًا","muajjal","noun",["hal","ism-maful"],
      "حَالٌ مَنْصُوبٌ — اسْمُ مَفْعُولٍ.",
      "A hal in nasb — a passive participle.",
      "Mensub hâl — ism-i mef'ûldür."),
  tok("جَائِزٌ","jaiz","noun",["mubtada-khabar","ism-fail"],
      "خَبَرٌ مَرْفُوعٌ.","The khabar in raf'.","Merfû haberdir.", punct="•"),
  tok("لِأَنَّ","lianna","part",["inna-wa-akhawatuha","lam-taleel"],
      "اللَّامُ لِلتَّعْلِيلِ وَ«أَنَّ» نَاصِبَةٌ.",
      "The causal lam with governing «anna».",
      "Ta'lîl lâmı; «أنّ» nâsıbedir."),
  tok("صَاحِبَ","sahib","noun",["inna-wa-akhawatuha","idafa-definiteness"],
      "اسْمُ «أَنَّ» مَنْصُوبٌ وَهُوَ مُضَافٌ.",
      "Anna's noun in nasb, mudaf.",
      "«أنّ»nin ismi; mensub ve muzâftır."),
  tok("الْحَقِّ","haqq-sulh","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ.","Mudaf ilayh in jarr.","Mecrur muzâfun ileyhtir."),
  tok("أَسْقَطَ","asqata","verb",["inna-wa-akhawatuha","fail","form-iv-verbs"],
      "مَاضٍ وَالْفَاعِلُ مُسْتَتِرٌ — وَالْجُمْلَةُ خَبَرُ «أَنَّ».",
      "A past verb, agent hidden — the clause anna's khabar.",
      "Mâzî; fâili gizli — cümle, «أنّ»nin haberidir."),
  tok("حَقَّ","haqq-sulh","noun",["maful-bihi","idafa-definiteness"],
      "مَفْعُولٌ بِهِ مَنْصُوبٌ مُضَافٌ.",
      "The object in nasb, mudaf.",
      "Mensub mef'ûlün bih; muzâftır."),
  tok("التَّعْجِيلِ","tajil-haste","noun",["idafa-definiteness","masdar","form-ii-verbs"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ — مَصْدَرُ التَّفْعِيلِ: طَلَبُ الْأَدَاءِ عَاجِلًا.",
      "Mudaf ilayh in jarr — the Form II masdar: demanding prompt payment.",
      "Mecrur muzâfun ileyh — tef'îl masdarı: peşin ödeme istemektir.", punct="."),
 ],
 "jumal": [
  J("وَالصُّلْحُ… جَائِزٌ",
    "جُمْلَةٌ اسْمِيَّةٌ مَعْطُوفَةٌ.",
    "A joined nominal clause.",
    "Matuf isim cümlesidir."),
  J("لِأَنَّ صَاحِبَ الْحَقِّ أَسْقَطَ…",
    "الْمَصْدَرُ الْمُؤَوَّلُ مَجْرُورٌ بِاللَّامِ — تَعْلِيلٌ.",
    "The derived masdar in jarr after the lam — the reason.",
    "Müevvel masdar lâm ile mecrur — ta'lîldir."),
 ]})

S5.append({"id": "s28", "translation": {
 "en": "And whoever settles from one debt to another deferred debt — it is not permitted, for it is the sale of debt for debt.",
 "tr": "Kim bir alacaktan başka bir vadeli alacağa sulh yaparsa — câiz olmaz; çünkü bu, deynin deynle satışıdır."},
 "tokens": [
  tok("وَمَنْ","man-shart","pron",["in-shartiyya"],
      "الْوَاوُ عَاطِفَةٌ وَ«مَنْ» شَرْطِيَّةٌ مُبْتَدَأٌ — تَجْزِمُ فِعْلَيْنِ.",
      "The waw joins; conditional «whoever», a mubtada — jazm on two verbs.",
      "Atıf vâvı; şart «من»i, mübteda — iki fiili cezmeder."),
  tok("صَالَحَ","salaha","verb",["in-shartiyya","fail","form-iii-verbs"],
      "فِعْلُ الشَّرْطِ فِي مَحَلِّ جَزْمٍ.",
      "The condition verb in jazm position.",
      "Şart fiili; mahallen meczumdur."),
  tok("عَنْ","an-prep","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("دَيْنٍ","dayn","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("عَلَى","ala","part",["huruf-jarr"],
      "حَرْفُ جَرٍّ.","A jarr particle.","Cer harfidir."),
  tok("دَيْنٍ","dayn","noun",["huruf-jarr"],
      "اسْمٌ مَجْرُورٌ.","In jarr.","Mecrur isimdir."),
  tok("آخَرَ","akhar","noun",["naat-sifa","mamnu-min-sarf"],
      "نَعْتٌ مَجْرُورٌ بِالْفَتْحَةِ — مَمْنُوعٌ مِنَ الصَّرْفِ عَلَى وَزْنِ أَفْعَل.",
      "An attribute in jarr by fatha — a diptote on af'al.",
      "Fetha ile mecrur sıfat — أفعل vezninde gayr-ı munsariftir."),
  tok("مُؤَجَّلٍ","muajjal","noun",["naat-sifa","ism-maful"],
      "نَعْتٌ ثَانٍ مَجْرُورٌ.",
      "A second attribute in jarr.",
      "İkinci sıfat; mecrurdur."),
  tok("لَمْ","lam-jazima","part",["lam-jazim"],
      "حَرْفُ نَفْيٍ وَجَزْمٍ.","Negation and jazm.","Nefiy ve cezm harfidir."),
  tok("يَجُزْ","jawaza","verb",["lam-jazim","hollow-verbs","in-shartiyya"],
      "مَجْزُومٌ بِلَمْ — وَالْجُمْلَةُ جَوَابُ الشَّرْطِ.",
      "In jazm after lam — the clause the condition's answer.",
      "«لم» ile meczum — cümle, şartın cevabıdır.", punct="•"),
  tok("لِأَنَّهُ","lianna","part",["inna-wa-akhawatuha","lam-taleel"],
      "اللَّامُ لِلتَّعْلِيلِ وَ«أَنَّ» نَاصِبَةٌ وَالْهَاءُ اسْمُهَا.",
      "The causal lam; «anna» governs, the ha its noun.",
      "Ta'lîl lâmı; «أنّ» nâsıbe, hâ zamiri ismidir."),
  tok("بَيْعُ","bay","noun",["inna-wa-akhawatuha","idafa-definiteness"],
      "خَبَرُ «أَنَّ» مَرْفُوعٌ وَهُوَ مُضَافٌ.",
      "Anna's khabar in raf', mudaf.",
      "«أنّ»nin haberi; merfû ve muzâftır."),
  tok("الدَّيْنِ","dayn","noun",["idafa-definiteness"],
      "مُضَافٌ إِلَيْهِ مَجْرُورٌ.","Mudaf ilayh in jarr.","Mecrur muzâfun ileyhtir."),
  tok("بِالدَّيْنِ","dayn","noun",["huruf-jarr"],
      "الْبَاءُ لِلْمُقَابَلَةِ وَ«الدَّيْنِ» مَجْرُورٌ.",
      "The ba of exchange; «the debt» in jarr.",
      "Mukabele bildiren بِ; «الدين» mecrurdur.", punct="."),
 ],
 "jumal": [
  J("وَمَنْ صَالَحَ… لَمْ يَجُزْ",
    "جُمْلَةُ شَرْطٍ — وَجُمْلَتَا الشَّرْطِ وَالْجَوَابِ خَبَرُ «مَنْ».",
    "A conditional — condition and answer together the khabar of «whoever».",
    "Şart cümlesi — şart ve cevap birlikte «من»in haberidir."),
 ]})

TITLE5 = {"ar": "أَحْكَامُ الْبَدَلِ وَالرِّبَا",
          "en": "The Consideration and Riba",
          "tr": "Bedel Hükümleri ve Ribâ"}

MANIFEST = {
 "id": "kitab-al-sulh",
 "storyGroup": "kitab-al-sulh",
 "title": {"ar": "كِتَابُ الصُّلْحِ",
           "en": "The Book of Sulh",
           "tr": "Sulh Bahsi"},
 "subtitle": {"ar": "الصُّلْحُ: تَعْرِيفُهُ وَأَنْوَاعُهُ وَأَحْكَامُهُ، بِعَرَبِيَّةٍ مُيَسَّرَةٍ",
              "en": "Settlement in fiqh — definition, kinds and rulings, in graded original Arabic",
              "tr": "Fıkıhta sulh — tarifi, nevileri ve hükümleri, kolaylaştırılmış Arapçayla"},
 "level": 5,
 "levelName": "Advanced",
 "version": "0.5.0",
 "published": "2026-07-31",
 "access": "premium",
 "chapters": [{"n": 1, "title": TITLE1}, {"n": 2, "title": TITLE2}, {"n": 3, "title": TITLE3}, {"n": 4, "title": TITLE4}, {"n": 5, "title": TITLE5}],
 "siblings": [],
 "attribution": {
  "ar": "عَرَبِيَّةٌ أَصْلِيَّةٌ مُيَسَّرَةٌ صِيغَتْ تَحْرِيرِيًّا مِنْ مَرْجِعٍ فِقْهِيٍّ تُرْكِيٍّ رَفَعَهُ صَاحِبُ الْمَشْرُوعِ.",
  "en": ("ORIGINAL graded Arabic, composed editorially from the project owner's uploaded Turkish fiqh "
         "reference on sulh (research/sources/sulh-fiqh-turkce.txt; Hanafi-centered, with classical "
         "citations). The Qur'anic clause (al-Nisa 4:128) and the hadith wording (Tirmidhi, Ahkam 17) "
         "are received text quoted as transmitted; all other Arabic is editorial composition in the "
         "Hidaya register and must not be cited as a classical text. Chapters 1-5 cover the definition, "
         "evidences, kinds, the six contract-guises and the bedel's conditions; further chapters follow release by release."),
  "tr": ("ÖZGÜN kolaylaştırılmış Arapça; proje sahibinin yüklediği Türkçe sulh maddesinden "
         "(research/sources/sulh-fiqh-turkce.txt) editoryal olarak telif edilmiştir. Âyet iktibası "
         "(en-Nisâ 4/128) ve hadis lafzı (Tirmizî, Ahkâm 17) nakledilen metindir; diğer bütün Arapça, "
         "Hidâye üslûbunda editoryal telif olup klasik metin diye iktibas edilemez. 1-5. bölümler tarif, "
         "deliller, neviler, altı akit kisvesi ve bedelin şartlarını kapsar; sonraki bölümler sürüm sürüm gelecektir."),
  "reviewStatus": "pending-scholarly-review"
 }
}

def copy_verbs():
    out = {}
    for lex, src in (("qala", "aqaid-ahl-al-sunna"),
                     ("taala", "wasiyyat-abi-hanifa-samti"),
                     ("laysa", "wasiyyat-abi-hanifa-samti"),
                     ("kana", "wasiyyat-abi-hanifa-samti")):
        verbs = json.loads((ROOT / "content/samples" / src / "morphology.json")
                           .read_text(encoding="utf-8"))["verbs"]
        out[lex] = verbs[lex]
    return out

MORPH = {"verbs": copy_verbs()}
MORPH["verbs"]["rafaa"] = _sg.sound1(
    "fataha", "رَفَع", "رْفَع", "اِرْفَع", "رَفْع", "رَافِع",
    "مَرْفُوع", "رُفِعَ", "يُرْفَعُ")
MORPH["verbs"]["harrama"] = _sg.derived(
    _sg.B2, _sg.W2, "ُ", "حَرَّم", "حَرِّم", "حَرِّم", "تَحْرِيم",
    "مُحَرِّم", "مُحَرَّم", "حُرِّمَ", "يُحَرَّمُ")
MORPH["verbs"]["raggaba"] = _sg.derived(
    _sg.B2, _sg.W2, "ُ", "رَغَّب", "رَغِّب", "رَغِّب", "تَرْغِيب",
    "مُرَغِّب", "مُرَغَّب", "رُغِّبَ", "يُرَغَّبُ")
# أَحَلَّ — Form IV geminate, assembled like the corpus's اِسْتَعَدَّ:
# contracted stem before vowels, broken stem before consonants.
MORPH["verbs"]["ahalla"] = _sg.entry(
    "بَابُ الْإِفْعَالِ: أَفْعَلَ يُفْعِلُ — مُضَاعَفٌ", _sg.W4,
    "إِحْلَال", "مُحِلّ",
    _sg.mazi14("أَحَلّ", "أَحْلَل"),
    _sg.mudari14("ُ", "حِلّ", "حْلِل"),
    ["أَحِلَّ", "أَحِلَّا", "أَحِلُّوا", "أَحِلِّي", "أَحِلَّا", "أَحْلِلْنَ"],
    "يُحِلَّ", "يُحِلَّ", "تُحِلَّ",
    "مُحَلّ", "أُحِلَّ", "يُحَلُّ",
    "مُضَاعَفٌ مِنَ الْإِفْعَالِ: الْجَزْمُ بِالْفَتْحِ — لَمْ يُحِلَّ، وَيَجُوزُ لَمْ يُحْلِلْ.")
# chapter 2's verbs: وَقَعَ rides the mithal shapes (waw drops in the mudari),
# جَازَ the hollow engine, صَالَحَ and أَسْقَطَ the derived engines.
MORPH["verbs"]["waqaa"] = _sg.sound1(
    "fataha", "وَقَع", "قَع", "قَع", "وُقُوع", "وَاقِع",
    note="مِثَالٌ وَاوِيٌّ: تَسْقُطُ الْوَاوُ فِي الْمُضَارِعِ وَالْأَمْرِ — يَقَعُ، قَعْ.")
MORPH["verbs"]["jawaza"] = _sg.hollow1(
    "nasara", "أَجْوَفُ وَاوِيٌّ", "جَاز", "جُز", "جُوز", "جُز",
    "جُوز", "جُز", "جَوَاز", "جَائِز",
    note=_sg.HOLLOW_NOTE.format(ex="جُزْتَ"))
MORPH["verbs"]["salaha"] = _sg.derived(
    _sg.B3, _sg.W3, "ُ", "صَالَح", "صَالِح", "صَالِح", "مُصَالَحَة",
    "مُصَالِح", "مُصَالَح", "صُولِحَ", "يُصَالَحُ")
MORPH["verbs"]["asqata"] = _sg.derived(
    _sg.B4, _sg.W4, "ُ", "أَسْقَط", "سْقِط", "أَسْقِط", "إِسْقَاط",
    "مُسْقِط", "مُسْقَط", "أُسْقِطَ", "يُسْقَطُ")

# chapter 4's verbs. ishtarata rides the sound VIII engine, mayyaza the
# sound II engine; salaha (III) and the copied kana/laysa already serve.
MORPH["verbs"]["ishtarata"] = _sg.derived(
    _sg.B8, _sg.W8, "َ", "اِشْتَرَط", "شْتَرِط", "اِشْتَرِط",
    "اِشْتِرَاط", "مُشْتَرِط", "مُشْتَرَط", "اُشْتُرِطَ", "يُشْتَرَطُ")
MORPH["verbs"]["ikhtalafa"] = _sg.derived(
    _sg.B8, _sg.W8, "َ", "اِخْتَلَف", "خْتَلِف", "اِخْتَلِف",
    "اِخْتِلَاف", "مُخْتَلِف", "مُخْتَلَف", "اُخْتُلِفَ", "يُخْتَلَفُ")
MORPH["verbs"]["mayyaza"] = _sg.derived(
    _sg.B2, _sg.W2, "ُ", "مَيَّز", "مَيِّز", "مَيِّز",
    "تَمْيِيز", "مُمَيِّز", "مُمَيَّز", "مُيِّزَ", "يُمَيَّزُ")

ALL = S + S2 + S3 + S4 + S5

(PKG / "manifest.json").write_text(json.dumps(MANIFEST, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "chapters/1.json").write_text(json.dumps({"chapter": 1, "sentences": S}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "chapters/2.json").write_text(json.dumps({"chapter": 2, "sentences": S2}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "chapters/3.json").write_text(json.dumps({"chapter": 3, "sentences": S3}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "chapters/4.json").write_text(json.dumps({"chapter": 4, "sentences": S4}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "chapters/5.json").write_text(json.dumps({"chapter": 5, "sentences": S5}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "glossary.json").write_text(json.dumps({"entries": GLOSS}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "morphology.json").write_text(json.dumps(MORPH, ensure_ascii=False, indent=1), encoding="utf-8")

used = {t["lex"] for s in ALL for t in s["tokens"]}
dead = set(GLOSS) - used
missing = used - set(GLOSS)
print("tokens:", sum(len(s["tokens"]) for s in ALL), "gloss:", len(GLOSS),
      "jumal:", sum(len(s.get("jumal", [])) for s in ALL),
      "dead:", sorted(dead), "missing:", sorted(missing))
