# -*- coding: utf-8 -*-
"""Qiṣaṣ al-Nabiyyīn, Part Four — chapter 3: «أَبٌ رَحِيمٌ وَمُعَلِّمٌ حَكِيمٌ» — sections 5–7 of the story of Shuʿayb (print pp. 4–7):
the appeal in a second voice (7:85–86), the people's mocking answer (11:87), and Shuʿayb's explanation of his call (11:88).
The vowelling is the print's; the sentences are the print's clauses. python3 tools/authoring/author_qisas4_ch3.py"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from qisas4_common import *
import qisas4_common as _qc
import sarf_gen as _sg
PKG = _qc.PKG
TITLE = {"ar": "أَبٌ رَحِيمٌ وَمُعَلِّمٌ حَكِيمٌ", "en": "A tender father and a wise teacher", "tr": "Şefkatli bir baba ve hikmetli bir öğretmen"}
S = []; sen = sen_of(S)
TG = json.loads((PKG / "glossary.json").read_text(encoding="utf-8"))["entries"]
HJ = "huruf-jarr"; ID = "idafa-definiteness"; AT = "atf-nasaq"; NA = "naat-sifa"; MK = "mubtada-khabar"; MB = "maful-bihi"; FL = "fail"; IW = "inna-wa-akhawatuha"; IQ = "al-iqtibas-wal-tadmin"; KN = "kana-wa-akhawatuha"; MW = "ism-mawsul"; AK = "afal-khamsa"; MF = "maful-fih"; NF = "naib-al-fail"; SH = "in-shartiyya"

def majrur(full, lex, en, tr, punct=None, tags=(), ar="مَجْرُورٌ بِالْكَسْرَةِ."): return tok(full, lex, "noun", [HJ] + list(tags), ar, en, tr, punct=punct)
def atf_majrur(full, lex, en, tr, punct=None, tags=(), ar="مَعْطُوفٌ مَجْرُورٌ بِالْكَسْرَةِ."):
    return tok(full, lex, "noun", [AT] + list(tags), "الْوَاوُ عَاطِفَةٌ، وَالِاسْمُ " + ar, en, tr, punct=punct, segments=wa_(full[2:], lex, "noun"))
def mudaf_ilayh(full, lex, en, tr, punct=None, tags=(), ar="مُضَافٌ إِلَيْهِ مَجْرُورٌ بِالْكَسْرَةِ."): return tok(full, lex, "noun", [ID] + list(tags), ar, en, tr, punct=punct)
def naat(full, lex, en, tr, punct=None, tags=(), case="jarr"):
    C = {"jarr": "نَعْتٌ مَجْرُورٌ بِالْكَسْرَةِ.", "raf": "نَعْتٌ مَرْفُوعٌ بِالضَّمَّةِ.", "nasb": "نَعْتٌ مَنْصُوبٌ بِالْفَتْحَةِ."}[case]
    return tok(full, lex, "noun", [NA] + list(tags), C, en + " — the naʿt.", tr + " — sıfat.", punct=punct)
def prep_pron(full, lex, pron_form, pron_lex, en, tr, punct=None, tags=(), extra_ar=""):
    pre = full[:len(full) - len(pron_form)]
    return tok(full, lex, "prep", [HJ] + list(tags), "حَرْفُ جَرٍّ، وَالضَّمِيرُ فِي مَحَلِّ جَرٍّ" + extra_ar + ".", en, tr, punct=punct, segments=[seg(pre, lex, "prep"), seg(pron_form, pron_lex, "pron")])
def maful_(full, lex, en, tr, punct=None, tags=(), ar="مَفْعُولٌ بِهِ مَنْصُوبٌ بِالْفَتْحَةِ."): return tok(full, lex, "noun", [MB] + list(tags), ar, en, tr, punct=punct)
def atf_mansub(full, lex, en, tr, punct=None, tags=()): return tok(full, lex, "noun", [AT] + list(tags), "الْوَاوُ عَاطِفَةٌ، وَالِاسْمُ مَعْطُوفٌ مَنْصُوبٌ بِالْفَتْحَةِ.", en, tr, punct=punct, segments=wa_(full[2:], lex, "noun"))
def wa_mudari(full, lex, en, tr, tags=(), punct=None, hidden="هُوَ", obj=None, obj_lex="pron-3mp", extra=""):
    base = full[2:]
    segs = [seg("وَ", "wa", "conj")] + ([seg(base, lex, "verb")] if not obj else [seg(base[:-len(obj)], lex, "verb"), seg(obj, obj_lex, "pron")])
    return tok(full, lex, "verb", [AT, "mudari-marfu"] + list(tags) + ([MB] if obj else []), f"الْوَاوُ عَاطِفَةٌ، وَالْفِعْلُ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: {hidden}" + ("، وَالضَّمِيرُ مَفْعُولٌ بِهِ" if obj else "") + extra + ".", "«and» + " + en, "«ve» + " + tr, punct=punct, segments=segs)
def amr_pl(full, lex, en, tr, tags=(), punct=None, wa=False, fa=False, obj=None):
    pre = "وَ" if wa else ("فَ" if fa else "")
    base = full[len(pre):]
    segs = ([seg(pre, "wa" if wa else "fa", "conj")] if pre else []) + ([seg(base, lex, "verb")] if not obj else [seg(base[:-len(obj)], lex, "verb"), seg(obj, "pron-3fs", "pron")])
    return tok(full, lex, "verb", ["imperative-amr"] + list(tags) + ([AT] if pre else []) + ([MB] if obj else []), ("الْوَاوُ عَاطِفَةٌ، وَ" if wa else "الْفَاءُ عَاطِفَةٌ، وَ" if fa else "") + "فِعْلُ أَمْرٍ مَبْنِيٌّ عَلَى حَذْفِ النُّونِ، وَالْوَاوُ فَاعِلٌ" + ("، وَالضَّمِيرُ مَفْعُولٌ بِهِ" if obj else "") + ".", en + " — the command, built on the nūn's dropping.", tr + " — nûnun hazfi üzere mebnî emir.", punct=punct, segments=segs if (pre or obj) else None)
def la_nahiya_verb(full, lex, en, tr, punct=None, wa=True, tags=()):
    base = full.split()[-1] if " " in full else (full[2:] if wa else full)   # (wave 32) the verb after «وَلَا » — the lā is its own token
    return [tok(("وَلَا" if wa else "لَا"), "la-nahiya", "part", ["la-nahiya"] + ([AT] if wa else []), W(wa) + "لَا نَاهِيَةٌ جَازِمَةٌ.", Wen(wa) + "«do not» — the prohibiting lā.", Wtr(wa) + "«-mayın» — nehiy lâ'sı.", segments=(wa_("لَا", "la-nahiya", "part") if wa else None)),
            tok(base, lex, "verb", ["la-nahiya", AK] + list(tags), "فِعْلٌ مُضَارِعٌ مَجْزُومٌ بِلَا، وَعَلَامَةُ جَزْمِهِ حَذْفُ النُّونِ، وَالْوَاوُ فَاعِلٌ.", en + " — majzūm by lā: the nūn dropped.", tr + " — lâ ile meczûm: nûn düşmüş.", punct=punct)]
def ya_qawmi(wa=False):
    return [tok("وَيَا" if wa else "يَا", "ya-nida", "part", ["vocative-munada"] + ([AT] if wa else []), W(wa) + "حَرْفُ نِدَاءٍ.", Wen(wa) + "«O»", Wtr(wa) + "«ey»", segments=(wa_("يَا", "ya-nida", "part") if wa else None)),
            tok("قَوْمِ", "qawm", "noun", ["vocative-munada", ID, "ya-al-mutakallim"], "مُنَادًى مَنْصُوبٌ بِفَتْحَةٍ مُقَدَّرَةٍ، مُضَافٌ إِلَى يَاءِ الْمُتَكَلِّمِ الْمَحْذُوفَةِ، وَالْكَسْرَةُ دَلِيلٌ عَلَيْهَا.", "«my people» — the munādā, annexed to the dropped yāʾ of the speaker.", "«kavmim» — münâdâ, hazfedilmiş mütekellim yâsına muzâf.")]
def annahu(full="وَأَنَّهُ", wa=True, pre_ar="الْوَاوُ عَاطِفَةٌ، وَ", en="«and that he»", tr="«ve onun»", extra=()):
    return tok(full, "anna", "part", [IW] + ([AT] if wa else []) + list(extra), pre_ar + "أَنَّ حَرْفٌ مُشَبَّهٌ بِالْفِعْلِ، وَالْهَاءُ اسْمُهَا فِي مَحَلِّ نَصْبٍ.", en + " — anna with its ism.", tr + " — enne ve ismi.", segments=([seg("وَ", "wa", "conj")] if wa else []) + [seg("أَنَّ", "anna", "part"), pr3ms()])

# ---------------------------------------------------------------- §5
sen("s1", "And he varies his address to them and tries every kind of counsel, as a tender father and a wise teacher do; so he says:", "Onlara hitabını çeşitlendirir, nasihatte türlü yollar dener — şefkatli bir babanın ve hikmetli bir öğretmenin yaptığı gibi; der ki:", [
  tok("وَيَتَنَوَّعُ", "tanawwaa", "verb", [AT, "mudari-marfu", "form-v-verbs"], "الْوَاوُ لِلِاسْتِئْنَافِ، وَيَتَنَوَّعُ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: هُوَ.", "«and he varies»", "«ve çeşitlendirir»", segments=wa_("يَتَنَوَّعُ", "tanawwaa", "verb")),
  prep_pron("لَهُمْ", "li", "هُمْ", "pron-3mp", "«to them»", "«onlara»"),
  fi(), majrur("الْخِطَابِ", "khitab", "«address»", "«hitapta»", punct="،"),
  wa_mudari("وَيَتَفَنَّنُ", "tafannana", "«tries every art»", "«türlü yollar dener»", tags=["form-v-verbs"]),
  fi(), majrur("النَّصِيحَةِ", "nasiha", "«counsel»", "«nasihatte»", punct="،"),
  tok("شَأْنَ", "shan", "noun", ["maful-mutlaq", ID], "مَفْعُولٌ مُطْلَقٌ نَائِبٌ عَنِ الْمَصْدَرِ مَنْصُوبٌ، مُضَافٌ.", "«as … do» — the absolute object's deputy.", "«… gibi» — masdarın yerine mef'ûl-i mutlak."),
  mudaf_ilayh("الْأَبِ", "ab", "«the father»", "«babanın»"), naat("الرَّحِيمِ", "rahim-merciful", "«tender»", "«şefkatli»"),
  atf_majrur("وَالْمُعَلِّمِ", "muallim", "«and the teacher»", "«ve öğretmenin»", tags=["ism-fail", "form-ii-verbs"]), naat("الْحَكِيمِ", "hakim", "«wise»", "«hikmetli»", punct="،"),
  tok("فَيَقُولُ", "qala", "verb", [AT, "hollow-verbs", "mudari-marfu", MB], "الْفَاءُ عَاطِفَةٌ، وَيَقُولُ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: هُوَ — وَمَقُولُ الْقَوْلِ مَفْعُولُهُ.", "«so he says»", "«der ki»", punct=":", segments=[seg("فَ", "fa", "conj"), seg("يَقُولُ", "qala", "verb")]),
])
sen("s2", "«O my people, worship God; you have no god but Him. A clear proof has come to you from your Lord, so give full measure and weight, and do not deprive people of their things, and do not spread corruption in the land after it has been set right; that is better for you, if you are believers» (7:85).",
        "«Ey kavmim, Allah'a kulluk edin; sizin O'ndan başka ilâhınız yoktur. Size Rabbinizden açık bir delil geldi; ölçüyü ve tartıyı tam yapın, insanların eşyasını eksiltmeyin ve ıslahından sonra yeryüzünde bozgunculuk yapmayın; eğer mü'minlerseniz bu sizin için daha hayırlıdır» (7:85).", quran([
  *ya_qawmi(), amr_pl("اعْبُدُوا", "abada", "«worship»", "«kulluk edin»", tags=[MB]),
  tok("اللهَ", "allah", "propn", [MB], "لَفْظُ الْجَلَالَةِ مَفْعُولٌ بِهِ مَنْصُوبٌ.", "«God» — the object.", "«Allah'a» — mef'ûl."),
  tok("مَا", "ma-nafiya", "part", ["anwa-ma", MK], "حَرْفُ نَفْيٍ.", "«not»", "«yoktur»"),
  prep_pron("لَكُمْ", "li", "كُمْ", "pron-2mp", "«for you» — the fronted khabar.", "«sizin» — mukaddem haber.", tags=[MK]),
  tok("مِنْ", "min", "prep", [HJ, "huruf-jarr-nawadir"], "حَرْفُ جَرٍّ زَائِدٌ لِتَأْكِيدِ النَّفْيِ.", "«any» — the added min.", "«hiç» — zâid min."),
  tok("إِلٰهٍ", "ilah", "noun", [MK, HJ], "مُبْتَدَأٌ مُؤَخَّرٌ مَجْرُورٌ لَفْظًا بِمِنْ الزَّائِدَةِ، مَرْفُوعٌ مَحَلًّا.", "«god» — the delayed mubtada, jarr on the surface, rafʿ by place.", "«ilâh» — muahhar mübtedâ; lafzan mecrûr, mahallen merfû."),
  tok("غَيْرُهُ", "ghayr", "noun", [NA, ID], "نَعْتٌ لِإِلٰهٍ عَلَى الْمَحَلِّ مَرْفُوعٌ، مُضَافٌ، وَالْهَاءُ مُضَافٌ إِلَيْهِ.", "«but Him» — the naʿt on the place.", "«O'ndan başka» — mahallen sıfat.", segments=[seg("غَيْرُ", "ghayr", "noun"), pr3ms()]),
  tok("قَدْ", "qad", "part", ["qad-harf"], "حَرْفُ تَحْقِيقٍ.", "«indeed»", "«gerçekten»"),
  tok("جَاءَتْكُمْ", "jaa", "verb", [MB, "hollow-verbs"], "فِعْلٌ مَاضٍ، وَالتَّاءُ لِلتَّأْنِيثِ، وَكُمْ مَفْعُولٌ بِهِ.", "«has come to you» — the kum its object.", "«size geldi» — küm mef'ûl.", segments=[seg("جَاءَتْ", "jaa", "verb"), pr2mp()]),
  tok("بَيِّنَةٌ", "bayyina", "noun", [FL], "فَاعِلٌ مَرْفُوعٌ بِالضَّمَّةِ.", "«a clear proof» — the doer.", "«açık bir delil» — fâil."),
  tok("مِنْ", "min", "prep", [HJ, NA], "حَرْفُ جَرٍّ — صِفَةٌ لِبَيِّنَةٍ.", "«from»", "«-den»"),
  tok("رَبِّكُمْ", "rabb", "noun", [HJ, ID], "مَجْرُورٌ بِمِنْ، مُضَافٌ، وَكُمْ مُضَافٌ إِلَيْهِ.", "«your Lord»", "«Rabbinizden»", segments=[seg("رَبِّ", "rabb", "noun"), pr2mp()]),
  amr_pl("فَأَوْفُوا", "awfa", "«so give full»", "«tam yapın»", fa=True, tags=["form-iv-verbs", "naqis-verbs", MB]),
  maful_("الْكَيْلَ", "kayl", "«the measure»", "«ölçüyü»"), atf_mansub("وَالْمِيزَانَ", "mizan", "«and the weight»", "«ve tartıyı»"),
  *la_nahiya_verb("وَلَا تَبْخَسُوا", "bakhasa", "«do not deprive»", "«eksiltmeyin»"),
  maful_("النَّاسَ", "nas", "«people»", "«insanları»"),
  tok("أَشْيَاءَهُمْ", "shay", "noun", ["mafulayn", ID, "jam-taksir", "mamnu-min-sarf"], "مَفْعُولٌ ثَانٍ مَنْصُوبٌ، مُضَافٌ، وَهُمْ مُضَافٌ إِلَيْهِ.", "«their things» — the second object.", "«eşyalarını» — ikinci mef'ûl.", segments=[seg("أَشْيَاءَ", "shay", "noun"), pr3mp()]),
  *la_nahiya_verb("وَلَا تُفْسِدُوا", "afsada", "«do not spread corruption»", "«bozgunculuk yapmayın»", tags=["form-iv-verbs"]),
  fi(), majrur("الْأَرْضِ", "ard", "«the land»", "«yeryüzünde»"),
  tok("بَعْدَ", "bada", "noun", [MF, ID], "ظَرْفُ زَمَانٍ مَنْصُوبٌ، مُضَافٌ.", "«after»", "«sonra»"),
  tok("إِصْلَاحِهَا", "islah", "noun", [ID, "masdar", "form-iv-verbs"], "مُضَافٌ إِلَيْهِ مَجْرُورٌ، مُضَافٌ، وَهَا مُضَافٌ إِلَيْهِ — الْمَصْدَرُ مُضَافٌ إِلَى مَفْعُولِهِ.", "«its being set right» — the masdar annexed to its object.", "«ıslahından» — mef'ûlüne muzâf masdar.", segments=[seg("إِصْلَاحِ", "islah", "noun"), pr3fs_()]),
  tok("ذٰلِكُمْ", "dhalikum", "pron", ["asma-al-ishara", MK], "اسْمُ إِشَارَةٍ فِي مَحَلِّ رَفْعٍ مُبْتَدَأٌ — الْكَافُ لِلْخِطَابِ، وَالْمِيمُ لِلْجَمْعِ.", "«that» — the mubtada; the kāf addresses, the mīm makes it plural.", "«bu» — mübtedâ; kâf hitap, mîm cemi."),
  tok("خَيْرٌ", "khayr", "noun", [MK, "ism-tafdil"], "خَبَرٌ مَرْفُوعٌ.", "«better» — the khabar.", "«daha hayırlı» — haber."),
  prep_pron("لَكُمْ", "li", "كُمْ", "pron-2mp", "«for you»", "«sizin için»"),
  tok("إِنْ", "in-shartiyya", "part", [SH], "حَرْفُ شَرْطٍ جَازِمٌ، جَوَابُهُ مَحْذُوفٌ دَلَّ عَلَيْهِ مَا قَبْلَهُ.", "«if»", "«eğer»"),
  tok("كُنْتُمْ", "kana", "verb", [SH, KN, "hollow-verbs"], "فِعْلٌ مَاضٍ نَاقِصٌ فِي مَحَلِّ جَزْمٍ، وَالتَّاءُ اسْمُهُ.", "«you are»", "«iseniz»", segments=[seg("كُنْ", "kana", "verb"), seg("تُمْ", "pron-2mp", "pron")]),
  tok("مُؤْمِنِينَ", "mumin", "noun", [KN, "jam-mudhakkar-salim", "ism-fail"], "خَبَرُ كَانَ مَنْصُوبٌ بِالْيَاءِ.", "«believers» — kāna's khabar.", "«mü'minler» — kâne'nin haberi.", punct="."),
]))
sen("s3", "«And do not sit on every road, threatening and turning away from God's path those who believe in Him, seeking to make it crooked; and remember when you were few and He made you many, and see how the end of the corrupters was» (7:86).",
        "«Her yola oturup tehdit ederek Allah'a iman edenleri O'nun yolundan çevirmeyin ve o yolu eğri göstermeyin; hatırlayın, siz az idiniz de O sizi çoğalttı; bozguncuların sonunun nasıl olduğuna bakın» (7:86).", quran([
  *la_nahiya_verb("وَلَا تَقْعُدُوا", "qaada", "«do not sit»", "«oturmayın»", wa=True),
  tok("بِكُلِّ", "kull", "noun", [HJ, ID], "الْبَاءُ حَرْفُ جَرٍّ، وَكُلِّ مَجْرُورٌ، مُضَافٌ.", "«on every»", "«her»", segments=[seg("بِ", "bi", "prep"), seg("كُلِّ", "kull", "noun")]),
  mudaf_ilayh("صِرَاطٍ", "sirat", "«road»", "«yola»"),
  tok("تُوعِدُونَ", "awada", "verb", ["hal", AK, "form-iv-verbs", "mithal-verbs"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ بِثُبُوتِ النُّونِ، وَالْوَاوُ فَاعِلٌ — وَالْجُمْلَةُ حَالٌ.", "«threatening» — a ḥāl clause.", "«tehdit ederek» — hâl cümlesi."),
  tok("وَتَصُدُّونَ", "sadda", "verb", [AT, AK, "doubled-verbs", MB], "الْوَاوُ عَاطِفَةٌ، وَتَصُدُّونَ مُضَارِعٌ مَرْفُوعٌ بِثُبُوتِ النُّونِ، وَالْوَاوُ فَاعِلٌ.", "«and turning away»", "«ve çeviriyorsunuz»", segments=wa_("تَصُدُّونَ", "sadda", "verb")),
  tok("عَنْ", "an", "prep", [HJ], "حَرْفُ جَرٍّ.", "«from»", "«-den»"), majrur("سَبِيلِ", "sabil", "«the path of»", "«yolundan»", tags=[ID], ar="مَجْرُورٌ بِعَنْ، مُضَافٌ."),
  tok("اللهِ", "allah", "propn", [ID], "لَفْظُ الْجَلَالَةِ مُضَافٌ إِلَيْهِ مَجْرُورٌ.", "«God»", "«Allah'ın»"),
  tok("مَنْ", "man-mawsula", "pron", [MW, MB], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ نَصْبٍ مَفْعُولٌ بِهِ لِتَصُدُّونَ.", "«those who» — the object of «turning away».", "«… kimseleri» — «çeviriyorsunuz»un mef'ûlü."),
  tok("آمَنَ", "aamana", "verb", [MW, "form-iv-verbs"], "فِعْلٌ مَاضٍ، وَالْفَاعِلُ مُسْتَتِرٌ — صِلَةٌ.", "«believe» — the ṣila.", "«iman eden» — sıla."),
  prep_pron("بِهِ", "bi", "هِ", "pron-3ms", "«in Him»", "«O'na»"),
  tok("وَتَبْغُونَهَا", "bagha", "verb", [AT, AK, MB, "naqis-verbs"], "الْوَاوُ عَاطِفَةٌ، وَتَبْغُونَ مُضَارِعٌ مَرْفُوعٌ بِثُبُوتِ النُّونِ، وَالْوَاوُ فَاعِلٌ، وَهَا مَفْعُولٌ بِهِ — السَّبِيلُ.", "«and seeking it» — the hā is the path.", "«ve onu arıyorsunuz» — hâ yol.", segments=[seg("وَ", "wa", "conj"), seg("تَبْغُونَ", "bagha", "verb"), pr3fs_()]),
  tok("عِوَجًا", "iwaj", "noun", ["hal", "masdar"], "حَالٌ مَنْصُوبٌ — أَيْ: مُعْوَجَّةً، أَوْ مَفْعُولٌ ثَانٍ.", "«crooked» — the ḥāl.", "«eğri» — hâl."),
  amr_pl("وَاذْكُرُوا", "dhakara", "«and remember»", "«ve hatırlayın»", wa=True),
  tok("إِذْ", "idh", "noun", [MF, MB], "ظَرْفٌ لِمَا مَضَى مِنَ الزَّمَانِ فِي مَحَلِّ نَصْبٍ مَفْعُولٌ بِهِ — أَيِ: اذْكُرُوا وَقْتَ كَوْنِكُمْ قَلِيلًا.", "«when» — the ẓarf of the past, here the object.", "«… zamanı» — mâzî zarfı, burada mef'ûl."),
  tok("كُنْتُمْ", "kana", "verb", [KN, "hollow-verbs"], "فِعْلٌ مَاضٍ نَاقِصٌ، وَالتَّاءُ اسْمُهُ.", "«you were»", "«idiniz»", segments=[seg("كُنْ", "kana", "verb"), seg("تُمْ", "pron-2mp", "pron")]),
  tok("قَلِيلًا", "qalil", "noun", [KN], "خَبَرُ كَانَ مَنْصُوبٌ بِالْفَتْحَةِ.", "«few» — kāna's khabar.", "«az» — kâne'nin haberi."),
  tok("فَكَثَّرَكُمْ", "kaththara", "verb", [AT, MB, "form-ii-verbs"], "الْفَاءُ عَاطِفَةٌ، وَكَثَّرَ فِعْلٌ مَاضٍ، وَالْفَاعِلُ مُسْتَتِرٌ: هُوَ، وَكُمْ مَفْعُولٌ بِهِ.", "«and He made you many»", "«de sizi çoğalttı»", segments=[seg("فَ", "fa", "conj"), seg("كَثَّرَ", "kaththara", "verb"), pr2mp()]),
  amr_pl("وَانْظُرُوا", "nazara", "«and see»", "«ve bakın»", wa=True),
  tok("كَيْفَ", "kayfa", "noun", ["al-istifham", KN], "اسْمُ اسْتِفْهَامٍ مَبْنِيٌّ فِي مَحَلِّ نَصْبٍ خَبَرُ كَانَ مُقَدَّمٌ.", "«how» — the question noun; kāna's fronted khabar.", "«nasıl» — istifham ismi; kâne'nin mukaddem haberi."),
  tok("كَانَ", "kana", "verb", [KN, "hollow-verbs"], "فِعْلٌ مَاضٍ نَاقِصٌ.", "«was»", "«oldu»"),
  tok("عَاقِبَةُ", "aqiba", "noun", [KN, ID], "اسْمُ كَانَ مَرْفُوعٌ، مُضَافٌ.", "«the end of» — kāna's ism.", "«sonu» — kâne'nin ismi."),
  mudaf_ilayh("الْمُفْسِدِينَ", "mufsid", "«the corrupters»", "«bozguncuların»", punct=".", tags=["jam-mudhakkar-salim", "ism-fail"], ar="مُضَافٌ إِلَيْهِ مَجْرُورٌ بِالْيَاءِ لِأَنَّهُ جَمْعُ مُذَكَّرٍ سَالِمٌ."),
]))
# ---------------------------------------------------------------- §6
sen("s4", "And their clever ones scrutinised the meaning and reasons of this call, and said, in conceit and vanity, as though they had uncovered a secret or solved a riddle:",
        "Zekileri bu çağrının mânâsını ve sebebini inceden inceye yorumladılar ve sanki bir sır keşfetmiş ya da bir bilmece çözmüş gibi kibir ve böbürlenme içinde dediler ki:", [
  tok("وَقَدْ", "qad", "part", [AT, "qad-harf"], "الْوَاوُ لِلِاسْتِئْنَافِ، وَقَدْ حَرْفُ تَحْقِيقٍ.", "«and indeed»", "«ve gerçekten»", segments=wa_("قَدْ", "qad", "part")),
  tok("دَقَّقَ", "daqqaqa", "verb", ["form-ii-verbs"], "فِعْلٌ مَاضٍ.", "«scrutinised»", "«inceden inceye inceledi»"),
  tok("أَذْكِيَاؤُهُمْ", "dhaki", "noun", [FL, ID, "jam-taksir", "ism-mamdud"], "فَاعِلٌ مَرْفُوعٌ بِالضَّمَّةِ، مُضَافٌ، وَهُمْ مُضَافٌ إِلَيْهِ — جَمْعُ ذَكِيٍّ، هَمْزَتُهُ عَلَى وَاوٍ لِلضَّمَّةِ.", "«their clever ones» — the doer; the hamza seated on a wāw by the ḍamma.", "«zekileri» — fâil; hemzesi damme için vâv üzerinde.", segments=[seg("أَذْكِيَاؤُ", "dhaki", "noun"), pr3mp()]),
  fi(), majrur("تَفْسِيرِ", "tafsir", "«the interpreting of»", "«yorumlamada»", tags=[ID, "masdar"], ar="مَجْرُورٌ بِفِي، مُضَافٌ."),
  tok("هٰذِهِ", "hadhihi", "pron", ["asma-al-ishara", ID], "اسْمُ إِشَارَةٍ فِي مَحَلِّ جَرٍّ مُضَافٌ إِلَيْهِ.", "«this»", "«bu»"),
  tok("الدَّعْوَةِ", "dawa", "noun", ["badal"], "بَدَلٌ مِنِ اسْمِ الْإِشَارَةِ مَجْرُورٌ.", "«call» — the badal.", "«çağrının» — bedel."),
  tok("وَتَعْلِيلِهَا", "talil", "noun", [AT, ID, "masdar"], "الْوَاوُ عَاطِفَةٌ، وَتَعْلِيلِ مَعْطُوفٌ مَجْرُورٌ، مُضَافٌ، وَهَا مُضَافٌ إِلَيْهِ.", "«and its reasoning»", "«ve sebebini»", punct="،", segments=[seg("وَ", "wa", "conj"), seg("تَعْلِيلِ", "talil", "noun"), pr3fs_()]),
  qalu("وَقَالُوا", wa=True, punct=None),
  fi(), majrur("تِيهٍ", "tih", "«conceit»", "«kibir»"), atf_majrur("وَزَهْوٍ", "zahw", "«and vanity»", "«ve böbürlenme»"),
  tok("كَأَنَّهُمُ", "kaanna", "part", [IW, "tashbih"], "حَرْفٌ مُشَبَّهٌ بِالْفِعْلِ لِلتَّشْبِيهِ، وَهُمْ اسْمُهُ، حُرِّكَتْ مِيمُهُ بِالضَّمِّ لِالْتِقَاءِ السَّاكِنَيْنِ.", "«as though they» — ka-anna with its ism.", "«sanki onlar» — keenne ve ismi.", segments=[seg("كَأَنَّ", "kaanna", "part"), seg("هُمُ", "pron-3mp", "pron")]),
  tok("اكْتَشَفُوا", "iktashafa", "verb", [IW, MB, "form-viii-verbs"], "فِعْلٌ مَاضٍ، وَالْوَاوُ فَاعِلٌ — وَالْجُمْلَةُ خَبَرُ كَأَنَّ.", "«had uncovered» — the khabar of ka-anna.", "«keşfetmişler» — keenne'nin haberi."),
  maful_("سِرًّا", "sirr", "«a secret»", "«bir sır»"),
  tok("أَوْ", "aw", "part", [AT], "حَرْفُ عَطْفٍ.", "«or»", "«ya da»"),
  tok("فَكُّوا", "fakka", "verb", [AT, MB, "doubled-verbs"], "فِعْلٌ مَاضٍ، وَالْوَاوُ فَاعِلٌ.", "«solved»", "«çözmüşler»"),
  maful_("لُغْزًا", "lughz", "«a riddle»", "«bir bilmece»", punct=":"),
])
sen("s5", "«O Shuʿayb, does your prayer command you that we leave what our fathers worshipped, or that we not do with our wealth what we please? You are indeed the forbearing, the right-minded one!» (11:87).",
        "«Ey Şuayb, babalarımızın taptıklarını bırakmamızı yahut mallarımızda dilediğimizi yapmamamızı sana namazın mı emrediyor? Sen gerçekten yumuşak huylu, aklı başında birisin!» (11:87).", quran([
  tok("يَا", "ya-nida", "part", ["vocative-munada"], "حَرْفُ نِدَاءٍ.", "«O»", "«ey»"),
  tok("شُعَيْبُ", "shuayb", "propn", ["vocative-munada"], "مُنَادًى مُفْرَدٌ عَلَمٌ مَبْنِيٌّ عَلَى الضَّمِّ فِي مَحَلِّ نَصْبٍ.", "«Shuʿayb» — a single-name munādā, built on the ḍamma.", "«Şuayb» — müfred alem münâdâ, damme üzere mebnî."),
  tok("أَصَلَاتُكَ", "salat", "noun", ["al-istifham", MK, ID], "الْهَمْزَةُ لِلِاسْتِفْهَامِ الْإِنْكَارِيِّ، وَصَلَاةُ مُبْتَدَأٌ مَرْفُوعٌ، مُضَافٌ، وَالْكَافُ مُضَافٌ إِلَيْهِ.", "«does your prayer» — the question hamza; the mubtada.", "«namazın mı» — istifham hemzesi; mübtedâ.", segments=[seg("أَ", "hamza-istifham", "part"), seg("صَلَاتُ", "salat", "noun"), seg("كَ", "pron-2ms", "pron")]),
  tok("تَأْمُرُكَ", "amara-v", "verb", [MK, MB, "mudari-marfu"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: هِيَ، وَالْكَافُ مَفْعُولٌ بِهِ — وَالْجُمْلَةُ خَبَرٌ.", "«command you» — the khabar clause.", "«sana emrediyor» — haber cümlesi.", segments=[seg("تَأْمُرُ", "amara-v", "verb"), seg("كَ", "pron-2ms", "pron")]),
  tok("أَنْ", "an-masdariyya", "part", ["an-masdariyya"], "حَرْفٌ مَصْدَرِيٌّ وَنَصْبٍ — وَالْمَصْدَرُ الْمُؤَوَّلُ فِي مَحَلِّ جَرٍّ بِبَاءٍ مَحْذُوفَةٍ: بِأَنْ نَتْرُكَ.", "«that» — the clause after a dropped bāʾ.", "«-mamızı» — mahzûf bâ'dan sonraki cümle."),
  tok("نَتْرُكَ", "taraka", "verb", ["an-masdariyya", MB], "فِعْلٌ مُضَارِعٌ مَنْصُوبٌ بِأَنْ، وَالْفَاعِلُ مُسْتَتِرٌ: نَحْنُ.", "«we leave» — in naṣb by an.", "«bırakmamızı» — en ile mansûb."),
  tok("مَا", "ma-mawsula", "pron", [MW, MB], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ نَصْبٍ مَفْعُولٌ بِهِ.", "«what» — the relative, the object.", "«… şeyi» — mef'ûl."),
  tok("يَعْبُدُ", "abada", "verb", [MW, "mudari-marfu"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ — صِلَةٌ.", "«worshipped»", "«taptığı»"),
  tok("آبَاؤُنَا", "ab", "noun", [FL, ID, "jam-taksir", "ism-mamdud"], "فَاعِلٌ مَرْفُوعٌ بِالضَّمَّةِ، مُضَافٌ، وَنَا مُضَافٌ إِلَيْهِ — جَمْعُ أَبٍ.", "«our fathers» — the doer.", "«babalarımız» — fâil.", segments=[seg("آبَاؤُ", "ab", "noun"), seg("نَا", "pron-1p", "pron")]),
  tok("أَوْ", "aw", "part", [AT], "حَرْفُ عَطْفٍ.", "«or»", "«yahut»"),
  tok("أَنْ", "an-masdariyya", "part", ["an-masdariyya", AT], "حَرْفٌ مَصْدَرِيٌّ وَنَصْبٍ — مَعْطُوفٌ عَلَى الْأَوَّلِ.", "«that»", "«-mamamızı»"),
  tok("نَفْعَلَ", "faala", "verb", ["an-masdariyya", MB], "فِعْلٌ مُضَارِعٌ مَنْصُوبٌ بِأَنْ، وَالْفَاعِلُ مُسْتَتِرٌ: نَحْنُ.", "«we do»", "«yapmamızı»"),
  fi(), tok("أَمْوَالِنَا", "mal", "noun", [HJ, ID, "jam-taksir"], "مَجْرُورٌ بِفِي، مُضَافٌ، وَنَا مُضَافٌ إِلَيْهِ.", "«our wealth»", "«mallarımızda»", segments=[seg("أَمْوَالِ", "mal", "noun"), seg("نَا", "pron-1p", "pron")]),
  tok("مَا", "ma-mawsula", "pron", [MW, MB], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ نَصْبٍ مَفْعُولٌ بِهِ.", "«what»", "«… şeyi»"),
  tok("نَشَاءُ", "shaa", "verb", [MW, "mudari-marfu", "hollow-verbs"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: نَحْنُ — صِلَةٌ.", "«we please»", "«dilediğimiz»"),
  tok("إِنَّكَ", "inna", "part", [IW], "إِنَّ حَرْفٌ مُشَبَّهٌ بِالْفِعْلِ، وَالْكَافُ اسْمُهَا.", "«indeed you» — inna with its ism.", "«şüphesiz sen» — inne ve ismi.", segments=[seg("إِنَّ", "inna", "part"), seg("كَ", "pron-2ms", "pron")]),
  tok("لَأَنْتَ", "anta", "pron", [IW, MK, "tawkid"], "اللَّامُ لَامُ الِابْتِدَاءِ الْمُزَحْلَقَةُ، وَأَنْتَ ضَمِيرُ فَصْلٍ — أَوْ مُبْتَدَأٌ خَبَرُهُ الْحَلِيمُ، وَالْجُمْلَةُ خَبَرُ إِنَّ.", "«you are» — the slid lām; the pronoun of separation, or a mubtada.", "«sen» — kayan lâm; fasl zamiri, ya da mübtedâ.", segments=[seg("لَ", "lam-ibtida", "part"), seg("أَنْتَ", "anta", "pron")]),
  tok("الْحَلِيمُ", "halim", "noun", [IW], "خَبَرُ إِنَّ مَرْفُوعٌ.", "«the forbearing» — the khabar of inna.", "«yumuşak huylu» — inne'nin haberi."),
  tok("الرَّشِيدُ", "rashid", "noun", [IW, NA], "نَعْتٌ أَوْ خَبَرٌ ثَانٍ مَرْفُوعٌ.", "«the right-minded» — a second khabar.", "«aklı başında» — ikinci haber.", punct="."),
]))
# ---------------------------------------------------------------- §7
sen("s6", "And Shuʿayb was gentle with them; he was neither harsh nor angry,", "Şuayb onlara yumuşak davrandı; ne sertleşti ne öfkelendi;", [
  tok("وَتَلَطَّفَ", "talattafa", "verb", [AT, "form-v-verbs"], "الْوَاوُ لِلِاسْتِئْنَافِ، وَتَلَطَّفَ فِعْلٌ مَاضٍ.", "«and was gentle»", "«ve yumuşak davrandı»", segments=wa_("تَلَطَّفَ", "talattafa", "verb")),
  prep_pron("لَهُمْ", "li", "هُمْ", "pron-3mp", "«with them»", "«onlara»"),
  tok("شُعَيْبٌ", "shuayb", "propn", [FL], "فَاعِلٌ مَرْفُوعٌ بِالضَّمَّةِ.", "«Shuʿayb» — the doer.", "«Şuayb» — fâil.", punct="،"),
  tok("فَلَمْ", "lam", "part", [AT, "lam-jazim"], "الْفَاءُ عَاطِفَةٌ، وَلَمْ حَرْفُ نَفْيٍ وَجَزْمٍ وَقَلْبٍ.", "«and did not»", "«ve -madı»", segments=[seg("فَ", "fa", "conj"), seg("لَمْ", "lam", "part")]),
  tok("يَقْسُ", "qasa-harsh", "verb", ["lam-jazim", "naqis-verbs"], "فِعْلٌ مُضَارِعٌ مَجْزُومٌ بِلَمْ، وَعَلَامَةُ جَزْمِهِ حَذْفُ حَرْفِ الْعِلَّةِ.", "«was harsh» — majzūm: the weak letter dropped.", "«sertleşti» — meczûm: illet harfi düşmüş."),
  tok("وَلَمْ", "lam", "part", [AT, "lam-jazim"], "الْوَاوُ عَاطِفَةٌ، وَلَمْ حَرْفُ نَفْيٍ وَجَزْمٍ وَقَلْبٍ.", "«nor»", "«ne de»", segments=wa_("لَمْ", "lam", "part")),
  tok("يَغْضَبْ", "ghadiba", "verb", ["lam-jazim"], "فِعْلٌ مُضَارِعٌ مَجْزُومٌ بِلَمْ، وَعَلَامَةُ جَزْمِهِ السُّكُونُ.", "«was angry» — majzūm on sukūn.", "«öfkelendi» — sükûn ile meczûm.", punct="،"),
])
sen("s7", "and he made them understand that nothing had moved him to this call and counsel — after a long silence, and after not touching the corrupt morals and unjust dealings they lived in — except what God had lately honoured him with: prophethood and revelation, the opening of his breast, and a light He gave him from Himself;",
        "ve onlara anlattı ki, uzun bir sessizlikten ve içinde bulundukları bozuk ahlâk ile zalimce davranışlara dokunmamaktan sonra, kendisini bu çağrı ve nasihate sevk eden, Allah'ın yakınlarda kendisine lütfettiği şeyden başkası değildi: peygamberlik ve vahiy, göğsünün açılması ve O'nun katından verilen bir nur;", [
  tok("وَأَفْهَمَهُمْ", "afhama", "verb", [AT, MB, "form-iv-verbs", "mafulayn"], "الْوَاوُ عَاطِفَةٌ، وَأَفْهَمَ فِعْلٌ مَاضٍ، وَالْفَاعِلُ مُسْتَتِرٌ: هُوَ، وَهُمْ مَفْعُولٌ أَوَّلُ — وَالْمَصْدَرُ الْمُؤَوَّلُ بَعْدَهُ مَفْعُولٌ ثَانٍ.", "«and he made them understand» — hum the first object; the clause the second.", "«ve onlara anlattı» — hüm birinci mef'ûl; cümle ikinci.", segments=[seg("وَ", "wa", "conj"), seg("أَفْهَمَ", "afhama", "verb"), pr3mp()]),
  annahu("أَنَّهُ", wa=False, pre_ar="", en="«that he»", tr="«ki o»", extra=["mafulayn"]),
  tok("مَا", "ma-nafiya", "part", ["anwa-ma"], "حَرْفُ نَفْيٍ.", "«nothing»", "«değil»"),
  tok("حَمَلَهُ", "hamala", "verb", [IW, MB], "فِعْلٌ مَاضٍ، وَالْهَاءُ مَفْعُولٌ بِهِ — وَالْجُمْلَةُ خَبَرُ أَنَّ، وَالْفَاعِلُ يَأْتِي بَعْدَ إِلَّا.", "«moved him» — the khabar of anna; its doer comes after illā.", "«onu sevk etti» — enne'nin haberi; fâili illâ'dan sonra.", segments=[seg("حَمَلَ", "hamala", "verb"), pr3ms()]),
  tok("عَلَى", "ala", "prep", [HJ], "حَرْفُ جَرٍّ.", "«to»", "«-e»"),
  tok("هٰذِهِ", "hadhihi", "pron", ["asma-al-ishara", HJ], "اسْمُ إِشَارَةٍ فِي مَحَلِّ جَرٍّ.", "«this»", "«bu»"),
  tok("الدَّعْوَةِ", "dawa", "noun", ["badal"], "بَدَلٌ مَجْرُورٌ.", "«call»", "«çağrı»"), atf_majrur("وَالنَّصِيحَةِ", "nasiha", "«and counsel»", "«ve nasihate»"),
  tok("بَعْدَ", "bada", "noun", [MF, ID], "ظَرْفُ زَمَانٍ مَنْصُوبٌ، مُضَافٌ.", "«after»", "«sonra»"),
  mudaf_ilayh("صَمْتٍ", "samt", "«a silence»", "«bir sessizlikten»", tags=["masdar"]), naat("طَوِيلٍ", "tawil-long", "«long»", "«uzun»"),
  atf_majrur("وَعَدَمِ", "adam", "«and the absence of»", "«ve olmayışından»", tags=[ID], ar="مَعْطُوفٌ عَلَى صَمْتٍ مَجْرُورٌ، مُضَافٌ."),
  mudaf_ilayh("تَعَرُّضٍ", "taarrud", "«touching»", "«dokunmanın»", tags=["masdar", "form-v-verbs"]),
  tok("لِمَا", "ma-mawsula", "pron", [HJ, MW], "اللَّامُ حَرْفُ جَرٍّ، وَمَا اسْمٌ مَوْصُولٌ فِي مَحَلِّ جَرٍّ.", "«to what»", "«… şeye»", segments=[seg("لِ", "li", "prep"), seg("مَا", "ma-mawsula", "pron")]),
  tok("كَانُوا", "kana", "verb", [MW, KN, "hollow-verbs"], "فِعْلٌ مَاضٍ نَاقِصٌ، وَالْوَاوُ اسْمُهُ — صِلَةٌ.", "«they were» — the ṣila.", "«idiler» — sıla."),
  prep_pron("عَلَيْهِ", "ala", "هِ", "pron-3ms", "«upon» — kāna's khabar.", "«üzerinde» — kâne'nin haberi.", tags=[KN]),
  tok("مِنْ", "min", "prep", [HJ], "حَرْفُ جَرٍّ لِلْبَيَانِ.", "«of»", "«-den»"),
  majrur("أَخْلَاقٍ", "khuluq", "«morals»", "«ahlâk»", tags=["jam-taksir"]), naat("فَاسِدَةٍ", "fasid", "«corrupt»", "«bozuk»", tags=["ism-fail"]),
  atf_majrur("وَتَصَرُّفَاتٍ", "tasarruf", "«and dealings»", "«ve davranışlar»", tags=["jam-muannath-salim"]), naat("جَائِرَةٍ", "jair", "«unjust»", "«zalimce»", punct="،", tags=["ism-fail", "hollow-verbs"]),
  tok("إِلَّا", "illa", "part", ["istithna", "istithna-mufarragh"], "أَدَاةُ اسْتِثْنَاءٍ مُفَرَّغٍ.", "«except» — the exception with nothing before it: the doer follows.", "«ancak» — müferrağ istisnâ: fâil ardından gelir."),
  tok("مَا", "ma-mawsula", "pron", [MW, FL], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ رَفْعٍ فَاعِلُ حَمَلَهُ.", "«what» — the doer of «moved him».", "«… şey» — «sevk etti»nin fâili."),
  tok("أَكْرَمَهُ", "akrama", "verb", [MW, MB, "form-iv-verbs"], "فِعْلٌ مَاضٍ، وَالْهَاءُ مَفْعُولٌ بِهِ — صِلَةٌ.", "«honoured him»", "«ona lütfetti»", segments=[seg("أَكْرَمَ", "akrama", "verb"), pr3ms()]),
  allah_fail(), prep_pron("بِهِ", "bi", "هِ", "pron-3ms", "«with»", "«onunla»"),
  tok("أَخِيرًا", "akhir", "noun", [MF], "ظَرْفُ زَمَانٍ مَنْصُوبٌ — أَيْ: فِي الْآخِرِ.", "«lately» — the ẓarf.", "«yakınlarda» — zarf.", punct=":"),
  tok("بِالنُّبُوَّةِ", "nubuwwa", "noun", [HJ, "badal"], "الْبَاءُ حَرْفُ جَرٍّ، وَالنُّبُوَّةِ مَجْرُورٌ — بَدَلٌ مِنْ بِهِ.", "«with prophethood» — the badal of «with».", "«peygamberlikle» — «onunla»nın bedeli.", segments=[seg("بِ", "bi", "prep"), seg("النُّبُوَّةِ", "nubuwwa", "noun")]),
  atf_majrur("وَالْوَحْيِ", "wahy", "«and revelation»", "«ve vahiyle»"),
  tok("وَمَا", "ma-mawsula", "pron", [AT, MW], "الْوَاوُ عَاطِفَةٌ، وَمَا اسْمٌ مَوْصُولٌ مَعْطُوفٌ فِي مَحَلِّ جَرٍّ.", "«and what»", "«ve … şeyle»", segments=wa_("مَا", "ma-mawsula", "pron")),
  tok("شَرَحَ", "sharaha", "verb", [MW, MB], "فِعْلٌ مَاضٍ، وَالْفَاعِلُ مُسْتَتِرٌ: هُوَ — صِلَةٌ.", "«He opened»", "«açtı»"),
  prep_pron("لَهُ", "li", "هُ", "pron-3ms", "«for him»", "«ona»"),
  tok("صَدْرَهُ", "sadr", "noun", [MB, ID], "مَفْعُولٌ بِهِ مَنْصُوبٌ، مُضَافٌ، وَالْهَاءُ مُضَافٌ إِلَيْهِ.", "«his breast»", "«göğsünü»", segments=[seg("صَدْرَ", "sadr", "noun"), pr3ms()]),
  tok("وَآتَاهُ", "aataa", "verb", [AT, MB, "mafulayn", "naqis-verbs"], "الْوَاوُ عَاطِفَةٌ، وَآتَى فِعْلٌ مَاضٍ، وَالْهَاءُ مَفْعُولٌ أَوَّلُ.", "«and gave him»", "«ve ona verdi»", segments=[seg("وَ", "wa", "conj"), seg("آتَا", "aataa", "verb"), pr3ms()]),
  tok("نُورًا", "nur", "noun", ["mafulayn"], "مَفْعُولٌ ثَانٍ مَنْصُوبٌ.", "«a light» — the second object.", "«bir nur» — ikinci mef'ûl."),
  tok("مِنْ", "min", "prep", [HJ, NA], "حَرْفُ جَرٍّ — صِفَةٌ لِنُورًا.", "«from»", "«-den»"),
  tok("عِنْدِهِ", "inda", "noun", [HJ, ID], "مَجْرُورٌ بِمِنْ، مُضَافٌ، وَالْهَاءُ مُضَافٌ إِلَيْهِ.", "«Himself»", "«katından»", punct=".", segments=[seg("عِنْدِ", "inda", "noun"), pr3msi()]),
])
sen("s8", "and that envy did not drive him to it — for God had made him rich and provided for him lawfully and well — and that he was happy with that, content in soul, easy in mind, thankful to God Most High with heart and tongue;",
        "ve onu buna hasedin sevk etmediğini — zira Allah onu zengin etmiş ve ona helâl, temiz rızık vermişti — ve bununla mutlu, gönlü hoş, zihni rahat, kalbi ve diliyle Allah Teâlâ'ya şükreden biri olduğunu;", [
  annahu(),
  la_nafiya(), tok("يَحْمِلُهُ", "hamala", "verb", [IW, "la-nafiya", MB, "mudari-marfu"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْهَاءُ مَفْعُولٌ بِهِ — خَبَرُ أَنَّ.", "«drive him» — the khabar of anna.", "«onu sevk eder» — enne'nin haberi.", segments=[seg("يَحْمِلُ", "hamala", "verb"), pr3ms()]),
  tok("عَلَى", "ala", "prep", [HJ], "حَرْفُ جَرٍّ.", "«to»", "«-e»"), tok("ذٰلِكَ", "dhalika", "pron", ["asma-al-ishara", HJ], "اسْمُ إِشَارَةٍ فِي مَحَلِّ جَرٍّ.", "«that»", "«buna»"),
  tok("الْحَسَدُ", "hasad", "noun", [FL], "فَاعِلٌ مَرْفُوعٌ بِالضَّمَّةِ.", "«envy» — the doer.", "«haset» — fâil.", punct="،"),
  tok("فَقَدْ", "qad", "part", ["qad-harf"], "الْفَاءُ لِلتَّعْلِيلِ، وَقَدْ حَرْفُ تَحْقِيقٍ.", "«for indeed»", "«zira»", segments=[seg("فَ", "fa", "conj"), seg("قَدْ", "qad", "part")]),
  tok("أَغْنَاهُ", "aghna", "verb", [MB, "form-iv-verbs", "naqis-verbs"], "فِعْلٌ مَاضٍ، وَالْهَاءُ مَفْعُولٌ بِهِ.", "«had made him rich»", "«onu zengin etti»", segments=[seg("أَغْنَا", "aghna", "verb"), pr3ms()]),
  allah_fail(),
  tok("وَرَزَقَهُ", "razaqa", "verb", [AT, MB, "mafulayn"], "الْوَاوُ عَاطِفَةٌ، وَرَزَقَ فِعْلٌ مَاضٍ، وَالْهَاءُ مَفْعُولٌ أَوَّلُ.", "«and provided for him»", "«ve ona rızık verdi»", segments=[seg("وَ", "wa", "conj"), seg("رَزَقَ", "razaqa", "verb"), pr3ms()]),
  tok("حَلَالًا", "halal", "noun", ["mafulayn"], "مَفْعُولٌ ثَانٍ مَنْصُوبٌ.", "«lawful»", "«helâl»"), naat("طَيِّبًا", "tayyib", "«good»", "«temiz»", punct="،", case="nasb"),
  annahu(),
  tok("بِذٰلِكَ", "dhalika", "pron", [HJ, "asma-al-ishara"], "الْبَاءُ حَرْفُ جَرٍّ، وَذٰلِكَ فِي مَحَلِّ جَرٍّ.", "«with that»", "«bununla»", segments=[seg("بِ", "bi", "prep"), seg("ذٰلِكَ", "dhalika", "pron")]),
  khabar_inna("سَعِيدٌ", "said", "«happy»", "«mutlu»", part="أَنَّ"),
  tok("هَنِيُّ", "hani-content", "noun", [IW, ID, NA], "خَبَرٌ ثَانٍ مَرْفُوعٌ، مُضَافٌ — إِضَافَةٌ لَفْظِيَّةٌ.", "«content of» — a second khabar, annexed (a verbal annexation).", "«hoş» — ikinci haber, lafzî izâfetle muzâf."),
  mudaf_ilayh("النَّفْسِ", "nafs", "«soul»", "«gönlü»", punct="،"),
  tok("رَخِيُّ", "rakhi", "noun", [IW, ID, NA], "خَبَرٌ ثَالِثٌ مَرْفُوعٌ، مُضَافٌ.", "«easy of» — a third khabar.", "«rahat» — üçüncü haber."),
  mudaf_ilayh("الْبَالِ", "bal-state", "«mind»", "«zihni»", punct="،"),
  tok("شَاكِرٌ", "shakir", "noun", [IW, "ism-fail"], "خَبَرٌ رَابِعٌ مَرْفُوعٌ.", "«thankful» — a fourth khabar.", "«şükreden» — dördüncü haber."),
  tok("لِلّٰهِ", "allah", "propn", [HJ], "اللَّامُ حَرْفُ جَرٍّ، وَلَفْظُ الْجَلَالَةِ مَجْرُورٌ.", "«to God»", "«Allah'a»", segments=[seg("لِ", "li", "prep"), seg("لّٰهِ", "allah", "propn")]),
  tok("تَعَالَى", "taala", "verb", ["ism-maqsur-manqus"], "فِعْلٌ مَاضٍ، وَالْفَاعِلُ مُسْتَتِرٌ — جُمْلَةٌ مُعْتَرِضَةٌ لِلتَّعْظِيمِ.", "«Most High»", "«Teâlâ»"),
  tok("بِالْقَلْبِ", "qalb", "noun", [HJ], "الْبَاءُ حَرْفُ جَرٍّ، وَالْقَلْبِ مَجْرُورٌ.", "«with heart»", "«kalbiyle»", segments=[seg("بِ", "bi", "prep"), seg("الْقَلْبِ", "qalb", "noun")]),
  atf_majrur("وَاللِّسَانِ", "lisan", "«and tongue»", "«ve diliyle»", punct="."),
])
sen("s9", "then, that he does not forbid them a thing and commit it himself, nor keep them from something and do it; and that he is not of those who command people to piety and forget themselves, nor of those who say what they do not do;",
        "sonra, onlara bir şeyi yasaklayıp kendisinin onu işlemediğini, onları bir şeyden alıkoyup kendisinin onu yapmadığını; insanlara iyiliği emredip kendilerini unutanlardan da, yapmadıklarını söyleyenlerden de olmadığını;", [
  tok("ثُمَّ", "thumma", "part", [AT], "حَرْفُ عَطْفٍ.", "«then»", "«sonra»"),
  tok("إِنَّهُ", "inna", "part", [IW], "إِنَّ حَرْفٌ مُشَبَّهٌ بِالْفِعْلِ، وَالْهَاءُ اسْمُهَا — كُسِرَتْ بَعْدَ ثُمَّ لِلِاسْتِئْنَافِ.", "«he» — inna with its ism, kasra after thumma.", "«o» — inne ve ismi; sümme'den sonra kesre.", segments=[seg("إِنَّ", "inna", "part"), pr3ms()]),
  la_nafiya(), tok("يَنْهَاهُمْ", "naha", "verb", [IW, "la-nafiya", MB, "naqis-verbs", "mudari-marfu"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ بِضَمَّةٍ مُقَدَّرَةٍ، وَهُمْ مَفْعُولٌ بِهِ — خَبَرُ إِنَّ.", "«forbid them» — the khabar of inna.", "«onları yasaklar» — inne'nin haberi.", segments=[seg("يَنْهَا", "naha", "verb"), pr3mp()]),
  tok("عَنْ", "an", "prep", [HJ], "حَرْفُ جَرٍّ.", "«from»", "«-den»"), majrur("أَمْرٍ", "amr-noun", "«a thing»", "«bir şeyi»"),
  wa_mudari("وَيَرْتَكِبُهُ", "irtakaba", "«commit it»", "«onu işler»", tags=["form-viii-verbs"], obj="هُ", obj_lex="pron-3ms", punct="،"),
  wa_mudari("وَيَمْنَعُهُمْ", "manaa", "«keep them»", "«onları alıkoyar»", obj="هُمْ"),
  tok("مِنْ", "min", "prep", [HJ], "حَرْفُ جَرٍّ.", "«from»", "«-den»"), majrur("شَيْءٍ", "shay", "«something»", "«bir şey»"),
  wa_mudari("وَيَأْتِيهِ", "ata", "«do it»", "«onu yapar»", tags=["naqis-verbs"], obj="هِ", obj_lex="pron-3ms", punct="،"),
  tok("وَإِنَّهُ", "inna", "part", [AT, IW], "الْوَاوُ عَاطِفَةٌ، وَإِنَّ حَرْفٌ مُشَبَّهٌ بِالْفِعْلِ، وَالْهَاءُ اسْمُهَا.", "«and that he»", "«ve onun»", segments=[seg("وَ", "wa", "conj"), seg("إِنَّ", "inna", "part"), pr3ms()]),
  tok("لَيْسَ", "laysa", "verb", [IW, KN, "ma-la-mushabbaha"], "فِعْلٌ مَاضٍ نَاقِصٌ جَامِدٌ، وَاسْمُهُ مُسْتَتِرٌ: هُوَ — وَالْجُمْلَةُ خَبَرُ إِنَّ.", "«is not» — the khabar clause of inna.", "«değildir» — inne'nin haber cümlesi."),
  tok("مِنَ", "min", "prep", [HJ, KN], "حَرْفُ جَرٍّ، حُرِّكَ بِالْفَتْحِ — وَالْجَارُّ وَالْمَجْرُورُ خَبَرُ لَيْسَ.", "«of» — the phrase is laysa's khabar.", "«-den» — câr-mecrûr leyse'nin haberi."),
  tok("الَّذِينَ", "alladhina", "pron", [MW, HJ], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ جَرٍّ.", "«those who»", "«… olanlardan»"),
  khamsa("يَأْمُرُونَ", "amara-v", "«command» — the ṣila.", "«emredenler» — sıla.", tags=[MW, MB]),
  maful_("النَّاسَ", "nas", "«people»", "«insanlara»"),
  tok("بِالْبِرِّ", "birr", "noun", [HJ], "الْبَاءُ حَرْفُ جَرٍّ، وَالْبِرِّ مَجْرُورٌ.", "«to piety»", "«iyiliği»", segments=[seg("بِ", "bi", "prep"), seg("الْبِرِّ", "birr", "noun")]),
  khamsa("وَيَنْسَوْنَ", "nasiya", "«and forget»", "«ve unutanlar»", wa=True, tags=["naqis-verbs", MB]),
  tok("أَنْفُسَهُمْ", "nafs", "noun", [MB, ID, "jam-taksir"], "مَفْعُولٌ بِهِ مَنْصُوبٌ، مُضَافٌ، وَهُمْ مُضَافٌ إِلَيْهِ.", "«themselves»", "«kendilerini»", punct="،", segments=[seg("أَنْفُسَ", "nafs", "noun"), pr3mp()]),
  la_nafiya("وَلَا", wa=True), tok("مِنَ", "min", "prep", [HJ, AT], "حَرْفُ جَرٍّ — مَعْطُوفٌ عَلَى الْأَوَّلِ.", "«of»", "«-den»"),
  tok("الَّذِينَ", "alladhina", "pron", [MW, HJ], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ جَرٍّ.", "«those who»", "«… olanlardan»"),
  khamsa("يَقُولُونَ", "qala", "«say» — the ṣila.", "«söyleyenler» — sıla.", tags=[MW, "hollow-verbs", MB]),
  tok("مَا", "ma-mawsula", "pron", [MW, MB], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ نَصْبٍ مَفْعُولٌ بِهِ.", "«what»", "«… şeyi»"),
  la_nafiya(), khamsa("يَفْعَلُونَ", "faala", "«do»", "«yapmazlar»", tags=[MW, "la-nafiya"], punct="،"),
])
sen("s10", "he only wants to set them right, to make them happy and to save them from the punishment that hovers over their heads; and all grace returns to God Most High, and on Him is his reliance.",
         "o yalnız onları ıslah etmek, mutlu etmek ve başlarının üstünde dolaşan azaptan kurtarmak ister; bütün lütuf Allah Teâlâ'ya döner ve dayanağı O'dur.", [
  tok("إِنَّمَا", "innama", "part", ["innama-kaffa", "qasr"], "أَدَاةُ حَصْرٍ: إِنَّ الْمَكْفُوفَةُ بِمَا.", "«only» — the tool of restriction.", "«ancak» — hasr edatı."),
  tok("يُرِيدُ", "arada", "verb", ["mudari-marfu", "hollow-verbs", "form-iv-verbs", MB], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: هُوَ.", "«he wants»", "«ister»"),
  tok("إِصْلَاحَهُمْ", "islah", "noun", [MB, ID, "masdar"], "مَفْعُولٌ بِهِ مَنْصُوبٌ، مُضَافٌ، وَهُمْ مُضَافٌ إِلَيْهِ — الْمَصْدَرُ مُضَافٌ إِلَى مَفْعُولِهِ.", "«to set them right» — the masdar annexed to its object.", "«onları ıslah etmeyi» — mef'ûlüne muzâf masdar.", segments=[seg("إِصْلَاحَ", "islah", "noun"), pr3mp()]),
  tok("وَإِسْعَادَهُمْ", "isad", "noun", [AT, ID, "masdar"], "الْوَاوُ عَاطِفَةٌ، وَإِسْعَادَ مَعْطُوفٌ مَنْصُوبٌ، مُضَافٌ.", "«and to make them happy»", "«ve mutlu etmeyi»", segments=[seg("وَ", "wa", "conj"), seg("إِسْعَادَ", "isad", "noun"), pr3mp()]),
  tok("وَإِنْقَاذَهُمْ", "inqadh", "noun", [AT, ID, "masdar"], "الْوَاوُ عَاطِفَةٌ، وَإِنْقَاذَ مَعْطُوفٌ مَنْصُوبٌ، مُضَافٌ.", "«and to save them»", "«ve kurtarmayı»", segments=[seg("وَ", "wa", "conj"), seg("إِنْقَاذَ", "inqadh", "noun"), pr3mp()]),
  tok("مِنَ", "min", "prep", [HJ], "حَرْفُ جَرٍّ، حُرِّكَ بِالْفَتْحِ لِالْتِقَاءِ السَّاكِنَيْنِ.", "«from»", "«-den»"), majrur("الْعَذَابِ", "adhab", "«the punishment»", "«azaptan»"),
  tok("الَّذِي", "alladhi", "pron", [MW, NA], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ جَرٍّ نَعْتٌ.", "«that»", "«… olan»"),
  tok("يُحَلِّقُ", "hallaqa", "verb", [MW, "mudari-marfu", "form-ii-verbs"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ — صِلَةٌ.", "«hovers» — the ṣila.", "«dolaşan» — sıla."),
  tok("عَلَى", "ala", "prep", [HJ], "حَرْفُ جَرٍّ.", "«over»", "«üstünde»"),
  tok("رُؤُوسِهِمْ", "ras", "noun", [HJ, ID, "jam-taksir"], "مَجْرُورٌ بِعَلَى، مُضَافٌ، وَهِمْ مُضَافٌ إِلَيْهِ — جَمْعُ رَأْسٍ.", "«their heads»", "«başlarının»", punct="،", segments=[seg("رُؤُوسِ", "ras", "noun"), seg("هِمْ", "pron-3mp", "pron")]),
  tok("وَإِنَّ", "inna", "part", [AT, IW], "الْوَاوُ عَاطِفَةٌ، وَإِنَّ حَرْفٌ مُشَبَّهٌ بِالْفِعْلِ.", "«and indeed»", "«ve şüphesiz»", segments=wa_("إِنَّ", "inna", "part")),
  ism_inna("الْفَضْلَ", "fadl", "«grace»", "«lütuf»"),
  tok("كُلَّهُ", "kull", "noun", ["tawkid", ID], "تَوْكِيدٌ مَعْنَوِيٌّ مَنْصُوبٌ، مُضَافٌ، وَالْهَاءُ مُضَافٌ إِلَيْهِ.", "«all of it» — the emphasis.", "«bütünü» — te'kid.", segments=[seg("كُلَّ", "kull", "noun"), pr3ms()]),
  tok("يَرْجِعُ", "rajaa", "verb", [IW, "mudari-marfu"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ — وَالْجُمْلَةُ خَبَرُ إِنَّ.", "«returns» — the khabar of inna.", "«döner» — inne'nin haberi."),
  tok("إِلَى", "ila", "prep", [HJ], "حَرْفُ جَرٍّ.", "«to»", "«-e»"),
  tok("اللهِ", "allah", "propn", [HJ], "لَفْظُ الْجَلَالَةِ مَجْرُورٌ.", "«God»", "«Allah'a»"),
  tok("تَعَالَى", "taala", "verb", ["ism-maqsur-manqus"], "فِعْلٌ مَاضٍ، وَالْفَاعِلُ مُسْتَتِرٌ — جُمْلَةٌ مُعْتَرِضَةٌ.", "«Most High»", "«Teâlâ»", punct="،"),
  prep_pron("وَعَلَيْهِ", "ala", "هِ", "pron-3ms", "«and on Him» — the fronted khabar.", "«ve O'nadır» — mukaddem haber.", tags=[AT, MK]),
  tok("اعْتِمَادُهُ", "itimad", "noun", [MK, ID, "masdar", "form-viii-verbs"], "مُبْتَدَأٌ مُؤَخَّرٌ مَرْفُوعٌ، مُضَافٌ، وَالْهَاءُ مُضَافٌ إِلَيْهِ.", "«his reliance» — the delayed mubtada.", "«dayanağı» — muahhar mübtedâ.", punct=".", segments=[seg("اعْتِمَادُ", "itimad", "noun"), pr3ms()]),
])
sen("s11", "He said: «O my people, have you considered: if I stand on a clear proof from my Lord, and He has provided me from Himself a good provision — and I do not wish to go against you to what I forbid you; I wish only to set things right as far as I can, and my success is only through God; on Him I rely and to Him I turn» (11:88).",
         "Dedi ki: «Ey kavmim, söyleyin bakalım: ya ben Rabbimden açık bir delil üzerinde isem ve O bana katından güzel bir rızık vermişse? Size yasakladığım şeyde size aykırı davranmak istemiyorum; ben gücüm yettiğince ıslahtan başkasını istemiyorum; muvaffakiyetim ancak Allah'tandır; O'na dayandım ve O'na yönelirim» (11:88).", [
  qala(punct=":"),
  *quran([
  *ya_qawmi(),
  tok("أَرَأَيْتُمْ", "raa", "verb", ["al-istifham", FL, "naqis-verbs"], "الْهَمْزَةُ لِلِاسْتِفْهَامِ، وَرَأَيْتُمْ فِعْلٌ مَاضٍ، وَالتَّاءُ فَاعِلٌ — بِمَعْنَى أَخْبِرُونِي.", "«have you considered» — «tell me».", "«söyleyin bakalım» — «bana haber verin».", segments=[seg("أَ", "hamza-istifham", "part"), seg("رَأَيْ", "raa", "verb"), seg("تُمْ", "pron-2mp", "pron")]),
  tok("إِنْ", "in-shartiyya", "part", [SH], "حَرْفُ شَرْطٍ جَازِمٌ، جَوَابُهُ مَحْذُوفٌ: أَأَتْرُكُ تَبْلِيغَ الرِّسَالَةِ؟", "«if» — its answer dropped.", "«eğer» — cevabı mahzûf."),
  tok("كُنْتُ", "kana", "verb", [SH, KN, "hollow-verbs"], "فِعْلٌ مَاضٍ نَاقِصٌ فِي مَحَلِّ جَزْمٍ، وَالتَّاءُ اسْمُهُ.", "«I stand»", "«ben … isem»", segments=[seg("كُنْ", "kana", "verb"), seg("تُ", "pron-1s", "pron")]),
  tok("عَلَى", "ala", "prep", [HJ, KN], "حَرْفُ جَرٍّ — وَالْجَارُّ وَالْمَجْرُورُ خَبَرُ كَانَ.", "«on» — kāna's khabar.", "«üzerinde» — kâne'nin haberi."),
  majrur("بَيِّنَةٍ", "bayyina", "«a clear proof»", "«açık bir delil»"),
  tok("مِنْ", "min", "prep", [HJ, NA], "حَرْفُ جَرٍّ — صِفَةٌ لِبَيِّنَةٍ.", "«from»", "«-den»"),
  tok("رَبِّي", "rabb", "noun", [HJ, ID, "ya-al-mutakallim"], "مَجْرُورٌ بِكَسْرَةٍ مُقَدَّرَةٍ، مُضَافٌ، وَالْيَاءُ مُضَافٌ إِلَيْهِ.", "«my Lord»", "«Rabbimden»", segments=[seg("رَبِّ", "rabb", "noun"), seg("ي", "pron-1s", "pron")]),
  tok("وَرَزَقَنِي", "razaqa", "verb", [AT, MB, "mafulayn"], "الْوَاوُ عَاطِفَةٌ، وَرَزَقَ فِعْلٌ مَاضٍ، وَالنُّونُ لِلْوِقَايَةِ، وَالْيَاءُ مَفْعُولٌ أَوَّلُ.", "«and He has provided me»", "«ve bana verdi»", segments=[seg("وَ", "wa", "conj"), seg("رَزَقَ", "razaqa", "verb"), seg("نِ", "nun-wiqaya", "part"), seg("ي", "pron-1s", "pron")]),
  prep_pron("مِنْهُ", "min", "هُ", "pron-3ms", "«from Himself»", "«katından»"),
  tok("رِزْقًا", "rizq", "noun", ["mafulayn"], "مَفْعُولٌ ثَانٍ مَنْصُوبٌ.", "«a provision»", "«bir rızık»"), naat("حَسَنًا", "hasan", "«good»", "«güzel»", case="nasb"),
  tok("وَمَا", "ma-nafiya", "part", [AT, "anwa-ma"], "الْوَاوُ لِلْحَالِ، وَمَا نَافِيَةٌ.", "«and not»", "«ve -miyorum»", segments=wa_("مَا", "ma-nafiya", "part")),
  tok("أُرِيدُ", "arada", "verb", ["mudari-marfu", "hollow-verbs", "form-iv-verbs"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: أَنَا.", "«I wish»", "«istiyorum»"),
  tok("أَنْ", "an-masdariyya", "part", ["an-masdariyya", MB], "حَرْفٌ مَصْدَرِيٌّ وَنَصْبٍ — وَالْمَصْدَرُ الْمُؤَوَّلُ مَفْعُولٌ بِهِ.", "«to»", "«-mayı»"),
  tok("أُخَالِفَكُمْ", "khalafa", "verb", ["an-masdariyya", MB, "form-iii-verbs"], "فِعْلٌ مُضَارِعٌ مَنْصُوبٌ بِأَنْ، وَالْفَاعِلُ مُسْتَتِرٌ: أَنَا، وَكُمْ مَفْعُولٌ بِهِ.", "«go against you»", "«size aykırı davranmak»", segments=[seg("أُخَالِفَ", "khalafa", "verb"), pr2mp()]),
  tok("إِلَى", "ila", "prep", [HJ], "حَرْفُ جَرٍّ.", "«to»", "«-e»"),
  tok("مَا", "ma-mawsula", "pron", [MW, HJ], "اسْمٌ مَوْصُولٌ فِي مَحَلِّ جَرٍّ.", "«what»", "«… şeye»"),
  tok("أَنْهَاكُمْ", "naha", "verb", [MW, MB, "naqis-verbs", "mudari-marfu"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ بِضَمَّةٍ مُقَدَّرَةٍ، وَالْفَاعِلُ مُسْتَتِرٌ: أَنَا، وَكُمْ مَفْعُولٌ بِهِ — صِلَةٌ.", "«I forbid you» — the ṣila.", "«size yasakladığım» — sıla.", segments=[seg("أَنْهَا", "naha", "verb"), pr2mp()]),
  prep_pron("عَنْهُ", "an", "هُ", "pron-3ms", "«from»", "«-den»"),
  tok("إِنْ", "ma-nafiya", "part", ["anwa-ma"], "إِنْ نَافِيَةٌ بِمَعْنَى مَا.", "«not» — the negating in.", "«-miyorum» — nefy in'i."),
  tok("أُرِيدُ", "arada", "verb", ["mudari-marfu", "hollow-verbs", "form-iv-verbs"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: أَنَا.", "«I wish»", "«istiyorum»"),
  tok("إِلَّا", "illa", "part", ["istithna-mufarragh", "qasr"], "أَدَاةُ اسْتِثْنَاءٍ مُفَرَّغٍ — لِلْحَصْرِ.", "«only»", "«ancak»"),
  maful_("الْإِصْلَاحَ", "islah", "«setting right»", "«ıslahı»", tags=["masdar"]),
  tok("مَا", "ma-masdariyya", "part", ["an-masdariyya", MF], "مَا مَصْدَرِيَّةٌ ظَرْفِيَّةٌ — أَيْ: مُدَّةَ اسْتِطَاعَتِي.", "«as long as» — the mā of time.", "«-diği sürece» — zaman mâ'sı."),
  tok("اسْتَطَعْتُ", "istataa", "verb", ["an-masdariyya", FL, "form-x-verbs", "hollow-verbs"], "فِعْلٌ مَاضٍ، وَالتَّاءُ فَاعِلٌ.", "«I can»", "«gücüm yetti»", segments=[seg("اسْتَطَعْ", "istataa", "verb"), seg("تُ", "pron-1s", "pron")]),
  tok("وَمَا", "ma-nafiya", "part", [AT, "anwa-ma", MK], "الْوَاوُ عَاطِفَةٌ، وَمَا نَافِيَةٌ.", "«and not»", "«ve değil»", segments=wa_("مَا", "ma-nafiya", "part")),
  tok("تَوْفِيقِي", "tawfiq", "noun", [MK, ID, "ya-al-mutakallim", "masdar"], "مُبْتَدَأٌ مَرْفُوعٌ بِضَمَّةٍ مُقَدَّرَةٍ، مُضَافٌ، وَالْيَاءُ مُضَافٌ إِلَيْهِ.", "«my success» — the mubtada.", "«muvaffakiyetim» — mübtedâ.", segments=[seg("تَوْفِيقِ", "tawfiq", "noun"), seg("ي", "pron-1s", "pron")]),
  tok("إِلَّا", "illa", "part", ["istithna-mufarragh", "qasr"], "أَدَاةُ حَصْرٍ.", "«only»", "«ancak»"),
  tok("بِاللهِ", "allah", "propn", [HJ, MK], "الْبَاءُ حَرْفُ جَرٍّ، وَلَفْظُ الْجَلَالَةِ مَجْرُورٌ — وَالْجَارُّ وَالْمَجْرُورُ خَبَرٌ.", "«through God» — the khabar.", "«Allah'tandır» — haber.", segments=[seg("بِ", "bi", "prep"), seg("اللهِ", "allah", "propn")]),
  prep_pron("عَلَيْهِ", "ala", "هِ", "pron-3ms", "«on Him» — fronted for restriction.", "«O'na» — hasr için öne alınmış.", tags=["taqdim-al-musnad"]),
  tok("تَوَكَّلْتُ", "tawakkala", "verb", [FL, "form-v-verbs"], "فِعْلٌ مَاضٍ، وَالتَّاءُ فَاعِلٌ.", "«I rely»", "«dayandım»", segments=[seg("تَوَكَّلْ", "tawakkala", "verb"), seg("تُ", "pron-1s", "pron")]),
  prep_pron("وَإِلَيْهِ", "ila", "هِ", "pron-3ms", "«and to Him»", "«ve O'na»", tags=[AT]),
  tok("أُنِيبُ", "anaba", "verb", ["mudari-marfu", "form-iv-verbs", "hollow-verbs"], "فِعْلٌ مُضَارِعٌ مَرْفُوعٌ، وَالْفَاعِلُ مُسْتَتِرٌ: أَنَا.", "«I turn»", "«yönelirim»", punct="."),
  ]),
])

CAND = {
 "tanawwaa": G("tanawwaa", "تَنَوَّعَ", "ن و ع", "verb", "to vary, to be of many kinds (Form V)", "çeşitlenmek (tefa''ul)", 4),
 "khitab": G("khitab", "خِطَاب", "خ ط ب", "noun", "address, speech directed to someone", "hitap", 3),
 "tafannana": G("tafannana", "تَفَنَّنَ", "ف ن ن", "verb", "to use every art, to vary one's ways (Form V)", "türlü yollar denemek, ustalık göstermek (tefa''ul)", 4),
 "nasiha": G("nasiha", "نَصِيحَة", "ن ص ح", "noun", "counsel, sincere advice", "nasihat", 2),
 "shan": G("shan", "شَأْن", "ش أ ن", "noun", "the matter, the way (of); شَأْنَ: as … do", "şan — durum, tarz; şâ'ne: … gibi", 3),
 "ab": G("ab", "أَب", "أ ب و", "noun", "father; الْأَبَوَانِ: the parents", "baba; el-ebevân: anne-baba", 1, plural="آبَاء"),
 "rahim-merciful": G("rahim-merciful", "رَحِيم", "ر ح م", "noun", "merciful, tender", "merhametli, şefkatli", 1),
 "muallim": G("muallim", "مُعَلِّم", "ع ل م", "noun", "a teacher", "öğretmen, muallim", 1),
 "hakim": G("hakim", "حَكِيم", "ح ك م", "noun", "wise", "hikmetli, hakîm", 2),
 "qala": G("qala", "قَالَ", "ق و ل", "verb", "to say", "demek, söylemek", 1),
 "ya-nida": G("ya-nida", "يَا", None, "part", "O — the calling particle", "yâ — nidâ harfi", 1),
 "qawm": G("qawm", "قَوْم", "ق و م", "noun", "a people, a folk", "kavim", 1),
 "abada": G("abada", "عَبَدَ", "ع ب د", "verb", "to worship", "kulluk etmek, ibadet etmek", 1),
 "allah": G("allah", "اللَّه", None, "propn", "God", "Allah", 1),
 "ma-nafiya": G("ma-nafiya", "مَا (النَّافِيَة)", None, "part", "the negating mā (with the māḍī: did not)", "nefy mâ'sı (mâzîyle: -medi)", 2),
 "ilah": G("ilah", "إِلَه", "أ ل ه", "noun", "a god", "ilâh", 1),
 "ghayr": G("ghayr", "غَيْر", None, "noun", "other than; except", "başka, gayri", 2),
 "qad": G("qad", "قَدْ", None, "part", "qad — certainty with the māḍī, possibility with the muḍāriʿ", "kad — mâzîyle tahkik, muzâriyle ihtimal", 3),
 "jaa": G("jaa", "جَاءَ", "ج ي أ", "verb", "to come", "gelmek", 1),
 "bayyina": G("bayyina", "بَيِّنَة", "ب ي ن", "noun", "a clear proof", "açık delil, beyyine", 3),
 "rabb": G("rabb", "رَبّ", "ر ب ب", "noun", "Lord", "Rab", 1),
 "awfa": G("awfa", "أَوْفَى", "و ف ي", "verb", "to give in full, to fulfil (Form IV)", "tam vermek, yerine getirmek (if'âl)", 3),
 "kayl": G("kayl", "كَيْل", "ك ي ل", "noun", "measuring, measure (masdar of كَالَ)", "ölçme, ölçü", 3),
 "mizan": G("mizan", "مِيزَان", "و ز ن", "noun", "a balance, scales; weight", "terazi, tartı", 2),
 "la-nahiya": G("la-nahiya", "لَا (النَّاهِيَة)", None, "part", "the prohibiting lā — puts the muḍāriʿ in jazm", "nehiy lâ'sı — muzâriyi cezm eder", 2),
 "bakhasa": G("bakhasa", "بَخَسَ", "ب خ س", "verb", "to deprive, to give less than due (two objects)", "eksik vermek, hakkını yemek (iki mef'ûllü)", 4),
 "nas": G("nas", "نَاس", "ن و س", "noun", "people", "insanlar", 1),
 "shay": G("shay", "شَيْء", "ش ي أ", "noun", "a thing; شَيْءٌ مِنْ: some", "şey; şey'ün min: biraz", 1, plural="أَشْيَاء"),
 "afsada": G("afsada", "أَفْسَدَ", "ف س د", "verb", "to corrupt, to spread mischief (Form IV)", "bozmak, bozgunculuk yapmak (if'âl)", 2),
 "ard": G("ard", "أَرْض", "أ ر ض", "noun", "earth, land", "yer, arz", 1),
 "bada": G("bada", "بَعْدَ", "ب ع د", "noun", "after (a ẓarf)", "sonra (zarf)", 1),
 "islah": G("islah", "إِصْلَاح", "ص ل ح", "noun", "setting right, reform (masdar of أَصْلَحَ)", "ıslah", 2),
 "dhalikum": G("dhalikum", "ذَلِكُمْ", None, "pron", "that (addressed to many)", "bu, şu (topluluğa hitapla)", 2),
 "khayr": G("khayr", "خَيْر", "خ ي ر", "noun", "good; better (an elative without its hamza)", "hayır; daha hayırlı", 1),
 "in-shartiyya": G("in-shartiyya", "إِنْ", None, "part", "if — the conditional particle", "eğer — şart harfi", 1),
 "kana": G("kana", "كَانَ", "ك و ن", "verb", "to be — raises its ism and puts its khabar in naṣb", "kâne — idi; ismini ref', haberini nasb eder", 1),
 "mumin": G("mumin", "مُؤْمِن", "أ م ن", "noun", "a believer", "mü'min", 1, plural="مُؤْمِنُونَ"),
 "qaada": G("qaada", "قَعَدَ", "ق ع د", "verb", "to sit down", "oturmak", 1),
 "kull": G("kull", "كُلّ", "ك ل ل", "noun", "each, every, all", "her, bütün", 1),
 "sirat": G("sirat", "صِرَاط", "ص ر ط", "noun", "a road, a path", "yol, sırat", 2),
 "awada": G("awada", "أَوْعَدَ", "و ع د", "verb", "to threaten (Form IV)", "tehdit etmek (if'âl)", 4),
 "sadda": G("sadda", "صَدَّ", "ص د د", "verb", "to turn away, to bar (صَدَّ عَنْ)", "çevirmek, alıkoymak", 3),
 "sabil": G("sabil", "سَبِيل", "س ب ل", "noun", "a way, a path", "yol, sebil", 2),
 "man-mawsula": G("man-mawsula", "مَنْ (الْمَوْصُولَة)", None, "pron", "he who, whoever — the relative", "men-i mevsûle — kim ki", 3),
 "aamana": G("aamana", "آمَنَ", "أ م ن", "verb", "to believe (Form IV; آمَنَ بِ)", "iman etmek, inanmak (if'âl; âmene bi-)", 1),
 "bagha": G("bagha", "بَغَى", "ب غ ي", "verb", "to seek; to transgress", "aramak, istemek; azmak", 3),
 "iwaj": G("iwaj", "عِوَج", "ع و ج", "noun", "crookedness", "eğrilik", 4),
 "dhakara": G("dhakara", "ذَكَرَ", "ذ ك ر", "verb", "to remember, to mention", "hatırlamak, anmak", 1),
 "idh": G("idh", "إِذْ", None, "noun", "when (of the past) — a ẓarf", "o zaman ki, -dığı zaman (mâzî zarfı)", 3),
 "qalil": G("qalil", "قَلِيل", "ق ل ل", "noun", "few, little", "az", 1),
 "kaththara": G("kaththara", "كَثَّرَ", "ك ث ر", "verb", "to make many, to multiply (Form II)", "çoğaltmak (tef'îl)", 2),
 "nazara": G("nazara", "نَظَرَ", "ن ظ ر", "verb", "to look (نَظَرَ فِي / إِلَى)", "bakmak", 1),
 "kayfa": G("kayfa", "كَيْفَ", None, "noun", "how (the question noun)", "nasıl (istifham ismi)", 1),
 "aqiba": G("aqiba", "عَاقِبَة", "ع ق ب", "noun", "the end, the outcome", "âkıbet, son", 2),
 "mufsid": G("mufsid", "مُفْسِد", "ف س د", "noun", "a corrupter, one who spreads mischief (ism fāʿil of أَفْسَدَ)", "bozguncu, müfsit", 2),
 "daqqaqa": G("daqqaqa", "دَقَّقَ", "د ق ق", "verb", "to scrutinise, to examine minutely (Form II)", "inceden inceye incelemek (tef'îl)", 4),
 "dhaki": G("dhaki", "ذَكِيّ", "ذ ك و", "noun", "clever, intelligent", "zeki", 2, plural="أَذْكِيَاء"),
 "tafsir": G("tafsir", "تَفْسِير", "ف س ر", "noun", "interpretation, explanation (masdar of فَسَّرَ)", "tefsir, yorum", 2),
 "hadhihi": G("hadhihi", "هَذِهِ", None, "pron", "this (feminine)", "bu (müennes)", 1),
 "dawa": G("dawa", "دَعْوَة", "د ع و", "noun", "a call, an invitation", "davet, çağrı", 2),
 "talil": G("talil", "تَعْلِيل", "ع ل ل", "noun", "reasoning, giving the cause (masdar of عَلَّلَ)", "ta'lîl — sebep gösterme", 4),
 "tih": G("tih", "تِيه", "ت ي ه", "noun", "conceit, haughtiness; a trackless desert", "kibir, şaşkınlık; çöl", 4),
 "zahw": G("zahw", "زَهْو", "ز ه و", "noun", "vanity, pride", "böbürlenme, kibir", 4),
 "kaanna": G("kaanna", "كَأَنَّ", None, "part", "as if, as though — the sister of إِنَّ that likens", "keenne — sanki; benzetme bildiren inne kardeşi", 3),
 "iktashafa": G("iktashafa", "اِكْتَشَفَ", "ك ش ف", "verb", "to discover, to uncover (Form VIII)", "keşfetmek (iftiâl)", 3),
 "sirr": G("sirr", "سِرّ", "س ر ر", "noun", "a secret", "sır", 1),
 "aw": G("aw", "أَوْ", None, "part", "or", "yahut", 1),
 "fakka": G("fakka", "فَكَّ", "ف ك ك", "verb", "to undo, to solve (a riddle)", "çözmek", 3),
 "lughz": G("lughz", "لُغْز", "ل غ ز", "noun", "a riddle", "bilmece, lugaz", 3),
 "shuayb": G("shuayb", "شُعَيْب", None, "propn", "Shuʿayb — the prophet of Madyan", "Şuayb — Medyen'in peygamberi", 1),
 "hamza-istifham": G("hamza-istifham", "أَ (الِاسْتِفْهَام)", None, "part", "the question hamza", "istifham hemzesi", 2),
 "salat": G("salat", "صَلَاة", "ص ل و", "noun", "prayer", "namaz, salât", 1),
 "pron-2ms": G("pron-2ms", "كَ", None, "pron", "you / your (masculine singular, attached)", "sen / senin (bitişik)", 1),
 "amara-v": G("amara-v", "أَمَرَ", "أ م ر", "verb", "to command", "emretmek", 1),
 "an-masdariyya": G("an-masdariyya", "أَنْ", None, "part", "that — the maṣdar-making particle that puts the muḍāriʿ in naṣb", "en — muzâriyi nasb eden masdariyye harfi", 2),
 "taraka": G("taraka", "تَرَكَ", "ت ر ك", "verb", "to leave", "bırakmak", 1),
 "ma-mawsula": G("ma-mawsula", "مَا (الْمَوْصُولَة)", None, "pron", "that which — the relative", "mâ-i mevsûle", 3),
 "faala": G("faala", "فَعَلَ", "ف ع ل", "verb", "to do", "yapmak", 1),
 "mal": G("mal", "مَال", "م و ل", "noun", "wealth, property", "mal", 1, plural="أَمْوَال"),
 "shaa": G("shaa", "شَاءَ", "ش ي أ", "verb", "to will, to please", "dilemek", 1),
 "inna": G("inna", "إِنَّ", None, "part", "indeed — puts its ism in naṣb and its khabar in rafʿ", "inne — şüphesiz; ismini nasb, haberini ref' eder", 1),
 "anta": G("anta", "أَنْتَ", None, "pron", "you (masculine singular)", "sen", 1),
 "lam-ibtida": G("lam-ibtida", "لَ (لَامُ الِابْتِدَاءِ)", None, "part", "the lām of ibtidāʾ — slid onto the khabar of إِنَّ", "ibtidâ lâmı — inne'nin haberine kayan lâm", 4),
 "halim": G("halim", "حَلِيم", "ح ل م", "noun", "forbearing, mild", "halîm — yumuşak huylu", 2),
 "rashid": G("rashid", "رَشِيد", "ر ش د", "noun", "right-minded, rightly guided", "reşîd — aklı başında", 2),
 "talattafa": G("talattafa", "تَلَطَّفَ", "ل ط ف", "verb", "to be gentle, to deal kindly (تَلَطَّفَ لِ) (Form V)", "yumuşak davranmak (tefa''ul)", 4),
 "lam": G("lam", "لَمْ", None, "part", "did not — negates the muḍāriʿ, puts it in jazm and turns it to the past", "lem — muzâriyi cezm eder ve mâzîye çevirir", 2),
 "qasa-harsh": G("qasa-harsh", "قَسَا", "ق س و", "verb", "to be harsh, to harden", "sertleşmek, katılaşmak", 3),
 "ghadiba": G("ghadiba", "غَضِبَ", "غ ض ب", "verb", "to be angry (غَضِبَ عَلَى)", "gazap etmek, kızmak", 2),
 "afhama": G("afhama", "أَفْهَمَ", "ف ه م", "verb", "to make understand (two objects) (Form IV)", "anlatmak, anlamasını sağlamak (if'âl)", 3),
 "anna": G("anna", "أَنَّ", None, "part", "that — the sister of إِنَّ that makes its clause a maṣdar", "enne — ki; cümlesini masdar kılan inne kardeşi", 2),
 "hamala": G("hamala", "حَمَلَ", "ح م ل", "verb", "to carry; حَمَلَهُ عَلَى: to move him to", "taşımak; hamelehû alâ: onu … -e sevk etmek", 2),
 "samt": G("samt", "صَمْت", "ص م ت", "noun", "silence", "sessizlik, sükût", 3),
 "tawil-long": G("tawil-long", "طَوِيل", "ط و ل", "noun", "long", "uzun", 1),
 "adam": G("adam", "عَدَم", "ع د م", "noun", "non-existence, absence of", "yokluk, -memezlik", 3),
 "taarrud": G("taarrud", "تَعَرُّض", "ع ر ض", "noun", "touching upon, confronting (masdar of تَعَرَّضَ)", "dokunma, karşı çıkma", 4),
 "khuluq": G("khuluq", "خُلُق", "خ ل ق", "noun", "character, moral; plural أَخْلَاق: morals", "huy, ahlâk", 2, plural="أَخْلَاق"),
 "fasid": G("fasid", "فَاسِد", "ف س د", "noun", "corrupt (ism fāʿil of فَسَدَ)", "bozuk, fâsit", 2),
 "tasarruf": G("tasarruf", "تَصَرُّف", "ص ر ف", "noun", "a dealing, conduct (masdar of تَصَرَّفَ)", "davranış, tasarruf", 3, plural="تَصَرُّفَات"),
 "jair": G("jair", "جَائِر", "ج و ر", "noun", "unjust, tyrannical (ism fāʿil of جَارَ)", "zalim, câir", 4),
 "illa": G("illa", "إِلَّا", None, "part", "except; (after a negation) only", "hâriç; ancak", 1),
 "akrama": G("akrama", "أَكْرَمَ", "ك ر م", "verb", "to honour (Form IV)", "ikram etmek, lütfetmek (if'âl)", 1),
 "akhir": G("akhir", "آخِر", "أ خ ر", "noun", "the end, the last; أَخِيرًا: lately, at last", "âhir — son; ahîran: sonunda, yakınlarda", 2),
 "nubuwwa": G("nubuwwa", "نُبُوَّة", "ن ب أ", "noun", "prophethood", "peygamberlik, nübüvvet", 2),
 "wahy": G("wahy", "وَحْي", "و ح ي", "noun", "revelation", "vahiy", 2),
 "sharaha": G("sharaha", "شَرَحَ", "ش ر ح", "verb", "to open (the breast); to explain", "açmak (göğsü); şerh etmek", 2),
 "sadr": G("sadr", "صَدْر", "ص د ر", "noun", "the breast, the chest; the front", "sadr — göğüs; baş", 3, plural="صُدُور"),
 "aataa": G("aataa", "آتَى", "أ ت ي", "verb", "to give (with two objects)", "vermek (iki mef'ûllü)", 4),
 "nur": G("nur", "نُور", "ن و ر", "noun", "light", "nur, ışık", 1),
 "inda": G("inda", "عِنْدَ", "ع ن د", "noun", "with, at (a ẓarf of place)", "yanında, nezdinde (mekân zarfı)", 2),
 "la-nafiya": G("la-nafiya", "لَا (النَّافِيَة)", None, "part", "the negating lā", "nefy lâ'sı", 1),
 "dhalika": G("dhalika", "ذَلِكَ", None, "pron", "that", "o, şu", 1),
 "hasad": G("hasad", "حَسَد", "ح س د", "noun", "envy", "haset", 2),
 "aghna": G("aghna", "أَغْنَى", "غ ن ي", "verb", "to make rich (Form IV)", "zengin etmek (if'âl)", 3),
 "razaqa": G("razaqa", "رَزَقَ", "ر ز ق", "verb", "to provide for (two objects)", "rızık vermek (iki mef'ûllü)", 1),
 "halal": G("halal", "حَلَال", "ح ل ل", "noun", "lawful", "helâl", 1),
 "tayyib": G("tayyib", "الطَّيِّب", "ط ي ب", "noun", "good, wholesome", "temiz, hoş", 1),
 "said": G("said", "سَعِيد", "س ع د", "noun", "happy", "mutlu, said", 1),
 "hani-content": G("hani-content", "هَنِيّ", "ه ن أ", "noun", "content, at ease (هَنِيُّ النَّفْسِ)", "hoşnut, gönlü hoş", 4),
 "nafs": G("nafs", "نَفْس", "ن ف س", "noun", "soul, self", "nefis, can", 1, plural="نُفُوس"),
 "rakhi": G("rakhi", "رَخِيّ", "ر خ و", "noun", "easy, relaxed (رَخِيُّ الْبَالِ: easy in mind)", "rahat (rahiyyü'l-bâl: zihni rahat)", 4),
 "bal-state": G("bal-state", "بَال", "ب و ل", "noun", "the mind, the state of mind", "bâl — zihin, hâl", 3),
 "shakir": G("shakir", "شَاكِر", "ش ك ر", "noun", "thankful (ism fāʿil of شَكَرَ)", "şükreden, şâkir", 2),
 "taala": G("taala", "تَعَالَى", "ع ل و", "verb", "to be exalted — تَعَالَى: Most High", "yüce olmak — Teâlâ", 2),
 "qalb": G("qalb", "قَلْب", "ق ل ب", "noun", "heart", "kalp", 1, plural="قُلُوب"),
 "lisan": G("lisan", "لِسَان", "ل س ن", "noun", "tongue; language", "dil", 1, plural="أَلْسِنَة"),
 "thumma": G("thumma", "ثُمَّ", None, "part", "then, moreover", "sonra", 1),
 "naha": G("naha", "نَهَى", "ن ه ي", "verb", "to forbid (نَهَى عَنْ)", "yasaklamak, nehyetmek", 2),
 "amr-noun": G("amr-noun", "أَمْر", "أ م ر", "noun", "a matter, an affair", "iş, husus", 2, plural="أُمُور"),
 "irtakaba": G("irtakaba", "اِرْتَكَبَ", "ر ك ب", "verb", "to commit (a wrong) (Form VIII)", "işlemek, irtikâp etmek (iftiâl)", 3),
 "manaa": G("manaa", "مَنَعَ", "م ن ع", "verb", "to prevent, to keep from", "engellemek, alıkoymak", 1),
 "ata": G("ata", "أَتَى", "أ ت ي", "verb", "to come; to do (a deed)", "gelmek; (bir işi) yapmak", 1),
 "laysa": G("laysa", "لَيْسَ", None, "verb", "is not — the frozen verb of negation", "leyse — değildir; câmid nefy fiili", 2),
 "alladhina": G("alladhina", "الَّذِينَ", None, "pron", "who, those who (masculine plural relative)", "ellezîne — cemi müzekker ism-i mevsûl", 2),
 "birr": G("birr", "بِرّ", "ب ر ر", "noun", "piety, righteousness", "iyilik, birr", 2),
 "nasiya": G("nasiya", "نَسِيَ", "ن س ي", "verb", "to forget", "unutmak", 1),
 "innama": G("innama", "إِنَّمَا", None, "part", "only — إِنَّ restrained by مَا: the tool of restriction", "innemâ — ancak; mâ ile kâffe olmuş inne: hasr edatı", 3),
 "arada": G("arada", "أَرَادَ", "ر و د", "verb", "to want, to intend (Form IV)", "istemek (if'âl)", 1),
 "isad": G("isad", "إِسْعَاد", "س ع د", "noun", "making happy (masdar of أَسْعَدَ)", "mutlu etme", 3),
 "inqadh": G("inqadh", "إِنْقَاذ", "ن ق ذ", "noun", "saving, rescue (masdar of أَنْقَذَ)", "kurtarma", 3),
 "adhab": G("adhab", "عَذَاب", "ع ذ ب", "noun", "punishment, torment", "azap", 1),
 "alladhi": G("alladhi", "الَّذِي", None, "pron", "who, which, that (masculine relative)", "ellezî — müzekker ism-i mevsûl", 2),
 "hallaqa": G("hallaqa", "حَلَّقَ", "ح ل ق", "verb", "to hover, to circle in the air (Form II)", "havada dönmek, dolaşmak (tef'îl)", 4),
 "ras": G("ras", "رَأْس", "ر أ س", "noun", "head", "baş", 1, plural="رُؤُوس"),
 "fadl": G("fadl", "فَضْل", "ف ض ل", "noun", "grace, favour; merit", "lütuf, fazilet", 2),
 "rajaa": G("rajaa", "رَجَعَ", "ر ج ع", "verb", "to return", "dönmek", 1),
 "ila": G("ila", "إِلَى", None, "prep", "to, towards", "-e, -e doğru", 1),
 "itimad": G("itimad", "اِعْتِمَاد", "ع م د", "noun", "reliance (masdar of اعْتَمَدَ)", "dayanma, itimat", 3),
 "raa": G("raa", "رَأَى", "ر أ ي", "verb", "to see; أَرَأَيْتُمْ: have you considered", "görmek; eraeytüm: söyleyin bakalım", 1),
 "rizq": G("rizq", "رِزْق", "ر ز ق", "noun", "provision, sustenance", "rızık", 1),
 "hasan": G("hasan", "حَسَن", "ح س ن", "noun", "good, fine", "güzel, hasen", 1),
 "khalafa": G("khalafa", "خَالَفَ", "خ ل ف", "verb", "to go against, to oppose (Form III)", "aykırı davranmak, muhalefet etmek (müfâale)", 2),
 "an": G("an", "عَنْ", None, "prep", "from, about; by way of", "-den, hakkında", 1),
 "ma-masdariyya": G("ma-masdariyya", "مَا (الْمَصْدَرِيَّة)", None, "part", "the mā that makes a maṣdar; with time: as long as", "masdariyye mâ; zamanla: -dığı sürece", 4),
 "istataa": G("istataa", "اِسْتَطَاعَ", "ط و ع", "verb", "to be able (Form X)", "gücü yetmek (istif'âl)", 2),
 "tawfiq": G("tawfiq", "تَوْفِيق", "و ف ق", "noun", "success granted by God", "tevfik, muvaffakiyet", 3),
 "tawakkala": G("tawakkala", "تَوَكَّلَ", "و ك ل", "verb", "to rely (تَوَكَّلَ عَلَى) (Form V)", "tevekkül etmek, dayanmak (tefa''ul)", 2),
 "anaba": G("anaba", "أَنَابَ", "ن و ب", "verb", "to turn in repentance (أَنَابَ إِلَى) (Form IV)", "yönelmek, tövbe ile dönmek (if'âl)", 3),
 "nun-wiqaya": G("nun-wiqaya", "نِ (نُونُ الْوِقَايَةِ)", None, "part", "the nūn of protection before the speaker's yāʾ", "vikâye nûnu — mütekellim yâsından önce", 4),
 "pron-1s": G("pron-1s", "ـي", None, "pron", "I / me / my", "ben", 1),
 "pron-1p": G("pron-1p", "نَا", None, "pron", "we / us / our", "biz", 1),
 "pron-3ms": G("pron-3ms", "هُ", None, "pron", "he / him / his (attached)", "o / onun (bitişik)", 1),
 "pron-3mp": G("pron-3mp", "هُمْ", None, "pron", "they / their (masculine plural, attached)", "onlar / onların (bitişik)", 1),
 "pron-2mp": G("pron-2mp", "ـكُمْ", None, "pron", "you / your (masculine plural, attached)", "siz / sizin (bitişik)", 1),
 "pron-3fs": G("pron-3fs", "هَا", None, "pron", "she / it / her (attached)", "o / onun (bitişik)", 1),
 "wa": G("wa", "وَ", None, "conj", "and", "ve", 1),
 "fa": G("fa", "فَ", None, "conj", "so, then", "o hâlde, sonra", 1),
 "bi": G("bi", "بِ", None, "prep", "by, with", "ile", 1),
 "li": G("li", "لِ", None, "prep", "for, to", "için", 1),
 "min": G("min", "مِنْ", None, "prep", "from, of", "-den", 1),
 "ala": G("ala", "عَلَى", None, "prep", "on, over", "üzerine, -e", 1),
 "fi": G("fi", "فِي", None, "prep", "in", "-de", 1),
}
GLOSS_ADD = {k: v for k, v in CAND.items() if v and k not in TG}
mo = json.loads((PKG / "morphology.json").read_text(encoding="utf-8"))
put_morph(mo, "tanawwaa", _sg.derived(_sg.B5, _sg.W5, "َ", "تَنَوَّع", "تَنَوَّع", "تَنَوَّع", "تَنَوُّع", "مُتَنَوِّع", None, None, None, "تَنَوَّعَ يَتَنَوَّعُ: صَارَ أَنْوَاعًا — بَابُ التَّفَعُّلِ، لَازِمٌ"))
put_morph(mo, "tafannana", _sg.derived(_sg.B5, _sg.W5, "َ", "تَفَنَّن", "تَفَنَّن", "تَفَنَّن", "تَفَنُّن", "مُتَفَنِّن", None, None, None, "تَفَنَّنَ يَتَفَنَّنُ: أَتَى بِفُنُونٍ — بَابُ التَّفَعُّلِ، لَازِمٌ"))
put_morph(mo, "awada", _sg.derived(_sg.B4 + " — مِثَالٌ وَاوِيٌّ", _sg.W4, "ُ", "أَوْعَد", "وعِد", "أَوْعِد", "إِيعَاد", "مُوعِد", "مُوعَد", "أُوعِدَ", "يُوعَدُ", "أَوْعَدَ يُوعِدُ: هَدَّدَ — بَابُ الْإِفْعَالِ، مِثَالٌ وَاوِيٌّ: تُوعِدُونَ"))
put_morph(mo, "daqqaqa", _sg.derived(_sg.B2, _sg.W2, "ُ", "دَقَّق", "دَقِّق", "دَقِّق", "تَدْقِيق", "مُدَقِّق", "مُدَقَّق", "دُقِّقَ", "يُدَقَّقُ", "دَقَّقَ يُدَقِّقُ: أَمْعَنَ النَّظَرَ — بَابُ التَّفْعِيلِ"))
put_morph(mo, "iktashafa", _sg.derived(_sg.B8, _sg.W8, "َ", "اِكْتَشَف", "كْتَشِف", "اِكْتَشِف", "اِكْتِشَاف", "مُكْتَشِف", "مُكْتَشَف", "اُكْتُشِفَ", "يُكْتَشَفُ", "اِكْتَشَفَ يَكْتَشِفُ: ظَهَرَ لَهُ مَا كَانَ خَفِيًّا — بَابُ الِافْتِعَالِ"))
put_morph(mo, "fakka", _sg.entry(_sg.BABS["nasara"][0] + " — مُضَاعَفٌ", _sg.BABS["nasara"][1], "فَكّ", "فَاكّ", _sg.mazi14("فَكّ", "فَكَك"), _sg.mudari14("َ", "فُكّ", "فْكُك"), ["فُكَّ", "فُكَّا", "فُكُّوا", "فُكِّي", "فُكَّا", "اُفْكُكْنَ"], "يَفُكَّ", "يَفُكَّ", "تَفُكَّ", "مَفْكُوك", "فُكَّ", "يُفَكُّ", "فَكَّ يَفُكُّ: حَلَّ — مُضَاعَفٌ مِنْ بَابِ نَصَرَ"))
put_morph(mo, "talattafa", _sg.derived(_sg.B5, _sg.W5, "َ", "تَلَطَّف", "تَلَطَّف", "تَلَطَّف", "تَلَطُّف", "مُتَلَطِّف", None, None, None, "تَلَطَّفَ لَهُ يَتَلَطَّفُ: رَفَقَ بِهِ — بَابُ التَّفَعُّلِ"))
put_morph(mo, "qasa-harsh", _sg.naqis1("nasara", "نَاقِصٌ وَاوِيٌّ", "w", "قَسَ", "قْس", "u", "اُقْس", "قَسْوَة", "قَاسٍ", None, None, None, "قَسَا يَقْسُو: صَلُبَ وَاشْتَدَّ — نَاقِصٌ وَاوِيٌّ مِنْ بَابِ نَصَرَ؛ لَمْ يَقْسُ"))
put_morph(mo, "afhama", _sg.derived(_sg.B4, _sg.W4, "ُ", "أَفْهَم", "فْهِم", "أَفْهِم", "إِفْهَام", "مُفْهِم", "مُفْهَم", "أُفْهِمَ", "يُفْهَمُ", "أَفْهَمَ يُفْهِمُ: جَعَلَهُ يَفْهَمُ — بَابُ الْإِفْعَالِ، يَتَعَدَّى إِلَى مَفْعُولَيْنِ"))
put_morph(mo, "aghna", _sg.derived_naqis(_sg.B4 + " — نَاقِصٌ", _sg.W4, "ُ", "أَغْنَ", "غْن", "i", "أَغْن", "إِغْنَاء", "مُغْنٍ", "مُغْنًى", "أُغْنِيَ", "يُغْنَى", "أَغْنَى يُغْنِي: جَعَلَهُ غَنِيًّا — نَاقِصٌ مِنَ الْإِفْعَالِ"))
put_morph(mo, "irtakaba", _sg.derived(_sg.B8, _sg.W8, "َ", "اِرْتَكَب", "رْتَكِب", "اِرْتَكِب", "اِرْتِكَاب", "مُرْتَكِب", "مُرْتَكَب", "اُرْتُكِبَ", "يُرْتَكَبُ", "اِرْتَكَبَ يَرْتَكِبُ: فَعَلَ الذَّنْبَ — بَابُ الِافْتِعَالِ"))
put_morph(mo, "hallaqa", _sg.derived(_sg.B2, _sg.W2, "ُ", "حَلَّق", "حَلِّق", "حَلِّق", "تَحْلِيق", "مُحَلِّق", None, None, None, "حَلَّقَ يُحَلِّقُ: ارْتَفَعَ وَدَارَ فِي الْجَوِّ — بَابُ التَّفْعِيلِ"))
put_morph(mo, "tawakkala", _sg.derived(_sg.B5, _sg.W5, "َ", "تَوَكَّل", "تَوَكَّل", "تَوَكَّل", "تَوَكُّل", "مُتَوَكِّل", None, None, None, "تَوَكَّلَ عَلَى اللهِ يَتَوَكَّلُ: اعْتَمَدَ — بَابُ التَّفَعُّلِ"))
put_morph(mo, "anaba", _sg.derived_hollow(_sg.B4 + " — أَجْوَفُ", _sg.W4, "ُ", "أَنَاب", "أَنَب", "نِيب", "نِب", "أَنِيب", "أَنِب", "إِنَابَة", "مُنِيب", None, None, None, "أَنَابَ إِلَى اللهِ يُنِيبُ: رَجَعَ — بَابُ الْإِفْعَالِ، أَجْوَفُ"))
for _k, _v in GLOSS_ADD.items():
    if _v.get("pos") == "verb" and _k not in mo["verbs"] and has_morph(_k):
        mo["verbs"][_k] = find_morph(_k)
(PKG / "morphology.json").write_text(json.dumps(mo, ensure_ascii=False, indent=1), encoding="utf-8")
print("qisas4 ch3 gloss+morph ok", len(GLOSS_ADD))
ADD_EN = " Chapter 3 (print pp. 4–7, sections 5–7): the appeal in a second voice with 7:85–86 (s1–s3), the people's mocking answer with 11:87 (s4–s5), and Shuʿayb's explanation of his call with 11:88 (s6–s11)."
ADD_TR = " Üçüncü bölüm (baskı s. 4–7, 5–7. kısımlar): 7:85–86 ile ikinci bir sesle çağrı (s1–s3), kavmin alaycı cevabı 11:87 ile (s4–s5) ve Şuayb'ın çağrısını açıklaması 11:88 ile (s6–s11)."
write_out(3, S, TITLE, ADD_EN, ADD_TR, "sections 5–7", GLOSS_ADD, notes=(), related=())
report(3, S, GLOSS_ADD, ())
