# -*- coding: utf-8 -*-
"""Scaffold a new story's authoring script.

    python3 tools/authoring/new_story.py kitab-al-hajj "كِتَابُ الْحَجِّ" \\
        "The Book of Hajj" "Hac Bahsi" --level 4 --source hac-turkce.txt

Writes tools/authoring/author_<slug>.py with the proven skeleton — tok/J
helpers, one worked example sentence, the GLOSS/MORPH/MANIFEST scaffolding,
attribution marked ORIGINAL + pending-scholarly-review — so a new story is
a matter of authoring sentences, never of plumbing. The generated script is
the story's permanent regenerator and lives in the repo like the others.
"""
import argparse, pathlib, sys

TEMPLATE = '''# -*- coding: utf-8 -*-
"""Author content/samples/{slug} — generated by new_story.py, then hand-authored.

ORIGINAL graded Arabic, composed editorially from {source_note}.
Everything is marked pending-scholarly-review. Verb paradigms ride the
audited engines in sarf_gen; copy a paradigm from another package when the
corpus already owns the verb (lemma-identity rule).
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PKG = ROOT / "content/samples/{slug}"
(PKG / "chapters").mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import sarf_gen as _sg

import re
DIA = re.compile("[\\u064b-\\u0670]")
def bare(s): return DIA.sub("", s)

def tok(full, lex, pos, grammar, ar, en, tr, punct=None):
    t = {{"surface": {{"full": full, "smart": full, "bare": bare(full)}},
         "lex": lex, "pos": pos}}
    if grammar: t["grammar"] = grammar
    t["irab"] = {{"ar": ar, "en": en, "tr": tr}}
    if punct: t["punctAfter"] = punct
    return t

J = lambda text, ar, en, tr: {{"text": text, "ar": ar, "en": en, "tr": tr}}

S = []

# -- worked example: replace with the story's real first sentence. Every token
# needs trilingual i'rab; grammar ids must exist in content/grammar/.
S.append({{"id": "s1", "translation": {{
 "en": "TODO english translation.",
 "tr": "TODO türkçe çeviri."}},
 "tokens": [
  tok("التَّوْدَةُ","todo","noun",["mubtada-khabar"],
      "مُبْتَدَأٌ مَرْفُوعٌ.","The mubtada in raf'.","Merfû mübtedadır.", punct="."),
 ],
 "jumal": [
  J("…","جُمْلَةٌ اسْمِيَّةٌ ابْتِدَائِيَّةٌ — لَا مَحَلَّ لَهَا.",
    "An opening nominal clause — i'rabless.","İbtidâiyye isim cümlesi — mahalsizdir."),
 ]}})

TITLE1 = {{"ar": "TODO", "en": "TODO", "tr": "TODO"}}

GLOSS = {{
 "todo": {{"lemma": "تَوْدَة", "root": "ت و د", "pos": "noun",
   "gloss": {{"en": "todo", "tr": "todo"}}, "level": {level}}},
}}

MANIFEST = {{
 "id": "{slug}",
 "storyGroup": "{slug}",
 "title": {{"ar": "{title_ar}", "en": "{title_en}", "tr": "{title_tr}"}},
 "subtitle": {{"ar": "TODO", "en": "TODO", "tr": "TODO"}},
 "level": {level},
 "levelName": "{level_name}",
 "version": "0.1.0",
 "published": "TODO-DATE",
 "access": "premium",
 "chapters": [{{"n": 1, "title": TITLE1}}],
 "siblings": [],
 "attribution": {{
  "ar": "عَرَبِيَّةٌ أَصْلِيَّةٌ مُيَسَّرَةٌ صِيغَتْ تَحْرِيرِيًّا.",
  "en": ("ORIGINAL graded Arabic, composed editorially from {source_note}. "
         "No sentence here may be cited as a classical text. Chapter 1 is the opening; "
         "further chapters follow release by release."),
  "tr": ("ÖZGÜN kolaylaştırılmış Arapça; {source_note} kaynağından editoryal olarak telif "
         "edilmiştir. Buradaki hiçbir cümle klasik metin diye iktibas edilemez. 1. bölüm "
         "giriştir; sonraki bölümler sürüm sürüm gelecektir."),
  "reviewStatus": "pending-scholarly-review"
 }}
}}

MORPH = {{"verbs": {{}}}}

ALL = S

(PKG / "manifest.json").write_text(json.dumps(MANIFEST, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "chapters/1.json").write_text(json.dumps({{"chapter": 1, "sentences": S}}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "glossary.json").write_text(json.dumps({{"entries": GLOSS}}, ensure_ascii=False, indent=1), encoding="utf-8")
(PKG / "morphology.json").write_text(json.dumps(MORPH, ensure_ascii=False, indent=1), encoding="utf-8")

used = {{t["lex"] for s in ALL for t in s["tokens"]}}
dead = set(GLOSS) - used
missing = used - set(GLOSS)
print("tokens:", sum(len(s["tokens"]) for s in ALL), "gloss:", len(GLOSS),
      "dead:", sorted(dead), "missing:", sorted(missing))
'''

LEVEL_NAMES = {1: "Beginner", 2: "Elementary", 3: "Intermediate",
               4: "Upper Intermediate", 5: "Advanced", 6: "Master"}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    ap.add_argument("title_ar")
    ap.add_argument("title_en")
    ap.add_argument("title_tr")
    ap.add_argument("--level", type=int, default=4)
    ap.add_argument("--source", default="the project owner's uploaded source")
    args = ap.parse_args()
    here = pathlib.Path(__file__).parent
    out = here / f"author_{args.slug.replace('-', '_')}.py"
    if out.exists():
        print(f"refusing to overwrite {out}"); sys.exit(1)
    out.write_text(TEMPLATE.format(
        slug=args.slug, title_ar=args.title_ar, title_en=args.title_en,
        title_tr=args.title_tr, level=args.level,
        level_name=LEVEL_NAMES.get(args.level, "Upper Intermediate"),
        source_note=args.source), encoding="utf-8")
    print(f"scaffolded {out}")
    print("next: author sentences, set the published date, then run it and tools/release.py")
    print("(the stub INTENTIONALLY fails validation until every TODO is replaced —")
    print(" a placeholder can never slip onto the shelf)")

if __name__ == "__main__":
    main()
