#!/usr/bin/env python3
"""Regenerate the embedded data block in prototype/reader.html from a content package.

The prototype is a renderer; the content packages are the source of truth. This script
reads a story package + the global grammar dir, transforms them into the JS constants the
prototype expects, and splices them between the __DATA_START__ / __DATA_END__ markers.

Usage:
    python3 tools/build_prototype.py [--package content/samples/wasiyyat-abi-hanifa]
        [--grammar-dir content/samples/grammar] [--html prototype/reader.html]

Run tools/validate_content.py first — this script refuses obviously broken input but
does not repeat full validation.
"""
import argparse
import json
from pathlib import Path

START = "// __DATA_START__"
END = "// __DATA_END__"


def bilingual(value):
    """Normalize plain strings and {en, tr} objects to {en, tr}."""
    if isinstance(value, dict):
        return {"en": value.get("en", ""), "tr": value.get("tr", value.get("en", ""))}
    return {"en": value or "", "tr": value or ""}


def build_glossary(pkg: Path):
    return json.load(open(pkg / "glossary.json", encoding="utf-8"))["entries"]


def build_morph(pkg: Path):
    path = pkg / "morphology.json"
    if not path.exists():
        return {}
    verbs = json.load(open(path, encoding="utf-8"))["verbs"]
    out = {}
    for lex, m in verbs.items():
        entry = {"bab": m["bab"], "wazn": m["wazn"], "masdar": m["masdar"],
                 "fail": m["ismFail"], "mazi": m["mazi"], "mudari": m["mudari"], "amr": m["amr"]}
        if m.get("ismMaful"):
            entry["maful"] = m["ismMaful"]
        if m.get("note"):
            entry["note"] = m["note"]
        out[lex] = entry
    return out


def build_chapters(pkg: Path):
    manifest = json.load(open(pkg / "manifest.json", encoding="utf-8"))
    chapters = []
    for ch in manifest["chapters"]:
        data = json.load(open(pkg / "chapters" / f"{ch['n']}.json", encoding="utf-8"))
        sentences = []
        for sen in data["sentences"]:
            tokens = []
            for tok in sen["tokens"]:
                t = {"s": tok["surface"], "lex": tok["lex"]}
                for key in ("grammar", "punctAfter", "quoteBefore", "quoteAfter", "irab"):
                    if tok.get(key):
                        t[key] = tok[key]
                if tok.get("segments"):
                    t["segments"] = [{"form": s["form"], "lex": s["lex"]} for s in tok["segments"]]
                tokens.append(t)
            sentences.append({"id": sen["id"], "translation": sen["translation"], "tokens": tokens})
        chapters.append({"n": ch["n"], "title": ch["title"], "sentences": sentences})
    return manifest, chapters


def build_grammar(grammar_dir: Path, story_id: str):
    notes = {}
    for path in sorted(grammar_dir.glob("*.json")):
        g = json.load(open(path, encoding="utf-8"))
        note = {"title": g["title"], "level": g.get("level"), "group": g.get("group", "nahw"),
                "explanation": bilingual(g.get("explanation"))}
        if g.get("amil"):
            note["amil"] = g["amil"]
        if g.get("classicalSources"):
            note["sources"] = g["classicalSources"]
        note["examples"] = [
            {"ar": x["ar"],
             "en": x.get("en", "") + (" — from this story" if x.get("sourceStory") == story_id else ""),
             "fromStory": x.get("sourceStory") == story_id}
            for x in g.get("examples", [])
        ]
        note["mistakes"] = [
            {"wrong": m["wrong"], "right": m["right"], "why": bilingual(m.get("why"))}
            for m in g.get("commonMistakes", [])
        ]
        notes[g["id"]] = note
    return notes


def js(name, value):
    return f"const {name} = {json.dumps(value, ensure_ascii=False, separators=(',', ':'))};"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    ap.add_argument("--package", type=Path, default=root / "content/samples/wasiyyat-abi-hanifa")
    ap.add_argument("--grammar-dir", type=Path, default=root / "content/grammar")
    ap.add_argument("--html", type=Path, default=root / "prototype/reader.html")
    args = ap.parse_args()

    manifest, chapters = build_chapters(args.package)
    block = "\n".join([
        START,
        "// Generated by tools/build_prototype.py — DO NOT EDIT BY HAND.",
        f"// Source package: {args.package.name} v{manifest.get('version')}",
        js("GLOSSARY", build_glossary(args.package)),
        js("MORPH", build_morph(args.package)),
        js("CHAPTERS", chapters),
        js("GRAMMAR", build_grammar(args.grammar_dir, manifest["id"])),
        js("REF_GROUPS", [
            {"id": "sarf", "ar": "الصَّرْف", "en": "Morphology — after Emsile & Bina"},
            {"id": "nahw", "ar": "النَّحْو", "en": "Syntax — after al-Kafiya & Qatr al-Nada"},
            {"id": "awamil", "ar": "الْعَوَامِل", "en": "Governors — after Birgivi's Awamil"},
        ]),
        END,
    ])

    html = args.html.read_text(encoding="utf-8")
    i, j = html.find(START), html.find(END)
    if i == -1 or j == -1:
        raise SystemExit(f"markers {START} / {END} not found in {args.html}")
    html = html[:i] + block + html[j + len(END):]

    # Stamp the static header from the manifest so standalone readers are correct.
    import re
    title = manifest["title"]
    subtitle = manifest.get("subtitle", {}).get("en") or title.get("en", "")
    access = {"free": "Free story", "premium": "Premium story",
              "user-upload": "Your upload · machine-analyzed"}.get(manifest.get("access"), "")
    chips = (f'<span class="chip level">Level {manifest["level"]}'
             f' · {manifest.get("levelName", "")}</span>\n      '
             f'<span class="chip">{len(chapters)} chapter{"s" if len(chapters) != 1 else ""}</span>'
             + (f'\n      <span class="chip">{access}</span>' if access else ""))
    html = re.sub(r'<h1 class="story-title">.*?</h1>',
                  f'<h1 class="story-title">{title["ar"]}</h1>', html, flags=re.S)
    html = re.sub(r'<p class="story-sub">.*?</p>',
                  f'<p class="story-sub">{subtitle}</p>', html, flags=re.S)
    html = re.sub(r'(<div class="meta-row">\s*).*?(\s*</div>)',
                  lambda m: m.group(1) + chips + m.group(2), html, count=1, flags=re.S)
    args.html.write_text(html, encoding="utf-8")
    n_tokens = sum(len(s["tokens"]) for c in chapters for s in c["sentences"])
    print(f"Rebuilt {args.html}: {len(chapters)} chapters, {n_tokens} tokens, "
          f"{len(build_grammar(args.grammar_dir, manifest['id']))} grammar notes")


if __name__ == "__main__":
    main()
